#ifndef _shy_win_platform_render_texture_loader_insider_injections_included
#define _shy_win_platform_render_texture_loader_insider_injections_included

#include "src/platform/render/texture/loader/winapi/insider/shy_insider_injections.h"
typedef so_called_platform_render_texture_loader_winapi_insider so_called_platform_render_texture_loader_insider ;

#endif
