#ifndef _shy_message_common_logic_salutation_animation_zoom_play_injections_included
#define _shy_message_common_logic_salutation_animation_zoom_play_injections_included

#include "./shy_play.h"

typedef shy_message_common_logic_salutation_animation_zoom_play so_called_message_common_logic_salutation_animation_zoom_play ;

#endif
