#ifndef _shy_sender_common_logic_salutation_letters_animation_roll_out_play_injections_included
#define _shy_sender_common_logic_salutation_letters_animation_roll_out_play_injections_included

#include "common/logic/salutation/letters/animation/roll_out/play/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_animation_roll_out_play so_called_sender_common_logic_salutation_letters_animation_roll_out_play ;

#endif
