#ifndef _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_sender_injections_included

#include "src/common/logic/main/menu/letters/animation/unselection/weight/select/row/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_sender so_called_common_logic_main_menu_letters_animation_unselection_weight_select_row_sender ;

#endif
