#ifndef _shy_common_engine_render_mesh_set_triangle_fan_index_value_sender_injections_included
#define _shy_common_engine_render_mesh_set_triangle_fan_index_value_sender_injections_included

#include "common/engine/render/message/mesh_set_triangle_fan_index_value/shy_mesh_set_triangle_fan_index_value_injections.h"

#include "./shy_mesh_set_triangle_fan_index_value.h"

typedef shy_common_engine_render_mesh_set_triangle_fan_index_value_sender so_called_common_engine_render_mesh_set_triangle_fan_index_value_sender ;

#endif

