// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_salutation_timer_consts :: time_appear = so_called_platform_math :: init_num_fract ( 4 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_timer_consts :: time_disappear = so_called_platform_math :: init_num_fract ( 2 , 1 ) ;

// autogenerated file end
