#ifndef _shy_message_common_logic_land_prepared_injections_included
#define _shy_message_common_logic_land_prepared_injections_included

#include "./shy_prepared.h"

typedef shy_message_common_logic_land_prepared so_called_message_common_logic_land_prepared ;

#endif
