#ifndef _shy_common_logic_door_mesh_render_reply_sender_injections_included
#define _shy_common_logic_door_mesh_render_reply_sender_injections_included

#include "common/logic/door/message/mesh_render_reply/shy_mesh_render_reply_injections.h"

#include "./shy_mesh_render_reply.h"

typedef shy_common_logic_door_mesh_render_reply_sender so_called_common_logic_door_mesh_render_reply_sender ;

#endif
