#ifndef _shy_common_engine_render_projection_frustum_sender_injections_included
#define _shy_common_engine_render_projection_frustum_sender_injections_included

#include "../../message/projection_frustum/shy_projection_frustum_injections.h"

#include "./shy_projection_frustum.h"

typedef shy_common_engine_render_projection_frustum_sender so_called_common_engine_render_projection_frustum_sender ;

#endif

