#ifndef _shy_common_logic_main_menu_selection_animation_push_weight_request_sender_injections_included
#define _shy_common_logic_main_menu_selection_animation_push_weight_request_sender_injections_included

#include "../../message/push_weight_request/shy_push_weight_request_injections.h"

#include "./shy_push_weight_request.h"

typedef shy_common_logic_main_menu_selection_animation_push_weight_request_sender so_called_common_logic_main_menu_selection_animation_push_weight_request_sender ;

#endif
