#ifndef _shy_common_logic_text_letter_mesh_create_reply_message_injections_included
#define _shy_common_logic_text_letter_mesh_create_reply_message_injections_included

#include "common/logic/text/type/letter_id/shy_letter_id_injections.h"
#include "common/engine/render/type/mesh_id/shy_mesh_id_injections.h"

#include "./shy_create_reply.h"

typedef shy_common_logic_text_letter_mesh_create_reply_message so_called_common_logic_text_letter_mesh_create_reply_message ;

#endif
