const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_color_a ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_color_b ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_color_g ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_color_r ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_u_bottom_left ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_u_bottom_right ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_u_top_left ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_u_top_right ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_v_bottom_left ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_v_bottom_right ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_v_top_left ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_v_top_right ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_x_left ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_x_right ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_y_bottom ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_y_top ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: mesh_z ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_paper_a ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_paper_b ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_paper_g ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_paper_r ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_pen_a ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_pen_b ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_pen_g ;
const so_called_platform_math_num_fract_type shy_common_logic_door_consts :: texture_pen_r ;
const so_called_platform_math_num_whole_type shy_common_logic_door_consts :: texture_stripes ;

void shy_common_logic_door_consts :: binding ( )
{
}
