#include "./shy_sender_injections.h"

#include "src/common/logic/main/menu/animation/shake/shy_shake_injections.h"
#include "src/common/logic/main/menu/choice/shy_choice_injections.h"
#include "src/common/logic/main/menu/letters/animation/appear/shy_appear_injections.h"
#include "src/common/logic/main/menu/letters/animation/disappear/shy_disappear_injections.h"
#include "src/common/logic/main/menu/letters/animation/idle/shy_idle_injections.h"
#include "src/common/logic/main/menu/letters/animation/selection/shy_selection_injections.h"
#include "src/common/logic/main/menu/letters/animation/selection/push/shy_push_injections.h"
#include "src/common/logic/main/menu/letters/animation/selection/weight/shy_weight_injections.h"
#include "src/common/logic/main/menu/letters/animation/unselection/weight/shy_weight_injections.h"
#include "src/common/logic/main/menu/letters/meshes/creation/director/shy_director_injections.h"
#include "src/common/logic/main/menu/selection/animation/appear/shy_appear_injections.h"
#include "src/common/logic/main/menu/selection/animation/disappear/shy_disappear_injections.h"
#include "src/common/logic/main/menu/selection/animation/idle/attention/shy_attention_injections.h"
#include "src/common/logic/main/menu/selection/animation/push/shy_push_injections.h"
#include "src/common/logic/main/menu/selection/animation/push/attention/shy_attention_injections.h"
#include "src/common/logic/main/menu/selection/animation/push/weight/shy_weight_injections.h"
#include "src/common/logic/main/menu/selection/animation/select/shy_select_injections.h"
#include "src/common/logic/main/menu/selection/animation/unselect/shy_unselect_injections.h"
#include "src/common/logic/main/menu/shy_menu_injections.h"

#include "./shy_sender.hpp"
