#ifndef _shy_message_common_logic_room_render_permit_injections_included
#define _shy_message_common_logic_room_render_permit_injections_included

#include "./shy_render_permit.h"

typedef shy_message_common_logic_room_render_permit so_called_message_common_logic_room_render_permit ;

#endif
