#ifndef _shy_common_logic_blanket_mesh_set_transform_sender_injections_included
#define _shy_common_logic_blanket_mesh_set_transform_sender_injections_included

#include "src/common/logic/blanket/mesh/set/transform/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_blanket_mesh_set_transform_sender so_called_common_logic_blanket_mesh_set_transform_sender ;

#endif
