#ifndef _shy_macosx_platform_render_injections_included
#define _shy_macosx_platform_render_injections_included

#include "src/platform/render/opengl/shy_opengl_injections.h"
typedef so_called_platform_render_opengl so_called_platform_render ;

#endif
