#ifndef _shy_sender_common_logic_salutation_timer_disappear_run_finished_injections_included
#define _shy_sender_common_logic_salutation_timer_disappear_run_finished_injections_included

#include "../../message/run_finished/shy_run_finished_injections.h"
#include "./shy_run_finished.h"

typedef shy_sender_common_logic_salutation_timer_disappear_run_finished so_called_sender_common_logic_salutation_timer_disappear_run_finished ;

#endif
