#ifndef _shy_common_logic_controls_state_request_sender_injections_included
#define _shy_common_logic_controls_state_request_sender_injections_included

#include "common/logic/controls/message/state_request/shy_state_request_injections.h"

#include "./shy_state_request.h"

typedef shy_common_logic_controls_state_request_sender so_called_common_logic_controls_state_request_sender ;

#endif
