#ifndef _shy_common_logic_core_near_plane_distance_reply_sender_injections_included
#define _shy_common_logic_core_near_plane_distance_reply_sender_injections_included

#include "common/logic/core/message/near_plane_distance_reply/shy_near_plane_distance_reply_injections.h"

#include "./shy_near_plane_distance_reply.h"

typedef shy_common_logic_core_near_plane_distance_reply_sender so_called_common_logic_core_near_plane_distance_reply_sender ;

#endif
