#ifndef _shy_common_logic_main_menu_selection_animation_idle_void_selected_message_injections_included
#define _shy_common_logic_main_menu_selection_animation_idle_void_selected_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_main_menu_selection_animation_idle_void_selected_message so_called_common_logic_main_menu_selection_animation_idle_void_selected_message ;

#endif
