#ifndef _shy_sender_common_logic_main_menu_letters_meshes_iterate_finished_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_iterate_finished_injections_included

#include "../../message/iterate_finished/shy_iterate_finished_injections.h"

#include "./shy_iterate_finished.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_iterate_finished so_called_sender_common_logic_main_menu_letters_meshes_iterate_finished ;

#endif
