#include "./shy_entities_injections.h"

#include "common/logic/entities/sender/height_reply/shy_height_reply_injections.h"
#include "common/logic/entities/sender/mesh_grid_reply/shy_mesh_grid_reply_injections.h"
#include "common/logic/entities/sender/origin_reply/shy_origin_reply_injections.h"
#include "common/logic/entities/sender/prepared/shy_prepared_injections.h"
#include "common/logic/entities/sender/render_reply/shy_render_reply_injections.h"

#include "common/engine/math/stateless/shy_stateless_injections.h"
#include "common/engine/render/sender/mesh_create_request/shy_mesh_create_request_injections.h"
#include "common/engine/render/sender/mesh_finalize/shy_mesh_finalize_injections.h"
#include "common/engine/render/sender/mesh_render/shy_mesh_render_injections.h"
#include "common/engine/render/sender/mesh_set_vertex_color/shy_mesh_set_vertex_color_injections.h"
#include "common/engine/render/sender/mesh_set_vertex_position/shy_mesh_set_vertex_position_injections.h"
#include "common/engine/render/sender/mesh_set_vertex_tex_coord/shy_mesh_set_vertex_tex_coord_injections.h"
#include "common/engine/render/sender/mesh_set_transform/shy_mesh_set_transform_injections.h"
#include "common/engine/render/sender/mesh_set_triangle_fan_index_value/shy_mesh_set_triangle_fan_index_value_injections.h"
#include "common/engine/render/sender/mesh_set_triangle_strip_index_value/shy_mesh_set_triangle_strip_index_value_injections.h"
#include "common/engine/render/sender/texture_unselect/shy_texture_unselect_injections.h"

#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"
#include "injections/platform/matrix/shy_matrix.h"
#include "injections/platform/pointer/type/data/shy_data.h"
#include "injections/platform/static_array/shy_static_array.h"
#include "injections/platform/static_array/type/data/shy_data.h"
#include "injections/platform/vector/shy_vector.h"

#include "./shy_entities.hpp"

