#include "./shy_entities_injections.h"

#include "common/logic/entities/height/reply/sender/shy_sender_injections.h"
#include "common/logic/entities/mesh/grid/reply/sender/shy_sender_injections.h"
#include "common/logic/entities/origin/reply/sender/shy_sender_injections.h"
#include "common/logic/entities/prepared/sender/shy_sender_injections.h"
#include "common/logic/entities/render/reply/sender/shy_sender_injections.h"

#include "common/engine/math/stateless/shy_stateless_injections.h"
#include "common/engine/render/mesh/create/request/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/finalize/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/render/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/color/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/position/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/tex/coord/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/transform/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/triangle/fan/index/value/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/triangle/strip/index/value/sender/shy_sender_injections.h"
#include "common/engine/render/texture/unselect/sender/shy_sender_injections.h"

#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"
#include "injections/platform/matrix/shy_matrix.h"
#include "injections/platform/pointer/data/type/shy_type.h"
#include "injections/platform/static/array/shy_array.h"
#include "injections/platform/static/array/data/type/shy_type.h"
#include "injections/platform/vector/shy_vector.h"

#include "./shy_entities.hpp"

