#ifndef _shy_win_platform_render_insider_injections_included
#define _shy_win_platform_render_insider_injections_included

#include "src/platform/render/directx/insider/shy_insider_injections.h"
typedef so_called_platform_render_directx_insider so_called_platform_render_insider ;

#endif

