#ifndef _shy_win_lib_directx_injections_included
#define _shy_win_lib_directx_injections_included

#define so_called_lib_directx_D3DBLEND_INVSRCALPHA D3DBLEND_INVSRCALPHA
#define so_called_lib_directx_D3DBLEND_SRCALPHA D3DBLEND_SRCALPHA
#define so_called_lib_directx_D3DCLEAR_TARGET D3DCLEAR_TARGET
#define so_called_lib_directx_D3DCLEAR_ZBUFFER D3DCLEAR_ZBUFFER
#define so_called_lib_directx_D3DCOLOR_ARGB D3DCOLOR_ARGB
#define so_called_lib_directx_D3DCULL_NONE
#define so_called_lib_directx_D3DFMT_A8R8G8B8 D3DFMT_A8R8G8B8
#define so_called_lib_directx_D3DFOG_LINEAR D3DFOG_LINEAR
#define so_called_lib_directx_D3DPOOL_MANAGED D3DPOOL_MANAGED
#define so_called_lib_directx_D3DRS_ALPHABLENDENABLE D3DRS_ALPHABLENDENABLE
#define so_called_lib_directx_D3DRS_CULLMODE D3DRS_CULLMODE
#define so_called_lib_directx_D3DRS_DESTBLEND D3DRS_DESTBLEND 
#define so_called_lib_directx_D3DRS_FOGCOLOR D3DRS_FOGCOLOR 
#define so_called_lib_directx_D3DRS_FOGENABLE D3DRS_FOGENABLE
#define so_called_lib_directx_D3DRS_FOGEND D3DRS_FOGEND 
#define so_called_lib_directx_D3DRS_FOGSTART D3DRS_FOGSTART 
#define so_called_lib_directx_D3DRS_FOGVERTEXMODE D3DRS_FOGVERTEXMODE
#define so_called_lib_directx_D3DRS_SRCBLEND D3DRS_SRCBLEND 
#define so_called_lib_directx_D3DRS_ZENABLE D3DRS_ZENABLE
#define so_called_lib_directx_D3DTS_PROJECTION D3DTS_PROJECTION 
#define so_called_lib_directx_D3DXMatrixPerspectiveOffCenterRH D3DXMatrixPerspectiveOffCenterRH 
#define so_called_lib_directx_D3DZB_FALSE D3DZB_FALSE
#define so_called_lib_directx_D3DZB_TRUE D3DZB_TRUE
#define so_called_lib_directx_DXUTGetD3D9Device D3DUTGetD3D9Device
#define so_called_lib_directx_FALSE FALSE
#define so_called_lib_directx_TRUE TRUE 
#define so_called_lib_directx_V V

typedef BYTE so_called_lib_directx_BYTE ;
typedef D3DCOLOR so_called_lib_directx_D3DCOLOR ;
typedef D3DLOCKED_RECT so_called_lib_directx_D3DLOCKED_RECT ;
typedef D3DXMATRIX so_called_lib_directx_D3DXMATRIX ;
typedef DWORD so_called_lib_directx_DWORD ; 
typedef HRESULT so_called_lib_directx_HRESULT ;
typedef RECT so_called_lib_directx_RECT ;

#endif
