#ifndef _shy_sender_common_logic_main_menu_selection_mesh_create_finished_injections_included
#define _shy_sender_common_logic_main_menu_selection_mesh_create_finished_injections_included

#include "../../message/mesh_create_finished/shy_mesh_create_finished_injections.h"

#include "./shy_mesh_create_finished.h"

typedef shy_sender_common_logic_main_menu_selection_mesh_create_finished so_called_sender_common_logic_main_menu_selection_mesh_create_finished ;

#endif
