#ifndef _shy_sender_common_logic_main_menu_letters_letter_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_letter_reply_injections_included

#include "../../message/letter_reply/shy_letter_reply_injections.h"

#include "./shy_letter_reply.h"

typedef shy_sender_common_logic_main_menu_letters_letter_reply so_called_sender_common_logic_main_menu_letters_letter_reply ;

#endif
