#ifndef _shy_common_logic_main_menu_letters_letter_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_letter_reply_sender_injections_included

#include "common/logic/main_menu/letters/message/letter_reply/shy_letter_reply_injections.h"

#include "./shy_letter_reply.h"

typedef shy_common_logic_main_menu_letters_letter_reply_sender so_called_common_logic_main_menu_letters_letter_reply_sender ;

#endif
