#ifndef _shy_type_win_platform_render_vertex_data_injections_included
#define _shy_type_win_platform_render_vertex_data_injections_included

#include "platform/render/directx/type/vertex_data/shy_vertex_data_injections.h"
typedef so_called_type_platform_render_directx_vertex_data so_called_type_platform_render_vertex_data ;

#endif
