#ifndef _shy_loadable_consts_reflection_logic_main_menu_selection_injections_included
#define _shy_loadable_consts_reflection_logic_main_menu_selection_injections_included

#include "./shy_selection.h"

typedef shy_loadable_consts_reflection_logic_main_menu_selection so_called_loadable_consts_reflection_logic_main_menu_selection ;

#endif
