#ifndef _shy_common_engine_rasterizer_draw_ellipse_in_rect_message_injections_included
#define _shy_common_engine_rasterizer_draw_ellipse_in_rect_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_draw_ellipse_in_rect.h"

typedef shy_common_engine_rasterizer_draw_ellipse_in_rect_message so_called_common_engine_rasterizer_draw_ellipse_in_rect_message ;

#endif
