#ifndef _shy_sender_common_logic_room_texture_creation_finished_injections_included
#define _shy_sender_common_logic_room_texture_creation_finished_injections_included

#include "../../message/texture_creation_finished/shy_texture_creation_finished_injections.h"

#include "./shy_texture_creation_finished.h"

typedef shy_sender_common_logic_room_texture_creation_finished so_called_sender_common_logic_room_texture_creation_finished ;

#endif
