#ifndef _shy_common_video_mode_changed_message_injections_included
#define _shy_common_video_mode_changed_message_injections_included

#include "./shy_video_mode_changed.h"

typedef shy_common_video_mode_changed_message so_called_common_video_mode_changed_message ;

#endif
