#ifndef _shy_message_common_video_mode_changed_injections_included
#define _shy_message_common_video_mode_changed_injections_included

#include "./shy_video_mode_changed.h"

typedef shy_message_common_video_mode_changed so_called_message_common_video_mode_changed ;

#endif
