#ifndef _shy_type_loadable_fsm_content_system_injections_included
#define _shy_type_loadable_fsm_content_system_injections_included

#include "./shy_system.h"

typedef shy_type_loadable_fsm_content_system so_called_type_loadable_fsm_content_system ;

#endif
