#ifndef _shy_common_logic_text_letter_mesh_create_request_message_injections_included
#define _shy_common_logic_text_letter_mesh_create_request_message_injections_included

#include "common/logic/text/type/letter_id/shy_letter_id_injections.h"
#include "injections/platform/math/type/num_fract/shy_num_fract.h"

#include "./shy_create_request.h"

typedef shy_common_logic_text_letter_mesh_create_request_message so_called_common_logic_text_letter_mesh_create_request_message ;

#endif
