// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_main_menu_letters_layout_consts :: letter_size_fract_horizontal_border = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_main_menu_letters_layout_consts :: letter_size_fract_horizontal_spacing = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_main_menu_letters_layout_consts :: letter_size_fract_vertical_border = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_main_menu_letters_layout_consts :: letter_size_fract_vertical_spacing = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_main_menu_letters_layout_consts :: menu_position_z = so_called_platform_math :: init_num_fract ( - 3 , 1 ) ;

// autogenerated file end
