#ifndef _shy_common_logic_main_menu_selection_track_row_selected_message_injections_included
#define _shy_common_logic_main_menu_selection_track_row_selected_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_track_row_selected.h"

typedef shy_common_logic_main_menu_selection_track_row_selected_message so_called_common_logic_main_menu_selection_track_row_selected_message ;

#endif
