#ifndef _shy_win_platform_sound_loader_insider_injections_included
#define _shy_win_platform_sound_loader_insider_injections_included

#include "src/platform/sound/loader/winapi/insider/shy_insider_injections.h"
typedef so_called_platform_sound_loader_winapi_insider so_called_platform_sound_loader_insider ;

#endif
