#ifndef _shy_iphone_platform_render_vertex_buffer_id_type_injections_included
#define _shy_iphone_platform_render_vertex_buffer_id_type_injections_included

#include "platform/render/opengl/type/vertex_buffer_id/shy_vertex_buffer_id_injections.h"
typedef so_called_platform_render_opengl_vertex_buffer_id_type so_called_platform_render_vertex_buffer_id_type ;

#endif
