#ifndef _shy_common_engine_render_texture_loader_ready_reply_message_injections_included
#define _shy_common_engine_render_texture_loader_ready_reply_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_texture_loader_ready_reply.h"

typedef shy_common_engine_render_texture_loader_ready_reply_message so_called_common_engine_render_texture_loader_ready_reply_message ;

#endif
