#ifndef _shy_common_logic_main_menu_letters_meshes_render_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_render_reply_sender_injections_included

#include "../../message/render_reply/shy_render_reply_injections.h"

#include "./shy_render_reply.h"

typedef shy_common_logic_main_menu_letters_meshes_render_reply_sender so_called_common_logic_main_menu_letters_meshes_render_reply_sender ;

#endif
