#ifndef _shy_sender_common_logic_blanket_animation_disappear_finished_injections_included
#define _shy_sender_common_logic_blanket_animation_disappear_finished_injections_included

#include "../../message/disappear_finished/shy_disappear_finished_injections.h"

#include "./shy_disappear_finished.h"

typedef shy_sender_common_logic_blanket_animation_disappear_finished so_called_sender_common_logic_blanket_animation_disappear_finished ;

#endif
