#ifndef _shy_sender_common_engine_render_mesh_set_triangle_fan_index_value_included
#define _shy_sender_common_engine_render_mesh_set_triangle_fan_index_value_included

class shy_sender_common_engine_render_mesh_set_triangle_fan_index_value
{
public :
    static void send ( so_called_message_common_engine_render_mesh_set_triangle_fan_index_value ) ;
} ;

#endif
