#ifndef _shy_common_engine_render_enable_depth_test_sender_injections_included
#define _shy_common_engine_render_enable_depth_test_sender_injections_included

#include "../../message/enable_depth_test/shy_enable_depth_test_injections.h"

#include "./shy_enable_depth_test.h"

typedef shy_common_engine_render_enable_depth_test_sender so_called_common_engine_render_enable_depth_test_sender ;

#endif

