#ifndef _shy_common_logic_salutation_letters_text_storage_add_letter_message_injections_included
#define _shy_common_logic_salutation_letters_text_storage_add_letter_message_injections_included

#include "common/logic/text/type/letter_id/shy_letter_id_injections.h"

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_text_storage_add_letter_message so_called_common_logic_salutation_letters_text_storage_add_letter_message ;

#endif
