#ifndef _shy_common_logic_door_mesh_injections_included
#define _shy_common_logic_door_mesh_injections_included

#include "shy_mesh.h"

typedef shy_common_logic_door_mesh_scheduled so_called_common_logic_door_mesh ;

#endif
