#ifndef _shy_common_logic_main_menu_letters_animation_selection_weight_select_row_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_selection_weight_select_row_sender_injections_included

#include "common/logic/main_menu/letters/animation/message/selection_weight_select_row/shy_selection_weight_select_row_injections.h"

#include "./shy_selection_weight_select_row.h"

typedef shy_common_logic_main_menu_letters_animation_selection_weight_select_row_sender so_called_common_logic_main_menu_letters_animation_selection_weight_select_row_sender ;

#endif
