#ifndef _shy_sender_common_logic_main_menu_selection_mesh_create_injections_included
#define _shy_sender_common_logic_main_menu_selection_mesh_create_injections_included

#include "../../message/mesh_create/shy_mesh_create_injections.h"

#include "./shy_mesh_create.h"

typedef shy_sender_common_logic_main_menu_selection_mesh_create so_called_sender_common_logic_main_menu_selection_mesh_create ;

#endif
