#ifndef _shy_sender_common_logic_main_menu_letters_meshes_create_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_create_injections_included

#include "../../message/create/shy_create_injections.h"

#include "./shy_create.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_create so_called_sender_common_logic_main_menu_letters_meshes_create ;

#endif
