#ifndef _shy_common_logic_main_menu_letters_meshes_create_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_create_sender_injections_included

#include "common/logic/main_menu/letters/meshes/message/create/shy_create_injections.h"

#include "./shy_create.h"

typedef shy_common_logic_main_menu_letters_meshes_create_sender so_called_common_logic_main_menu_letters_meshes_create_sender ;

#endif
