#ifndef _shy_common_logic_salutation_letters_meshes_creator_create_checker_injections_included
#define _shy_common_logic_salutation_letters_meshes_creator_create_checker_injections_included

#include "src/common/logic/salutation/letters/meshes/creator/create/reply/message/shy_message_injections.h"
#include "src/common/logic/salutation/letters/meshes/creator/create/request/message/shy_message_injections.h"

#include "./shy_checker.h"

typedef shy_common_logic_salutation_letters_meshes_creator_create_checker so_called_common_logic_salutation_letters_meshes_creator_create_checker ;

#endif
