#ifndef _shy_common_logic_salutation_letters_meshes_generator_generate_sender_injections_included
#define _shy_common_logic_salutation_letters_meshes_generator_generate_sender_injections_included

#include "src/common/logic/salutation/letters/meshes/generator/generate/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_meshes_generator_generate_sender so_called_common_logic_salutation_letters_meshes_generator_generate_sender ;

#endif
