#include "./shy_creator_injections.h"

#include "../consts/shy_consts_injections.h"
#include "../sender/creation_finished/shy_creation_finished_injections.h"
#include "../sender/mesh_has_been_created/shy_mesh_has_been_created_injections.h"
#include "../../sender/cols_request/shy_cols_request_injections.h"
#include "../../sender/letter_request/shy_letter_request_injections.h"
#include "../../sender/rows_request/shy_rows_request_injections.h"
#include "../../../../text/consts/shy_consts_injections.h"
#include "../../../../text/letter/mesh/sender/create_request/shy_create_request_injections.h"
#include "../../../../text/stateless/shy_stateless_injections.h"
#include "../../../../../../injections/platform/conditions/shy_conditions.h"
#include "../../../../../../injections/platform/math/consts/shy_consts.h"
#include "../../../../../../injections/platform/math/shy_math.h"

#include "./shy_creator.hpp"
