#ifndef _shy_iphone_platform_vector_injections_included
#define _shy_iphone_platform_vector_injections_included

#include "src/platform/vector/float/shy_float_injections.h"
typedef so_called_platform_vector_float so_called_platform_vector ;

#endif
