#ifndef _shy_loadable_consts_reflection_logic_title_injections_included
#define _shy_loadable_consts_reflection_logic_title_injections_included

#include "./shy_title.h"

typedef shy_loadable_consts_reflection_logic_title so_called_loadable_consts_reflection_logic_title ;

#endif
