#ifndef _shy_loadable_fsm_content_transition_container_type_injections_included
#define _shy_loadable_fsm_content_transition_container_type_injections_included

#include "loadable/fsm/content/type/transition/shy_transition_injections.h"

#include "./shy_transition_container.h"

typedef shy_loadable_fsm_content_transition_container_type so_called_loadable_fsm_content_transition_container_type ;

#endif
