#ifndef _shy_type_loadable_fsm_content_transition_container_injections_included
#define _shy_type_loadable_fsm_content_transition_container_injections_included

#include "../transition/shy_transition_injections.h"

#include "./shy_transition_container.h"

typedef shy_type_loadable_fsm_content_transition_container so_called_type_loadable_fsm_content_transition_container ;

#endif
