// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_salutation_renderer_consts :: background_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_renderer_consts :: background_g = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_renderer_consts :: background_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;

// autogenerated file end
