#ifndef _shy_type_win_platform_sound_loader_stereo_resource_id_injections_included
#define _shy_type_win_platform_sound_loader_stereo_resource_id_injections_included

#include "platform/sound/loader/winapi/type/stereo_resource_id/shy_stereo_resource_id_injections.h"
typedef so_called_type_platform_sound_loader_winapi_stereo_resource_id so_called_type_platform_sound_loader_stereo_resource_id ;

#endif

