#ifndef _shy_win_platform_sound_loader_stereo_resource_id_type_injections_included
#define _shy_win_platform_sound_loader_stereo_resource_id_type_injections_included

#include "platform/sound/loader/winapi/type/stereo_resource_id/shy_stereo_resource_id_injections.h"
typedef so_called_platform_sound_loader_winapi_stereo_resource_id_type so_called_platform_sound_loader_stereo_resource_id_type ;

#endif

