#ifndef _shy_common_logic_perspective_planes_request_sender_injections_included
#define _shy_common_logic_perspective_planes_request_sender_injections_included

#include "src/common/logic/perspective/planes/request/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_perspective_planes_request_sender so_called_common_logic_perspective_planes_request_sender ;

#endif
