#ifndef _shy_type_macosx_platform_math_num_fract_injections_included
#define _shy_type_macosx_platform_math_num_fract_injections_included

#include "platform/math/int_float/type/num_fract/shy_num_fract_injections.h"
typedef so_called_type_platform_math_int_float_num_fract so_called_type_platform_math_num_fract ;

#endif
