#ifndef _shy_sender_common_logic_main_menu_letters_meshes_iterate_start_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_iterate_start_injections_included

#include "../../message/iterate_start/shy_iterate_start_injections.h"

#include "./shy_iterate_start.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_iterate_start so_called_sender_common_logic_main_menu_letters_meshes_iterate_start ;

#endif
