#ifndef _shy_common_logic_main_menu_letters_animation_selection_push_transform_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_selection_push_transform_reply_sender_injections_included

#include "common/logic/main_menu/letters/animation/message/selection_push_transform_reply/shy_selection_push_transform_reply_injections.h"

#include "./shy_selection_push_transform_reply.h"

typedef shy_common_logic_main_menu_letters_animation_selection_push_transform_reply_sender so_called_common_logic_main_menu_letters_animation_selection_push_transform_reply_sender ;

#endif
