#ifndef _shy_common_engine_render_mesh_create_reply_sender_injections_included
#define _shy_common_engine_render_mesh_create_reply_sender_injections_included

#include "../../message/mesh_create_reply/shy_mesh_create_reply_injections.h"

#include "./shy_mesh_create_reply.h"

typedef shy_common_engine_render_mesh_create_reply_sender so_called_common_engine_render_mesh_create_reply_sender ;

#endif

