#ifndef _shy_message_common_engine_render_frame_loss_request_injections_included
#define _shy_message_common_engine_render_frame_loss_request_injections_included

#include "shy_frame_loss_request.h"

typedef shy_message_common_engine_render_frame_loss_request so_called_message_common_engine_render_frame_loss_request ;

#endif
