#ifndef _shy_common_logic_camera_matrix_reply_sender_injections_included
#define _shy_common_logic_camera_matrix_reply_sender_injections_included

#include "common/logic/camera/message/matrix_reply/shy_matrix_reply_injections.h"

#include "./shy_matrix_reply.h"

typedef shy_common_logic_camera_matrix_reply_sender so_called_common_logic_camera_matrix_reply_sender ;

#endif
