#include "./shy_game_injections.h"

#include "../camera/sender/matrix_request/shy_matrix_request_injections.h"
#include "../camera/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../camera/sender/update/shy_update_injections.h"
#include "../core/sender/near_plane_distance_request/shy_near_plane_distance_request_injections.h"
#include "../entities/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../entities/sender/update/shy_update_injections.h"
#include "../image/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../image/sender/update/shy_update_injections.h"
#include "../land/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../land/sender/update/shy_update_injections.h"
#include "../sound/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../sound/sender/update/shy_update_injections.h"
#include "../text/sender/update/shy_update_injections.h"
#include "../touch/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../touch/sender/update/shy_update_injections.h"

#include "../../../injections/platform/conditions/shy_conditions.h"
#include "../../../injections/platform/math/consts/shy_consts.h"
#include "../../../injections/platform/math/shy_math.h"

#include "./shy_game.hpp"
