#include "./shy_game_injections.h"

#include "../camera/sender/matrix_request/shy_matrix_request_injections.h"
#include "../camera/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../camera/sender/update/shy_update_injections.h"
#include "../core/sender/near_plane_distance_request/shy_near_plane_distance_request_injections.h"
#include "../core/sender/use_ortho_projection_request/shy_use_ortho_projection_request_injections.h"
#include "../core/sender/use_perspective_projection_request/shy_use_perspective_projection_request_injections.h"
#include "../entities/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../entities/sender/render_request/shy_render_request_injections.h"
#include "../entities/sender/update/shy_update_injections.h"
#include "../fidget/sender/render_request/shy_render_request_injections.h"
#include "../image/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../image/sender/render_request/shy_render_request_injections.h"
#include "../image/sender/update/shy_update_injections.h"
#include "../land/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../land/sender/render_request/shy_render_request_injections.h"
#include "../land/sender/update/shy_update_injections.h"
#include "../sound/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../sound/sender/update/shy_update_injections.h"
#include "../text/sender/render_request/shy_render_request_injections.h"
#include "../text/sender/update/shy_update_injections.h"
#include "../touch/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../touch/sender/render/shy_render_injections.h"
#include "../touch/sender/update/shy_update_injections.h"

#include "../../engine/render/sender/clear_screen/shy_clear_screen_injections.h"
#include "../../engine/render/sender/disable_depth_test/shy_disable_depth_test_injections.h"
#include "../../engine/render/sender/enable_depth_test/shy_enable_depth_test_injections.h"
#include "../../engine/render/sender/fog_disable/shy_fog_disable_injections.h"
#include "../../engine/render/sender/fog_linear/shy_fog_linear_injections.h"
#include "../../engine/render/sender/matrix_load/shy_matrix_load_injections.h"

#include "../../../injections/platform/conditions/shy_conditions.h"
#include "../../../injections/platform/math/consts/shy_consts.h"
#include "../../../injections/platform/math/shy_math.h"

#include "./shy_game.hpp"
