/usr/local/bin/python -B shy_normalize_paths.py src/common|sh
/usr/local/bin/python -B shy_normalize_paths.py src/facade|sh
/usr/local/bin/python -B shy_normalize_paths.py src/injections|sh
/usr/local/bin/python -B shy_normalize_paths.py src/lib|sh
/usr/local/bin/python -B shy_normalize_paths.py src/loadable|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/iphone/lib|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/iphone/platform|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/macosx/lib|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/macosx/platform|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/win/lib|sh
/usr/local/bin/python -B shy_normalize_paths.py src/main/win/platform|sh
/usr/local/bin/python -B shy_normalize_paths.py src/platform|sh
/usr/local/bin/python -B shy_normalize_paths.py src/trace|sh

/usr/local/bin/python -B shy_normalize_includes.py src/common
/usr/local/bin/python -B shy_normalize_includes.py src/facade
/usr/local/bin/python -B shy_normalize_includes.py src/injections
/usr/local/bin/python -B shy_normalize_includes.py src/lib
/usr/local/bin/python -B shy_normalize_includes.py src/loadable
/usr/local/bin/python -B shy_normalize_includes.py src/main/iphone/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/iphone/platform
/usr/local/bin/python -B shy_normalize_includes.py src/main/macosx/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/macosx/platform
/usr/local/bin/python -B shy_normalize_includes.py src/main/win/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/win/platform
/usr/local/bin/python -B shy_normalize_includes.py src/platform
/usr/local/bin/python -B shy_normalize_includes.py src/trace
