/usr/local/bin/python -B shy_normalize_includes.py src/common
/usr/local/bin/python -B shy_normalize_includes.py src/facade
/usr/local/bin/python -B shy_normalize_includes.py src/injections
/usr/local/bin/python -B shy_normalize_includes.py src/lib
/usr/local/bin/python -B shy_normalize_includes.py src/loadable
/usr/local/bin/python -B shy_normalize_includes.py src/main/iphone/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/iphone/platform
/usr/local/bin/python -B shy_normalize_includes.py src/main/macosx/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/macosx/platform
/usr/local/bin/python -B shy_normalize_includes.py src/main/win/lib
/usr/local/bin/python -B shy_normalize_includes.py src/main/win/platform
/usr/local/bin/python -B shy_normalize_includes.py src/platform
/usr/local/bin/python -B shy_normalize_includes.py src/trace
