#ifndef _shy_common_logic_main_menu_selection_track_void_selected_sender_injections_included
#define _shy_common_logic_main_menu_selection_track_void_selected_sender_injections_included

#include "../../message/track_void_selected/shy_track_void_selected_injections.h"

#include "./shy_track_void_selected.h"

typedef shy_common_logic_main_menu_selection_track_void_selected_sender so_called_common_logic_main_menu_selection_track_void_selected_sender ;

#endif
