#ifndef _shy_common_logic_door_animation_appear_transform_reply_sender_injections_included
#define _shy_common_logic_door_animation_appear_transform_reply_sender_injections_included

#include "../../message/appear_transform_reply/shy_appear_transform_reply_injections.h"

#include "./shy_appear_transform_reply.h"

typedef shy_common_logic_door_animation_appear_transform_reply_sender so_called_common_logic_door_animation_appear_transform_reply_sender ;

#endif
