const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: animation_origin_x ;
const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: animation_origin_y ;
const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: animation_origin_z ;
const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: appear_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: appear_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_door_animation_consts :: appear_time_from_begin_to_end ;

void shy_common_logic_door_animation_consts :: binding ( )
{
}
