#ifndef _shy_common_logic_main_menu_selection_track_request_message_injections_included
#define _shy_common_logic_main_menu_selection_track_request_message_injections_included

#include "./shy_track_request.h"

typedef shy_common_logic_main_menu_selection_track_request_message so_called_common_logic_main_menu_selection_track_request_message ;

#endif
