const so_called_type_platform_math_num_fract shy_common_logic_amusement_consts :: renderer_clear_color_b ;
const so_called_type_platform_math_num_fract shy_common_logic_amusement_consts :: renderer_clear_color_g ;
const so_called_type_platform_math_num_fract shy_common_logic_amusement_consts :: renderer_clear_color_r ;

