#include "./shy_creator_injections.h"

#include "./create/reply/sender/shy_sender_injections.h"
#include "../consts/shy_consts_injections.h"
#include "../storage/add_mesh/sender/shy_sender_injections.h"
#include "../../text/storage/letter/checker/shy_checker_injections.h"
#include "../../text/storage/letter/request/sender/shy_sender_injections.h"
#include "../../../../text/letter/mesh/create/checker/shy_checker_injections.h"
#include "../../../../text/letter/mesh/sender/create_request/shy_create_request_injections.h"
#include "../../../../../engine/taker/helper/shy_helper_injections.h"
#include "../../../../../../injections/platform/conditions/shy_conditions.h"
#include "../../../../../../injections/platform/math/consts/shy_consts.h"
#include "../../../../../../injections/platform/math/shy_math.h"

#include "./shy_creator.hpp"
