#ifndef _shy_common_logic_text_letter_big_tex_coords_request_message_injections_included
#define _shy_common_logic_text_letter_big_tex_coords_request_message_injections_included

#include "src/common/logic/text/letter/id/type/shy_type_injections.h"

#include "./shy_message.h"

typedef shy_common_logic_text_letter_big_tex_coords_request_message so_called_common_logic_text_letter_big_tex_coords_request_message ;

#endif
