#ifndef _shy_common_engine_render_mesh_set_vertex_position_sender_injections_included
#define _shy_common_engine_render_mesh_set_vertex_position_sender_injections_included

#include "common/engine/render/message/mesh_set_vertex_position/shy_mesh_set_vertex_position_injections.h"

#include "./shy_mesh_set_vertex_position.h"

typedef shy_common_engine_render_mesh_set_vertex_position_sender so_called_common_engine_render_mesh_set_vertex_position_sender ;

#endif

