#ifndef _shy_loadable_fsm_content_action_command_container_type_injections_included
#define _shy_loadable_fsm_content_action_command_container_type_injections_included

#include "loadable/fsm/content/type/action_command/shy_action_command_injections.h"
#include "injections/lib/std/vector/shy_vector.h"

#include "./shy_action_command_container.h"

typedef shy_loadable_fsm_content_action_command_container_type so_called_loadable_fsm_content_action_command_container_type ;

#endif
