#ifndef _shy_common_logic_main_menu_letters_meshes_creation_finished_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_creation_finished_sender_injections_included

#include "common/logic/main_menu/letters/meshes/message/creation_finished/shy_creation_finished_injections.h"

#include "./shy_creation_finished.h"

typedef shy_common_logic_main_menu_letters_meshes_creation_finished_sender so_called_common_logic_main_menu_letters_meshes_creation_finished_sender ;

#endif
