#ifndef _shy_message_common_logic_core_use_ortho_projection_request_injections_included
#define _shy_message_common_logic_core_use_ortho_projection_request_injections_included

#include "./shy_use_ortho_projection_request.h"

typedef shy_message_common_logic_core_use_ortho_projection_request so_called_message_common_logic_core_use_ortho_projection_request ;

#endif
