#ifndef _shy_macosx_platform_matrix_insider_injections_included
#define _shy_macosx_platform_matrix_insider_injections_included

#include "src/platform/matrix/float/insider/shy_insider_injections.h"
typedef so_called_platform_matrix_float_insider so_called_platform_matrix_insider ;

#endif

