#ifndef _shy_message_common_logic_main_menu_letters_next_row_injections_included
#define _shy_message_common_logic_main_menu_letters_next_row_injections_included

#include "./shy_next_row.h"

typedef shy_message_common_logic_main_menu_letters_next_row so_called_message_common_logic_main_menu_letters_next_row ;

#endif
