#ifndef _shy_common_logic_main_menu_launch_permit_message_injections_included
#define _shy_common_logic_main_menu_launch_permit_message_injections_included

#include "./shy_launch_permit.h"

typedef shy_common_logic_main_menu_launch_permit_message so_called_common_logic_main_menu_launch_permit_message ;

#endif
