// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: appear_scale_begin = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: appear_scale_end = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: appear_time = so_called_platform_math :: init_num_fract ( 5 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: appear_time_shift_per_letter = so_called_platform_math :: init_num_fract ( 1 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: disappear_scale_begin = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: disappear_scale_cut_off = so_called_platform_math :: init_num_fract ( 1 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: disappear_scale_end = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: disappear_time = so_called_platform_math :: init_num_fract ( 5 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: disappear_time_shift_per_letter = so_called_platform_math :: init_num_fract ( 1 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: layout_border_height = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: layout_border_width = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_animation_consts :: layout_step = so_called_platform_math :: init_num_fract ( 1 , 10 ) ;

// autogenerated file end
