#ifndef _shy_type_loadable_fsm_content_condition_command_container_injections_included
#define _shy_type_loadable_fsm_content_condition_command_container_injections_included

#include "loadable/fsm/content/type/condition_command/shy_condition_command_injections.h"

#include "./shy_condition_command_container.h"

typedef shy_type_loadable_fsm_content_condition_command_container so_called_type_loadable_fsm_content_condition_command_container ;

#endif
