#ifndef _shy_loadable_fsm_content_condition_command_container_type_injections_included
#define _shy_loadable_fsm_content_condition_command_container_type_injections_included

#include "loadable/fsm/content/type/condition_command/shy_condition_command_injections.h"

#include "./shy_condition_command_container.h"

typedef shy_loadable_fsm_content_condition_command_container_type so_called_loadable_fsm_content_condition_command_container_type ;

#endif
