#ifndef _shy_common_logic_main_menu_selection_track_reply_sender_injections_included
#define _shy_common_logic_main_menu_selection_track_reply_sender_injections_included

#include "../../message/track_reply/shy_track_reply_injections.h"

#include "./shy_track_reply.h"

typedef shy_common_logic_main_menu_selection_track_reply_sender so_called_common_logic_main_menu_selection_track_reply_sender ;

#endif
