#ifndef _shy_iphone_platform_static_array_insider_injections_included
#define _shy_iphone_platform_static_array_insider_injections_included

#include "src/platform/static/array/insider/shy_insider_injections.h"

#endif
