#ifndef _shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh_injections_included
#define _shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh_injections_included

#include "common/logic/salutation/letters/meshes/storage/add_mesh/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh so_called_sender_common_logic_salutation_letters_meshes_storage_add_mesh ;

#endif
