#ifndef _shy_common_engine_render_texture_load_from_resource_sender_injections_included
#define _shy_common_engine_render_texture_load_from_resource_sender_injections_included

#include "src/common/engine/render/texture/load/from/resource/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_render_texture_load_from_resource_sender so_called_common_engine_render_texture_load_from_resource_sender ;

#endif

