#ifndef _shy_sender_common_logic_text_letter_mesh_create_reply_injections_included
#define _shy_sender_common_logic_text_letter_mesh_create_reply_injections_included

#include "../../message/create_reply/shy_create_reply_injections.h"
#include "./shy_create_reply.h"

typedef shy_sender_common_logic_text_letter_mesh_create_reply so_called_sender_common_logic_text_letter_mesh_create_reply ;

#endif
