#ifndef _shy_common_logic_text_letter_mesh_create_reply_sender_injections_included
#define _shy_common_logic_text_letter_mesh_create_reply_sender_injections_included

#include "../../message/create_reply/shy_create_reply_injections.h"
#include "./shy_create_reply.h"

typedef shy_common_logic_text_letter_mesh_create_reply_sender so_called_common_logic_text_letter_mesh_create_reply_sender ;

#endif
