#ifndef _shy_sender_common_logic_perspective_planes_request_injections_included
#define _shy_sender_common_logic_perspective_planes_request_injections_included

#include "../../message/planes_request/shy_planes_request_injections.h"

#include "./shy_planes_request.h"

typedef shy_sender_common_logic_perspective_planes_request so_called_sender_common_logic_perspective_planes_request ;

#endif
