#ifndef _shy_common_logic_main_menu_letters_animation_idle_transform_request_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_idle_transform_request_sender_injections_included

#include "src/common/logic/main/menu/letters/animation/idle/transform/request/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_main_menu_letters_animation_idle_transform_request_sender so_called_common_logic_main_menu_letters_animation_idle_transform_request_sender ;

#endif
