#ifndef _shy_type_loadable_fsm_content_system_binding_injections_included
#define _shy_type_loadable_fsm_content_system_binding_injections_included

#include "./shy_system_binding.h"

typedef shy_type_loadable_fsm_content_system_binding so_called_type_loadable_fsm_content_system_binding ;

#endif
