#ifndef _shy_loadable_fsm_content_machine_container_type_injections_included
#define _shy_loadable_fsm_content_machine_container_type_injections_included

#include "loadable/fsm/content/type/machine/shy_machine_injections.h"

#include "./shy_machine_container.h"

typedef shy_loadable_fsm_content_machine_container_type so_called_loadable_fsm_content_machine_container_type ;

#endif
