#ifndef _shy_type_loadable_fsm_content_machine_container_injections_included
#define _shy_type_loadable_fsm_content_machine_container_injections_included

#include "../machine/shy_machine_injections.h"

#include "./shy_machine_container.h"

typedef shy_type_loadable_fsm_content_machine_container so_called_type_loadable_fsm_content_machine_container ;

#endif
