#ifndef _shy_sender_common_logic_main_menu_letters_layout_row_rect_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_layout_row_rect_reply_injections_included

#include "../../message/row_rect_reply/shy_row_rect_reply_injections.h"

#include "./shy_row_rect_reply.h"

typedef shy_sender_common_logic_main_menu_letters_layout_row_rect_reply so_called_sender_common_logic_main_menu_letters_layout_row_rect_reply ;

#endif
