// autogenerated file begin

#ifndef _shy_common_autogenerated_logic_application_fsm_behaviour_static_injections_included
#define _shy_common_autogenerated_logic_application_fsm_behaviour_static_injections_included

#include "injections/platform/pointer/type/data/shy_data.h"

#include "./shy_logic_application_fsm_behaviour_static.h"

typedef shy_common_logic_application_fsm_behaviour_static so_called_common_logic_application_fsm_behaviour_static ;

#endif

// autogenerated file end
