// autogenerated file begin

#include "common/engine/fsm/stateless/shy_stateless_injections.h"

#include "injections/platform/math/consts/shy_consts.h"

#include "./shy_logic_application_fsm_behaviour_static.hpp"

// autogenerated file end
