#ifndef _shy_macosx_lib_openal_injections_included
#define _shy_macosx_lib_openal_injections_included

#include <OpenAL/al.h>
#include <OpenAL/alc.h>
#include <OpenAL/MacOSX_OALExtensions.h>

#define so_called_lib_openal_alcGetProcAddress alcGetProcAddress
#define so_called_lib_openal_alGenBuffers alGenBuffers
#define so_called_lib_openal_alGenSources alGenSources
#define so_called_lib_openal_alListenerfv alListenerfv
#define so_called_lib_openal_alSourcef alSourcef
#define so_called_lib_openal_alSourcefv alSourcefv
#define so_called_lib_openal_alSourcei alSourcei
#define so_called_lib_openal_alSourcePlay alSourcePlay
#define so_called_lib_openal_alSourceStop alSourceStop
#define so_called_lib_openal_AL_BUFFER AL_BUFFER
#define so_called_lib_openal_AL_FALSE AL_FALSE
#define so_called_lib_openal_AL_FORMAT_MONO8 AL_FORMAT_MONO8
#define so_called_lib_openal_AL_FORMAT_STEREO16 AL_FORMAT_STEREO16
#define so_called_lib_openal_AL_GAIN AL_GAIN
#define so_called_lib_openal_AL_LOOPING AL_LOOPING
#define so_called_lib_openal_AL_ORIENTATION AL_ORIENTATION
#define so_called_lib_openal_AL_PITCH AL_PITCH
#define so_called_lib_openal_AL_POSITION AL_POSITION
#define so_called_lib_openal_AL_TRUE AL_TRUE
#define so_called_lib_openal_AL_VELOCITY AL_VELOCITY

typedef alBufferDataStaticProcPtr so_called_lib_openal_alBufferDataStaticProcPtr ;
typedef ALfloat so_called_lib_openal_ALfloat ;
typedef ALubyte so_called_lib_openal_ALubyte ;
typedef ALuint so_called_lib_openal_ALuint ;
typedef ALushort so_called_lib_openal_ALushort ;
typedef ALvoid so_called_lib_openal_ALvoid ;
typedef ALCchar so_called_lib_openal_ALCchar ;

#endif
