#ifndef _shy_common_logic_main_menu_letters_animation_selection_weight_injections_included
#define _shy_common_logic_main_menu_letters_animation_selection_weight_injections_included

#include "common/logic/main_menu/letters/animation/message/selection_weight_request/shy_selection_weight_request_injections.h"
#include "common/logic/main_menu/letters/animation/message/selection_weight_select_row/shy_selection_weight_select_row_injections.h"
#include "common/logic/main_menu/letters/animation/message/selection_weight_unselect_row/shy_selection_weight_unselect_row_injections.h"
#include "common/logic/main_menu/message/update/shy_update_injections.h"
#include "common/message/init/shy_init_injections.h"
#include "injections/platform/scheduler/shy_scheduler.h"

#include "./shy_selection_weight.h"

typedef shy_common_logic_main_menu_letters_animation_selection_weight_scheduled so_called_common_logic_main_menu_letters_animation_selection_weight ;

#endif
