#include "./shy_renderer_injections.h"

#include "src/common/engine/render/blend/src/alpha/dst/one/minus/alpha/sender/shy_sender_injections.h"
#include "src/common/engine/render/clear/screen/sender/shy_sender_injections.h"
#include "src/common/engine/render/disable/depth/test/sender/shy_sender_injections.h"
#include "src/common/engine/render/fog/disable/sender/shy_sender_injections.h"
#include "src/common/engine/render/matrix/load/sender/shy_sender_injections.h"
#include "src/common/engine/render/projection/ortho/sender/shy_sender_injections.h"
#include "src/common/engine/taker/helper/shy_helper_injections.h"
#include "src/common/logic/ortho/planes/checker/shy_checker_injections.h"
#include "src/common/logic/ortho/planes/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/animation/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/animation/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/renderer/render/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/renderer/render/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/renderer/consts/shy_consts_injections.h"
#include "src/common/logic/text/use/text/texture/request/sender/shy_sender_injections.h"
#include "src/common/logic/text/use/text/texture/checker/shy_checker_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"

#include "./shy_renderer.hpp"
