#ifndef _shy_sender_common_logic_main_menu_letters_boundaries_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_boundaries_reply_injections_included

#include "../../message/boundaries_reply/shy_boundaries_reply_injections.h"

#include "./shy_boundaries_reply.h"

typedef shy_sender_common_logic_main_menu_letters_boundaries_reply so_called_sender_common_logic_main_menu_letters_boundaries_reply ;

#endif
