#ifndef _shy_sender_common_logic_main_menu_letters_meshes_count_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_count_request_injections_included

#include "../../message/count_request/shy_count_request_injections.h"

#include "./shy_count_request.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_count_request so_called_sender_common_logic_main_menu_letters_meshes_count_request ;

#endif
