#ifndef _shy_message_common_engine_render_done_injections_included
#define _shy_message_common_engine_render_done_injections_included

#include "./shy_done.h"

typedef shy_message_common_engine_render_done so_called_message_common_engine_render_done ;

#endif
