#ifndef _shy_sender_common_engine_rasterizer_draw_ellipse_in_rect_injections_included
#define _shy_sender_common_engine_rasterizer_draw_ellipse_in_rect_injections_included

#include "../../message/draw_ellipse_in_rect/shy_draw_ellipse_in_rect_injections.h"

#include "./shy_draw_ellipse_in_rect.h"

typedef shy_sender_common_engine_rasterizer_draw_ellipse_in_rect so_called_sender_common_engine_rasterizer_draw_ellipse_in_rect ;

#endif
