#pragma once

enum physres_e
{
    PHYSRES_OK = 0,
    PHYSRES_CANNOT_INIT,
    PHYSRES_OUT_OF_RB,
    PHYSRES_OUT_OF_CS,
    PHYSRES_OUT_OF_VEH,
    PHYSRES_OUT_OF_WLD,
    PHYSRES_INVALID_RB,
    PHYSRES_INVALID_CS,
    PHYSRES_INVALID_VEH,
    PHYSRES_INVALID_VEH_WHEEL,
    PHYSRES_INVALID_WLD,
    PHYSRES_CS_HAS_REFS,
    PHYSRES_WLD_HAS_REFS,
    PHYSRES_INTERNAL
};
