#ifndef YPHYSRES_H
#define YPHYSRES_H

enum yphysres_e {
    YPHYSRES_OK,
    YPHYSRES_CANNOT_INIT,
    YPHYSRES_OUT_OF_RB,
    YPHYSRES_OUT_OF_CS,
    YPHYSRES_OUT_OF_VEH,
    YPHYSRES_OUT_OF_WLD,
    YPHYSRES_INVALID_RB,
    YPHYSRES_INVALID_CS,
    YPHYSRES_INVALID_VEH,
    YPHYSRES_INVALID_VEH_WHEEL,
    YPHYSRES_INVALID_WLD,
    YPHYSRES_CS_HAS_REFS,
    YPHYSRES_WLD_HAS_REFS,
    YPHYSRES_INTERNAL
};

#endif /* YPHYSRES_H */

