#ifndef _shy_sender_common_logic_main_menu_letters_animation_unselection_weight_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_animation_unselection_weight_reply_injections_included

#include "../../message/unselection_weight_reply/shy_unselection_weight_reply_injections.h"

#include "./shy_unselection_weight_reply.h"

typedef shy_sender_common_logic_main_menu_letters_animation_unselection_weight_reply so_called_sender_common_logic_main_menu_letters_animation_unselection_weight_reply ;

#endif
