#ifndef _shy_type_macosx_platform_sound_source_id_injections_included
#define _shy_type_macosx_platform_sound_source_id_injections_included

#include "platform/sound/openal/type/source_id/shy_source_id_injections.h"
typedef so_called_type_platform_sound_openal_source_id so_called_type_platform_sound_source_id ;

#endif

