#ifndef _shy_sender_common_logic_salutation_letters_meshes_creator_create_reply_injections_included
#define _shy_sender_common_logic_salutation_letters_meshes_creator_create_reply_injections_included

#include "common/logic/salutation/letters/meshes/creator/create/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_meshes_creator_create_reply so_called_sender_common_logic_salutation_letters_meshes_creator_create_reply ;

#endif
