#ifndef _shy_sender_common_logic_main_menu_selection_animation_push_weight_reply_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_push_weight_reply_injections_included

#include "../../message/push_weight_reply/shy_push_weight_reply_injections.h"

#include "./shy_push_weight_reply.h"

typedef shy_sender_common_logic_main_menu_selection_animation_push_weight_reply so_called_sender_common_logic_main_menu_selection_animation_push_weight_reply ;

#endif
