#ifndef _shy_message_common_logic_main_menu_creation_permit_injections_included
#define _shy_message_common_logic_main_menu_creation_permit_injections_included

#include "./shy_creation_permit.h"

typedef shy_message_common_logic_main_menu_creation_permit so_called_message_common_logic_main_menu_creation_permit ;

#endif
