#ifndef _shy_iphone_platform_pointer_profile_injections_included
#define _shy_iphone_platform_pointer_profile_injections_included

#include "src/profile/platform/pointer/shy_pointer_injections.h"

#endif
