class shy_common_logic_application_fsm_actions
{
public :
    static void logic_amusement_creation_permit ( ) ;
    static void logic_amusement_launch_permit ( ) ;
    static void logic_amusement_render ( ) ;
    static void logic_amusement_update ( ) ;
    static void logic_game_launch_permit ( ) ;
    static void logic_game_render ( ) ;
    static void logic_game_update ( ) ;
    static void logic_main_menu_creation_permit ( ) ;
    static void logic_main_menu_launch_permit ( ) ;
    static void logic_main_menu_render ( ) ;
    static void logic_main_menu_update ( ) ;
    static void logic_salutation_animation_zoom_play ( ) ;
    static void logic_salutation_animation_zoom_update ( ) ;
    static void logic_salutation_letters_animation_appear_play ( ) ;
    static void logic_salutation_letters_animation_appear_update ( ) ;
    static void logic_salutation_letters_animation_disappear_play ( ) ;
    static void logic_salutation_letters_animation_disappear_update ( ) ;
    static void logic_salutation_letters_animation_roll_in_play ( ) ;
    static void logic_salutation_letters_animation_roll_in_update ( ) ;
    static void logic_salutation_letters_animation_roll_out_play ( ) ;
    static void logic_salutation_letters_animation_roll_out_update ( ) ;
    static void logic_salutation_letters_meshes_cleaner_clean ( ) ;
    static void logic_salutation_letters_meshes_cleaner_update ( ) ;
    static void logic_salutation_letters_meshes_generator_generate ( ) ;
    static void logic_salutation_letters_meshes_generator_update ( ) ;
    static void logic_salutation_letters_text_cleaner_clean ( ) ;
    static void logic_salutation_letters_text_generator_generate ( ) ;
    static void logic_salutation_renderer_render ( ) ;
    static void logic_salutation_timer_appear_run ( ) ;
    static void logic_salutation_timer_appear_update ( ) ;
    static void logic_salutation_timer_disappear_run ( ) ;
    static void logic_salutation_timer_disappear_update ( ) ;
    static void logic_text_prepare_permit ( ) ;
    static void logic_text_update ( ) ;
    static void logic_title_launch_permit ( ) ;
    static void logic_title_render ( ) ;
    static void logic_title_update ( ) ;
    static void logic_vacuum_render ( ) ;
    static void logic_vacuum_update ( ) ;
} ;
