#ifndef _shy_common_logic_application_fsm_actions_injections_included
#define _shy_common_logic_application_fsm_actions_injections_included

#include "./shy_actions.h"

typedef shy_common_logic_application_fsm_actions so_called_common_logic_application_fsm_actions ;

#endif
