#include "./shy_actions_injections.h"

#include "../../../amusement/sender/creation_permit/shy_creation_permit_injections.h"
#include "../../../amusement/sender/launch_permit/shy_launch_permit_injections.h"
#include "../../../amusement/sender/render/shy_render_injections.h"
#include "../../../amusement/sender/update/shy_update_injections.h"
#include "../../../game/sender/launch_permit/shy_launch_permit_injections.h"
#include "../../../game/sender/render/shy_render_injections.h"
#include "../../../game/sender/update/shy_update_injections.h"
#include "../../../main_menu/sender/creation_permit/shy_creation_permit_injections.h"
#include "../../../main_menu/sender/launch_permit/shy_launch_permit_injections.h"
#include "../../../main_menu/sender/render/shy_render_injections.h"
#include "../../../main_menu/sender/update/shy_update_injections.h"
#include "../../../salutation/letters/meshes/generator/sender/generate/shy_generate_injections.h"
#include "../../../salutation/letters/meshes/generator/sender/update/shy_update_injections.h"
#include "../../../salutation/letters/text/generator/sender/generate/shy_generate_injections.h"
#include "../../../salutation/sender/creation_permit/shy_creation_permit_injections.h"
#include "../../../salutation/sender/launch_permit/shy_launch_permit_injections.h"
#include "../../../salutation/sender/render/shy_render_injections.h"
#include "../../../salutation/sender/update/shy_update_injections.h"
#include "../../../text/sender/prepare_permit/shy_prepare_permit_injections.h"
#include "../../../text/sender/update/shy_update_injections.h"
#include "../../../title/sender/launch_permit/shy_launch_permit_injections.h"
#include "../../../title/sender/render/shy_render_injections.h"
#include "../../../title/sender/update/shy_update_injections.h"

#include "./shy_actions.hpp"
