#ifndef _shy_common_logic_blanket_creation_finished_sender_injections_included
#define _shy_common_logic_blanket_creation_finished_sender_injections_included

#include "../../message/creation_finished/shy_creation_finished_injections.h"

#include "./shy_creation_finished.h"

typedef shy_common_logic_blanket_creation_finished_sender so_called_common_logic_blanket_creation_finished_sender ;

#endif
