#ifndef _shy_win_platform_render_texture_loader_injections_included
#define _shy_win_platform_render_texture_loader_injections_included

#include "src/platform/render/texture/loader/winapi/shy_winapi_injections.h"
typedef so_called_platform_render_texture_loader_winapi so_called_platform_render_texture_loader ;

#endif

