#ifndef _shy_loadable_consts_reflection_logic_salutation_letters_meshes_injections_included
#define _shy_loadable_consts_reflection_logic_salutation_letters_meshes_injections_included

#include "./shy_meshes.h"

typedef shy_loadable_consts_reflection_logic_salutation_letters_meshes so_called_loadable_consts_reflection_logic_salutation_letters_meshes ;

#endif
