#ifndef _shy_sender_common_logic_main_menu_letters_animation_selection_weight_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_animation_selection_weight_reply_injections_included

#include "../../message/selection_weight_reply/shy_selection_weight_reply_injections.h"

#include "./shy_selection_weight_reply.h"

typedef shy_sender_common_logic_main_menu_letters_animation_selection_weight_reply so_called_sender_common_logic_main_menu_letters_animation_selection_weight_reply ;

#endif
