#ifndef _shy_message_common_logic_main_menu_selection_mesh_render_reply_injections_included
#define _shy_message_common_logic_main_menu_selection_mesh_render_reply_injections_included

#include "./shy_mesh_render_reply.h"

typedef shy_message_common_logic_main_menu_selection_mesh_render_reply so_called_message_common_logic_main_menu_selection_mesh_render_reply ;

#endif
