#ifndef _shy_common_engine_render_mesh_set_vertex_color_sender_injections_included
#define _shy_common_engine_render_mesh_set_vertex_color_sender_injections_included

#include "common/engine/render/message/mesh_set_vertex_color/shy_mesh_set_vertex_color_injections.h"

#include "./shy_mesh_set_vertex_color.h"

typedef shy_common_engine_render_mesh_set_vertex_color_sender so_called_common_engine_render_mesh_set_vertex_color_sender ;

#endif

