#ifndef _shy_iphone_platform_pointer_insider_injections_included
#define _shy_iphone_platform_pointer_insider_injections_included

#include "src/platform/pointer/insider/shy_insider_injections.h"

#endif
