#ifndef _shy_platform_render_opengl_index_buffer_mapped_data_type_injections_included
#define _shy_platform_render_opengl_index_buffer_mapped_data_type_injections_included

#include "./shy_index_buffer_mapped_data.h"

typedef shy_platform_render_opengl_index_buffer_mapped_data_type so_called_platform_render_opengl_index_buffer_mapped_data_type ;

#endif


