#ifndef _shy_common_logic_main_menu_letters_meshes_destroy_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_destroy_reply_sender_injections_included

#include "../../message/destroy_reply/shy_destroy_reply_injections.h"

#include "./shy_destroy_reply.h"

typedef shy_common_logic_main_menu_letters_meshes_destroy_reply_sender so_called_common_logic_main_menu_letters_meshes_destroy_reply_sender ;

#endif
