#ifndef _shy_loadable_fsm_reflection_logic_application_injections_included
#define _shy_loadable_fsm_reflection_logic_application_injections_included

#include "./shy_application.h"

typedef shy_loadable_fsm_reflection_logic_application so_called_loadable_fsm_reflection_logic_application ;

#endif
