#ifndef _shy_common_logic_core_near_plane_distance_reply_sender_injections_included
#define _shy_common_logic_core_near_plane_distance_reply_sender_injections_included

#include "src/common/logic/core/near/plane/distance/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_core_near_plane_distance_reply_sender so_called_common_logic_core_near_plane_distance_reply_sender ;

#endif
