#ifndef _shy_type_win_platform_render_vertex_buffer_id_injections_included
#define _shy_type_win_platform_render_vertex_buffer_id_injections_included

#include "platform/render/directx/type/vertex_buffer_id/shy_vertex_buffer_id_injections.h"
typedef so_called_type_platform_render_directx_vertex_buffer_id so_called_type_platform_render_vertex_buffer_id ;

#endif
