#ifndef _shy_common_video_mode_changed_sender_injections_included
#define _shy_common_video_mode_changed_sender_injections_included

#include "common/message/video_mode_changed/shy_video_mode_changed_injections.h"

#include "./shy_video_mode_changed.h"

typedef shy_common_video_mode_changed_sender so_called_common_video_mode_changed_sender ;

#endif
