#ifndef _shy_message_common_logic_application_render_injections_included
#define _shy_message_common_logic_application_render_injections_included

#include "./shy_render.h"

typedef shy_message_common_logic_application_render so_called_message_common_logic_application_render ;

#endif
