#ifndef _shy_win_platform_render_vertex_buffer_mapped_data_type_injections_included
#define _shy_win_platform_render_vertex_buffer_mapped_data_type_injections_included

#include "platform/render/directx/type/vertex_buffer_mapped_data/shy_vertex_buffer_mapped_data_injections.h"
typedef so_called_platform_render_directx_vertex_buffer_mapped_data_type so_called_platform_render_vertex_buffer_mapped_data_type ;

#endif
