#ifndef _shy_message_common_logic_camera_matrix_request_injections_included
#define _shy_message_common_logic_camera_matrix_request_injections_included

#include "./shy_matrix_request.h"

typedef shy_message_common_logic_camera_matrix_request so_called_message_common_logic_camera_matrix_request ;

#endif
