#ifndef _shy_common_logic_main_menu_letters_letter_add_message_injections_included
#define _shy_common_logic_main_menu_letters_letter_add_message_injections_included

#include "src/common/logic/text/letter/id/type/shy_type_injections.h"

#include "./shy_message.h"

typedef shy_common_logic_main_menu_letters_letter_add_message so_called_common_logic_main_menu_letters_letter_add_message ;

#endif
