#ifndef _shy_common_engine_render_mesh_create_request_message_injections_included
#define _shy_common_engine_render_mesh_create_request_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_mesh_create_request.h"

typedef shy_common_engine_render_mesh_create_request_message so_called_common_engine_render_mesh_create_request_message ;

#endif
