#ifndef _shy_sender_common_logic_main_menu_selection_mesh_render_reply_injections_included
#define _shy_sender_common_logic_main_menu_selection_mesh_render_reply_injections_included

#include "../../message/mesh_render_reply/shy_mesh_render_reply_injections.h"

#include "./shy_mesh_render_reply.h"

typedef shy_sender_common_logic_main_menu_selection_mesh_render_reply so_called_sender_common_logic_main_menu_selection_mesh_render_reply ;

#endif
