#ifndef _shy_common_logic_door_animation_transform_request_message_injections_included
#define _shy_common_logic_door_animation_transform_request_message_injections_included

#include "./shy_transform_request.h"

typedef shy_common_logic_door_animation_transform_request_message so_called_common_logic_door_animation_transform_request_message ;

#endif
