#ifndef _shy_loadable_consts_reflection_logic_perspective_injections_included
#define _shy_loadable_consts_reflection_logic_perspective_injections_included

#include "./shy_perspective.h"

typedef shy_loadable_consts_reflection_logic_perspective so_called_loadable_consts_reflection_logic_perspective ;

#endif
