#ifndef _shy_sender_common_logic_main_menu_letters_meshes_destroy_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_destroy_request_injections_included

#include "../../message/destroy_request/shy_destroy_request_injections.h"

#include "./shy_destroy_request.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_destroy_request so_called_sender_common_logic_main_menu_letters_meshes_destroy_request ;

#endif
