#ifndef _shy_sender_common_logic_salutation_letters_meshes_storage_mesh_request_injections_included
#define _shy_sender_common_logic_salutation_letters_meshes_storage_mesh_request_injections_included

#include "../../message/mesh_request/shy_mesh_request_injections.h"
#include "./shy_mesh_request.h"

typedef shy_sender_common_logic_salutation_letters_meshes_storage_mesh_request so_called_sender_common_logic_salutation_letters_meshes_storage_mesh_request ;

#endif
