#ifndef _shy_common_engine_render_projection_frustum_message_injections_included
#define _shy_common_engine_render_projection_frustum_message_injections_included

#include "src/injections/platform/math/num/fract/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_engine_render_projection_frustum_message so_called_common_engine_render_projection_frustum_message ;

#endif
