#ifndef _shy_common_logic_amusement_launch_permit_sender_injections_included
#define _shy_common_logic_amusement_launch_permit_sender_injections_included

#include "common/logic/amusement/message/launch_permit/shy_launch_permit_injections.h"

#include "./shy_launch_permit.h"

typedef shy_common_logic_amusement_launch_permit_sender so_called_common_logic_amusement_launch_permit_sender ;

#endif
