#ifndef _shy_macosx_platform_sound_insider_injections_included
#define _shy_macosx_platform_sound_insider_injections_included

#include "src/platform/sound/openal/insider/shy_insider_injections.h"
typedef so_called_platform_sound_openal_insider so_called_platform_sound_insider ;

#endif

