#ifndef _shy_common_logic_main_menu_selection_animation_appear_start_sender_injections_included
#define _shy_common_logic_main_menu_selection_animation_appear_start_sender_injections_included

#include "common/logic/main_menu/selection/animation/message/appear_start/shy_appear_start_injections.h"

#include "./shy_appear_start.h"

typedef shy_common_logic_main_menu_selection_animation_appear_start_sender so_called_common_logic_main_menu_selection_animation_appear_start_sender ;

#endif
