#ifndef _shy_sender_common_logic_main_menu_selection_animation_appear_start_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_appear_start_injections_included

#include "../../message/appear_start/shy_appear_start_injections.h"

#include "./shy_appear_start.h"

typedef shy_sender_common_logic_main_menu_selection_animation_appear_start so_called_sender_common_logic_main_menu_selection_animation_appear_start ;

#endif
