#ifndef _shy_sender_common_logic_main_menu_choice_void_selected_injections_included
#define _shy_sender_common_logic_main_menu_choice_void_selected_injections_included

#include "../../message/choice_void_selected/shy_choice_void_selected_injections.h"

#include "./shy_choice_void_selected.h"

typedef shy_sender_common_logic_main_menu_choice_void_selected so_called_sender_common_logic_main_menu_choice_void_selected ;

#endif
