#ifndef _shy_common_logic_salutation_letters_text_storage_add_letter_sender_injections_included
#define _shy_common_logic_salutation_letters_text_storage_add_letter_sender_injections_included

#include "src/common/logic/salutation/letters/text/storage/add/letter/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_text_storage_add_letter_sender so_called_common_logic_salutation_letters_text_storage_add_letter_sender ;

#endif
