#ifndef _shy_common_engine_render_texture_loader_ready_reply_message_injections_included
#define _shy_common_engine_render_texture_loader_ready_reply_message_injections_included

#include "src/injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_engine_render_texture_loader_ready_reply_message so_called_common_engine_render_texture_loader_ready_reply_message ;

#endif
