class shy_common_logic_main_menu_selection_animation_consts
{
public :
    static const so_called_type_platform_math_num_fract appear_horizontal_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract appear_horizontal_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract appear_horizontal_scale_value_begin ;
    static const so_called_type_platform_math_num_fract appear_horizontal_scale_value_end ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_time_from_begin_to_middle ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_time_from_middle_to_end ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_value_begin ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_value_middle ;
    static const so_called_type_platform_math_num_fract appear_vertical_scale_value_end ;
    static const so_called_type_platform_math_num_fract appear_total_animation_time ;
    static const so_called_type_platform_math_num_fract disappear_horizontal_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract disappear_horizontal_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract disappear_horizontal_scale_value_begin ;
    static const so_called_type_platform_math_num_fract disappear_horizontal_scale_value_end ;
    static const so_called_type_platform_math_num_fract disappear_vertical_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract disappear_vertical_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract disappear_vertical_scale_value_begin ;
    static const so_called_type_platform_math_num_fract disappear_vertical_scale_value_end ;
    static const so_called_type_platform_math_num_fract idle_position_z ;
    static const so_called_type_platform_math_num_fract idle_attention_horizontal_scale_min ;
    static const so_called_type_platform_math_num_fract idle_attention_horizontal_scale_max ;
    static const so_called_type_platform_math_num_fract idle_attention_horizontal_scale_period_in_seconds ;
    static const so_called_type_platform_math_num_fract idle_attention_vertical_scale_min ;
    static const so_called_type_platform_math_num_fract idle_attention_vertical_scale_max ;
    static const so_called_type_platform_math_num_fract idle_attention_vertical_scale_period_in_seconds ;
    static const so_called_type_platform_math_num_fract push_time_from_begin_to_middle ;
    static const so_called_type_platform_math_num_fract push_time_from_middle_to_end ;
    static const so_called_type_platform_math_num_fract push_horizontal_scale_begin ;
    static const so_called_type_platform_math_num_fract push_horizontal_scale_middle ;
    static const so_called_type_platform_math_num_fract push_horizontal_scale_end ;
    static const so_called_type_platform_math_num_fract push_vertical_scale_begin ;
    static const so_called_type_platform_math_num_fract push_vertical_scale_middle ;
    static const so_called_type_platform_math_num_fract push_vertical_scale_end ;
    static const so_called_type_platform_math_num_fract push_attention_horizontal_scale_min ;
    static const so_called_type_platform_math_num_fract push_attention_horizontal_scale_max ;
    static const so_called_type_platform_math_num_fract push_attention_vertical_scale_min ;
    static const so_called_type_platform_math_num_fract push_attention_vertical_scale_max ;
    static const so_called_type_platform_math_num_fract push_attention_period_in_seconds ;
    static const so_called_type_platform_math_num_fract push_weight_time_to_begin ;
    static const so_called_type_platform_math_num_fract push_weight_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract push_weight_min ;
    static const so_called_type_platform_math_num_fract push_weight_max ;
    static const so_called_type_platform_math_num_fract select_horizontal_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract select_horizontal_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract select_horizontal_scale_value_begin ;
    static const so_called_type_platform_math_num_fract select_horizontal_scale_value_end ;
    static const so_called_type_platform_math_num_fract select_vertical_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract select_vertical_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract select_vertical_scale_value_begin ;
    static const so_called_type_platform_math_num_fract select_vertical_scale_value_end ;
    static const so_called_type_platform_math_num_fract select_total_animation_time ;
    static const so_called_type_platform_math_num_fract unselect_horizontal_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract unselect_horizontal_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract unselect_horizontal_scale_value_begin ;
    static const so_called_type_platform_math_num_fract unselect_horizontal_scale_value_end ;
    static const so_called_type_platform_math_num_fract unselect_vertical_scale_time_to_begin ;
    static const so_called_type_platform_math_num_fract unselect_vertical_scale_time_from_begin_to_end ;
    static const so_called_type_platform_math_num_fract unselect_vertical_scale_value_begin ;
    static const so_called_type_platform_math_num_fract unselect_vertical_scale_value_end ;
    static const so_called_type_platform_math_num_fract unselect_total_animation_time ;
    static void binding ( ) ;
} ;

