const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_delay_per_col_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_delay_per_row_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_scale_middle ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_time_from_begin_to_middle_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: appear_time_from_middle_to_end_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_animation_time_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_delay_per_col_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_delay_per_row_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: disappear_time_from_begin_to_end_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_horizontal_shift_amplitude ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_horizontal_shift_period_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_horizontal_shift_phase_per_row ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_vertical_shift_amplitude ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_vertical_shift_period_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_vertical_shift_phase_per_col ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: idle_vertical_shift_phase_per_row ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_push_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_push_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_push_scale_middle ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_push_time_from_begin_to_middle ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_push_time_from_middle_to_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_scale_max ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_scale_min ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_time_stable ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_time_transition ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_weight_time_from_begin_to_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: selection_weight_time_to_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: unselection_weight_time_from_begin_to_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_animation_consts :: unselection_weight_time_to_begin ;

void shy_common_logic_main_menu_letters_animation_consts :: binding ( )
{
}
