#ifndef _shy_sender_common_logic_main_menu_letters_layout_position_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_layout_position_request_injections_included

#include "../../message/position_request/shy_position_request_injections.h"

#include "./shy_position_request.h"

typedef shy_sender_common_logic_main_menu_letters_layout_position_request so_called_sender_common_logic_main_menu_letters_layout_position_request ;

#endif
