#ifndef _shy_type_loadable_consts_content_value_fract_container_injections_included
#define _shy_type_loadable_consts_content_value_fract_container_injections_included

#include "loadable/consts/content/type/value_fract/shy_value_fract_injections.h"
#include "injections/lib/std/map/shy_map.h"

#include "./shy_value_fract_container.h"

typedef shy_type_loadable_consts_content_value_fract_container so_called_type_loadable_consts_content_value_fract_container ;

#endif
