#ifndef _shy_common_logic_salutation_letters_text_storage_size_checker_injections_included
#define _shy_common_logic_salutation_letters_text_storage_size_checker_injections_included

#include "src/common/logic/salutation/letters/text/storage/size/reply/message/shy_message_injections.h"
#include "src/common/logic/salutation/letters/text/storage/size/request/message/shy_message_injections.h"

#include "./shy_checker.h"

typedef shy_common_logic_salutation_letters_text_storage_size_checker so_called_common_logic_salutation_letters_text_storage_size_checker ;

#endif
