#ifndef _shy_common_logic_controls_state_reply_sender_injections_included
#define _shy_common_logic_controls_state_reply_sender_injections_included

#include "common/logic/controls/message/state_reply/shy_state_reply_injections.h"

#include "./shy_state_reply.h"

typedef shy_common_logic_controls_state_reply_sender so_called_common_logic_controls_state_reply_sender ;

#endif
