// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: eraser_a = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: eraser_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: eraser_g = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: eraser_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: pen_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: pen_b = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: pen_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: pen_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_texture_consts :: time_between_letters_creation = so_called_platform_math :: init_num_fract ( 20 , 1000 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_font_texture_consts :: letter_size_in_texels = so_called_platform_math :: init_num_whole ( 64 ) ;

// autogenerated file end
