#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_id_request_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_id_request_sender_injections_included

#include "../../message/mesh_id_request/shy_mesh_id_request_injections.h"

#include "./shy_mesh_id_request.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_id_request_sender so_called_common_logic_main_menu_letters_meshes_mesh_id_request_sender ;

#endif
