#ifndef _shy_common_logic_main_menu_selection_track_row_selected_message_injections_included
#define _shy_common_logic_main_menu_selection_track_row_selected_message_injections_included

#include "src/injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_main_menu_selection_track_row_selected_message so_called_common_logic_main_menu_selection_track_row_selected_message ;

#endif
