#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender_injections_included

#include "../../message/mesh_create_next/shy_mesh_create_next_injections.h"

#include "./shy_mesh_create_next.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender so_called_common_logic_main_menu_letters_meshes_mesh_create_next_sender ;

#endif
