#ifndef _shy_message_common_engine_render_texture_mode_modulate_included
#define _shy_message_common_engine_render_texture_mode_modulate_included

class shy_message_common_engine_render_texture_mode_modulate
{
} ;

#endif

