#ifndef _shy_message_common_engine_render_enable_face_culling_injections_included
#define _shy_message_common_engine_render_enable_face_culling_injections_included

#include "shy_enable_face_culling.h"

typedef shy_message_common_engine_render_enable_face_culling so_called_message_common_engine_render_enable_face_culling ;

#endif
