#ifndef _shy_message_common_engine_render_frame_loss_request_included
#define _shy_message_common_engine_render_frame_loss_request_included

class shy_message_common_engine_render_frame_loss_request
{
} ;

#endif

