#ifndef _shy_common_logic_core_use_ortho_projection_request_sender_injections_included
#define _shy_common_logic_core_use_ortho_projection_request_sender_injections_included

#include "common/logic/core/message/use_ortho_projection_request/shy_use_ortho_projection_request_injections.h"

#include "./shy_use_ortho_projection_request.h"

typedef shy_common_logic_core_use_ortho_projection_request_sender so_called_common_logic_core_use_ortho_projection_request_sender ;

#endif
