#ifndef _shy_common_logic_main_menu_letters_boundaries_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_boundaries_reply_sender_injections_included

#include "../../message/boundaries_reply/shy_boundaries_reply_injections.h"

#include "./shy_boundaries_reply.h"

typedef shy_common_logic_main_menu_letters_boundaries_reply_sender so_called_common_logic_main_menu_letters_boundaries_reply_sender ;

#endif
