#ifndef _shy_message_common_logic_main_menu_selection_animation_push_weight_request_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_push_weight_request_injections_included

#include "./shy_push_weight_request.h"

typedef shy_message_common_logic_main_menu_selection_animation_push_weight_request so_called_message_common_logic_main_menu_selection_animation_push_weight_request ;

#endif
