#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender_injections_included

#include "src/common/logic/main/menu/letters/meshes/mesh/create/next/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_create_next_sender so_called_common_logic_main_menu_letters_meshes_mesh_create_next_sender ;

#endif
