// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: color_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: color_b = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: color_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: color_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: mesh_size = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_font_mesh_consts :: time_between_letters_creation = so_called_platform_math :: init_num_fract ( 20 , 1000 ) ;

// autogenerated file end
