#ifndef _shy_common_logic_salutation_letters_animation_appear_transform_reply_sender_injections_included
#define _shy_common_logic_salutation_letters_animation_appear_transform_reply_sender_injections_included

#include "src/common/logic/salutation/letters/animation/appear/transform/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_animation_appear_transform_reply_sender so_called_common_logic_salutation_letters_animation_appear_transform_reply_sender ;

#endif
