#ifndef _shy_common_logic_text_letter_big_tex_coords_reply_sender_injections_included
#define _shy_common_logic_text_letter_big_tex_coords_reply_sender_injections_included

#include "src/common/logic/text/letter/big/tex/coords/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_text_letter_big_tex_coords_reply_sender so_called_common_logic_text_letter_big_tex_coords_reply_sender ;

#endif
