#ifndef _shy_common_logic_salutation_letters_animation_roll_in_play_sender_injections_included
#define _shy_common_logic_salutation_letters_animation_roll_in_play_sender_injections_included

#include "common/logic/salutation/letters/animation/roll_in/play/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_animation_roll_in_play_sender so_called_common_logic_salutation_letters_animation_roll_in_play_sender ;

#endif
