#ifndef _shy_sender_common_logic_salutation_letters_animation_roll_in_play_injections_included
#define _shy_sender_common_logic_salutation_letters_animation_roll_in_play_injections_included

#include "../message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_animation_roll_in_play so_called_sender_common_logic_salutation_letters_animation_roll_in_play ;

#endif
