#ifndef _shy_common_engine_rasterizer_draw_ellipse_in_rect_sender_injections_included
#define _shy_common_engine_rasterizer_draw_ellipse_in_rect_sender_injections_included

#include "src/common/engine/rasterizer/draw/ellipse/in/rect/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_rasterizer_draw_ellipse_in_rect_sender so_called_common_engine_rasterizer_draw_ellipse_in_rect_sender ;

#endif
