#ifndef _shy_common_logic_main_menu_letters_next_row_sender_injections_included
#define _shy_common_logic_main_menu_letters_next_row_sender_injections_included

#include "common/logic/main_menu/letters/message/next_row/shy_next_row_injections.h"

#include "./shy_next_row.h"

typedef shy_common_logic_main_menu_letters_next_row_sender so_called_common_logic_main_menu_letters_next_row_sender ;

#endif
