#ifndef _shy_common_logic_application_fsm_behaviour_static_injections_included
#define _shy_common_logic_application_fsm_behaviour_static_injections_included

#include "common/logic/application/fsm/inputs/type/shy_type_injections.h"

#include "common/logic/application/fsm/behaviour/static/autogenerated/shy_autogenerated_injections.h"

#endif
