#include "./shy_static_injections.h"

#include "../../actions/shy_actions_injections.h"

#include "../../../../../autogenerated/logic_application_fsm_behaviour_static/shy_logic_application_fsm_behaviour_static_injections.hpp"
