#ifndef _shy_common_logic_application_fsm_behaviour_static_injections_included
#define _shy_common_logic_application_fsm_behaviour_static_injections_included

#include "../../type/inputs/shy_inputs_injections.h"

#include "../../../../../autogenerated/logic_application_fsm_behaviour_static/shy_logic_application_fsm_behaviour_static_injections.h"

#endif
