#include "./shy_static_injections.h"

#include "src/common/logic/application/fsm/actions/shy_actions_injections.h"

#include "src/common/logic/application/fsm/behaviour/static/autogenerated/shy_autogenerated_injections.hpp"
