// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_begin_b = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_begin_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_begin_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_end_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_end_g = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: color_end_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fader_consts :: fade_time = so_called_platform_math :: init_num_fract ( 19 , 10 ) ;

// autogenerated file end
