#ifndef _shy_sender_common_logic_salutation_animation_zoom_transform_reply_injections_included
#define _shy_sender_common_logic_salutation_animation_zoom_transform_reply_injections_included

#include "../message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_animation_zoom_transform_reply so_called_sender_common_logic_salutation_animation_zoom_transform_reply ;

#endif
