#ifndef _shy_sender_common_logic_salutation_letters_generate_finished_injections_included
#define _shy_sender_common_logic_salutation_letters_generate_finished_injections_included

#include "../../message/generate_finished/shy_generate_finished_injections.h"
#include "./shy_generate_finished.h"

typedef shy_sender_common_logic_salutation_letters_generate_finished so_called_sender_common_logic_salutation_letters_generate_finished ;

#endif
