#ifndef _shy_sender_common_logic_salutation_timer_update_injections_included
#define _shy_sender_common_logic_salutation_timer_update_injections_included

#include "common/logic/salutation/timer/update/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_timer_update so_called_sender_common_logic_salutation_timer_update ;

#endif
