#ifndef _shy_message_common_logic_door_render_request_injections_included
#define _shy_message_common_logic_door_render_request_injections_included

#include "./shy_render_request.h"

typedef shy_message_common_logic_door_render_request so_called_message_common_logic_door_render_request ;

#endif
