#ifndef _shy_common_logic_main_menu_letters_meshes_iteration_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_iteration_sender_injections_included

#include "../../message/iteration/shy_iteration_injections.h"

#include "./shy_iteration.h"

typedef shy_common_logic_main_menu_letters_meshes_iteration_sender so_called_common_logic_main_menu_letters_meshes_iteration_sender ;

#endif
