#ifndef _shy_type_loadable_fsm_content_on_input_injections_included
#define _shy_type_loadable_fsm_content_on_input_injections_included

#include "./shy_on_input.h"

typedef shy_type_loadable_fsm_content_on_input so_called_type_loadable_fsm_content_on_input ;

#endif
