#ifndef _shy_common_engine_render_enable_face_culling_sender_injections_included
#define _shy_common_engine_render_enable_face_culling_sender_injections_included

#include "../../message/enable_face_culling/shy_enable_face_culling_injections.h"

#include "./shy_enable_face_culling.h"

typedef shy_common_engine_render_enable_face_culling_sender so_called_common_engine_render_enable_face_culling_sender ;

#endif

