const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: appear_pos_angle_periods ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: appear_rubber_first ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: appear_rubber_last ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: disappear_pos_angle_periods ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: disappear_rubber_first ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: disappear_rubber_last ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: scene_scale_max ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: scene_scale_min ;
const so_called_type_platform_math_num_fract shy_common_logic_title_consts :: spin_radius_in_letters ;
const so_called_type_platform_math_num_whole shy_common_logic_title_consts :: appear_duration_in_frames ;
const so_called_type_platform_math_num_whole shy_common_logic_title_consts :: disappear_duration_in_frames ;
const so_called_type_platform_math_num_whole shy_common_logic_title_consts :: frames_between_letters ;

