#ifndef _shy_common_logic_door_mesh_set_transform_message_injections_included
#define _shy_common_logic_door_mesh_set_transform_message_injections_included

#include "src/injections/platform/matrix/data/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_door_mesh_set_transform_message so_called_common_logic_door_mesh_set_transform_message ;

#endif
