#ifndef _shy_loadable_consts_reflection_logic_main_menu_letters_layout_injections_included
#define _shy_loadable_consts_reflection_logic_main_menu_letters_layout_injections_included

#include "./shy_layout.h"

typedef shy_loadable_consts_reflection_logic_main_menu_letters_layout so_called_loadable_consts_reflection_logic_main_menu_letters_layout ;

#endif
