#ifndef _shy_common_logic_observer_animation_transform_reply_message_injections_included
#define _shy_common_logic_observer_animation_transform_reply_message_injections_included

#include "injections/platform/matrix/type/data/shy_data.h"

#include "./shy_transform_reply.h"

typedef shy_common_logic_observer_animation_transform_reply_message so_called_common_logic_observer_animation_transform_reply_message ;

#endif
