#ifndef _shy_message_common_logic_salutation_letters_meshes_cleaner_clean_finished_injections_included
#define _shy_message_common_logic_salutation_letters_meshes_cleaner_clean_finished_injections_included

#include "./shy_clean_finished.h"

typedef shy_message_common_logic_salutation_letters_meshes_cleaner_clean_finished so_called_message_common_logic_salutation_letters_meshes_cleaner_clean_finished ;

#endif
