#ifndef _shy_iphone_platform_render_vertex_data_type_injections_included
#define _shy_iphone_platform_render_vertex_data_type_injections_included

#include "platform/render/opengl/type/vertex_data/shy_vertex_data_injections.h"
typedef so_called_platform_render_opengl_vertex_data_type so_called_platform_render_vertex_data_type ;

#endif
