#ifndef _shy_message_common_logic_main_menu_letters_boundaries_request_injections_included
#define _shy_message_common_logic_main_menu_letters_boundaries_request_injections_included

#include "./shy_boundaries_request.h"

typedef shy_message_common_logic_main_menu_letters_boundaries_request so_called_message_common_logic_main_menu_letters_boundaries_request ;

#endif
