#ifndef _shy_type_iphone_platform_sound_sample_stereo_injections_included
#define _shy_type_iphone_platform_sound_sample_stereo_injections_included

#include "platform/sound/openal/type/sample_stereo/shy_sample_stereo_injections.h"
typedef so_called_type_platform_sound_openal_sample_stereo so_called_type_platform_sound_sample_stereo ;

#endif
