#ifndef _shy_type_common_engine_fsm_state_injections_included
#define _shy_type_common_engine_fsm_state_injections_included

#include "./shy_state.h"

typedef shy_type_common_engine_fsm_state so_called_type_common_engine_fsm_state ;

#endif
