#ifndef _shy_common_logic_core_use_perspective_projection_reply_sender_injections_included
#define _shy_common_logic_core_use_perspective_projection_reply_sender_injections_included

#include "../../message/use_perspective_projection_reply/shy_use_perspective_projection_reply_injections.h"

#include "./shy_use_perspective_projection_reply.h"

typedef shy_common_logic_core_use_perspective_projection_reply_sender so_called_common_logic_core_use_perspective_projection_reply_sender ;

#endif
