#ifndef _shy_common_logic_main_menu_selection_animation_idle_attention_injections_included
#define _shy_common_logic_main_menu_selection_animation_idle_attention_injections_included

#include "common/logic/main_menu/selection/animation/message/idle_attention_transform_request/shy_idle_attention_transform_request_injections.h"
#include "common/logic/main_menu/message/launch_permit/shy_launch_permit_injections.h"
#include "common/logic/main_menu/message/update/shy_update_injections.h"
#include "common/message/init/shy_init_injections.h"
#include "injections/platform/scheduler/shy_scheduler.h"

#include "./shy_idle_attention.h"

typedef shy_common_logic_main_menu_selection_animation_idle_attention_scheduled so_called_common_logic_main_menu_selection_animation_idle_attention ;

#endif
