#ifndef _shy_sender_common_logic_core_use_perspective_projection_request_injections_included
#define _shy_sender_common_logic_core_use_perspective_projection_request_injections_included

#include "../../message/use_perspective_projection_request/shy_use_perspective_projection_request_injections.h"

#include "./shy_use_perspective_projection_request.h"

typedef shy_sender_common_logic_core_use_perspective_projection_request so_called_sender_common_logic_core_use_perspective_projection_request ;

#endif
