#ifndef _shy_message_common_logic_room_texture_select_reply_injections_included
#define _shy_message_common_logic_room_texture_select_reply_injections_included

#include "./shy_texture_select_reply.h"

typedef shy_message_common_logic_room_texture_select_reply so_called_message_common_logic_room_texture_select_reply ;

#endif
