#ifndef _shy_win_platform_render_texture_loader_resource_id_type_injections_included
#define _shy_win_platform_render_texture_loader_resource_id_type_injections_included

#include "platform/render/texture_loader/winapi/type/resource_id/shy_resource_id_injections.h"
typedef so_called_platform_render_texture_loader_winapi_resource_id_type so_called_platform_render_texture_loader_resource_id_type ;

#endif
