#ifndef _shy_type_win_platform_render_texture_loader_resource_id_injections_included
#define _shy_type_win_platform_render_texture_loader_resource_id_injections_included

#include "platform/render/texture_loader/winapi/type/resource_id/shy_resource_id_injections.h"
typedef so_called_type_platform_render_texture_loader_winapi_resource_id so_called_type_platform_render_texture_loader_resource_id ;

#endif
