#ifndef _shy_message_common_logic_salutation_letters_text_storage_letter_request_injections_included
#define _shy_message_common_logic_salutation_letters_text_storage_letter_request_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_message.h"

typedef shy_message_common_logic_salutation_letters_text_storage_letter_request so_called_message_common_logic_salutation_letters_text_storage_letter_request ;

#endif
