#ifndef _shy_common_logic_main_menu_letters_meshes_count_request_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_count_request_sender_injections_included

#include "../../message/count_request/shy_count_request_injections.h"

#include "./shy_count_request.h"

typedef shy_common_logic_main_menu_letters_meshes_count_request_sender so_called_common_logic_main_menu_letters_meshes_count_request_sender ;

#endif
