#ifndef _shy_type_loadable_fsm_content_input_binding_container_injections_included
#define _shy_type_loadable_fsm_content_input_binding_container_injections_included

#include "loadable/fsm/content/type/input_binding/shy_input_binding_injections.h"
#include "injections/lib/std/map/shy_map.h"

#include "./shy_input_binding_container.h"

typedef shy_type_loadable_fsm_content_input_binding_container so_called_type_loadable_fsm_content_input_binding_container ;

#endif
