#ifndef _shy_loadable_fsm_content_arbitrary_inputs_type_injections_included
#define _shy_loadable_fsm_content_arbitrary_inputs_type_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_arbitrary_inputs.h"

typedef shy_loadable_fsm_content_arbitrary_inputs_type so_called_loadable_fsm_content_arbitrary_inputs_type ;

#endif
