#ifndef _shy_common_logic_observer_animation_flight_transform_reply_message_injections_included
#define _shy_common_logic_observer_animation_flight_transform_reply_message_injections_included

#include "src/injections/platform/vector/data/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_observer_animation_flight_transform_reply_message so_called_common_logic_observer_animation_flight_transform_reply_message ;

#endif
