#ifndef _shy_common_engine_rasterizer_use_texture_sender_injections_included
#define _shy_common_engine_rasterizer_use_texture_sender_injections_included

#include "common/engine/rasterizer/message/use_texture/shy_use_texture_injections.h"

#include "./shy_use_texture.h"

typedef shy_common_engine_rasterizer_use_texture_sender so_called_common_engine_rasterizer_use_texture_sender ;

#endif
