#ifndef _shy_common_engine_render_projection_frustum_message_injections_included
#define _shy_common_engine_render_projection_frustum_message_injections_included

#include "injections/platform/math/type/num_fract/shy_num_fract.h"

#include "./shy_projection_frustum.h"

typedef shy_common_engine_render_projection_frustum_message so_called_common_engine_render_projection_frustum_message ;

#endif
