#ifndef _shy_common_engine_render_texture_select_sender_injections_included
#define _shy_common_engine_render_texture_select_sender_injections_included

#include "common/engine/render/message/texture_select/shy_texture_select_injections.h"

#include "./shy_texture_select.h"

typedef shy_common_engine_render_texture_select_sender so_called_common_engine_render_texture_select_sender ;

#endif

