#ifndef _shy_platform_sound_directx_sample_stereo_type_injections_included
#define _shy_platform_sound_directx_sample_stereo_type_injections_included

#include "injections/lib/std/int32_t/shy_int32_t.h"
#include "./shy_sample_stereo.h"

typedef shy_platform_sound_directx_sample_stereo_type so_called_platform_sound_directx_sample_stereo_type ;

#endif
