#ifndef _shy_type_platform_sound_directx_sample_stereo_injections_included
#define _shy_type_platform_sound_directx_sample_stereo_injections_included

#include "injections/lib/std/int32_t/shy_int32_t.h"
#include "./shy_sample_stereo.h"

typedef shy_type_platform_sound_directx_sample_stereo so_called_type_platform_sound_directx_sample_stereo ;

#endif
