const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: letter_mesh_color_a ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: letter_mesh_color_b ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: letter_mesh_color_g ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: letter_mesh_color_r ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: letter_mesh_size ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_letters_meshes_consts :: time_between_creation ;

void shy_common_logic_main_menu_letters_meshes_consts :: binding ( )
{
}
