#ifndef _shy_sender_common_logic_main_menu_letters_animation_selection_weight_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_animation_selection_weight_request_injections_included

#include "../../message/selection_weight_request/shy_selection_weight_request_injections.h"

#include "./shy_selection_weight_request.h"

typedef shy_sender_common_logic_main_menu_letters_animation_selection_weight_request so_called_sender_common_logic_main_menu_letters_animation_selection_weight_request ;

#endif
