#ifndef _shy_macosx_lib_opengl_injections_included
#define _shy_macosx_lib_opengl_injections_included

#include <OpenGL/glext.h>

#define so_called_lib_opengl_glBindTexture glBindTexture
#define so_called_lib_opengl_glBlendFunc glBlendFunc
#define so_called_lib_opengl_glClear glClear
#define so_called_lib_opengl_glClearColor glClearColor
#define so_called_lib_opengl_glClearDepth glClearDepth
#define so_called_lib_opengl_glEnable glEnable
#define so_called_lib_opengl_glFogf glFogf
#define so_called_lib_opengl_glFogfv glFogfv
#define so_called_lib_opengl_glDisable glDisable
#define so_called_lib_opengl_glGenTextures glGenTextures
#define so_called_lib_opengl_glPixelStorei glPixelStorei
#define so_called_lib_opengl_glTexEnvf glTexEnvf
#define so_called_lib_opengl_glTexImage2D glTexImage2D
#define so_called_lib_opengl_glTexParameteri glTexParameteri
#define so_called_lib_opengl_glTexSubImage2D glTexSubImage2D 
#define so_called_lib_opengl_GL_BGRA GL_BGRA
#define so_called_lib_opengl_GL_BLEND GL_BLEND
#define so_called_lib_opengl_GL_COLOR_BUFFER_BIT GL_COLOR_BUFFER_BIT
#define so_called_lib_opengl_GL_CULL_FACE GL_CULL_FACE
#define so_called_lib_opengl_GL_DEPTH_BUFFER_BIT GL_DEPTH_BUFFER_BIT
#define so_called_lib_opengl_GL_DEPTH_TEST GL_DEPTH_TEST
#define so_called_lib_opengl_GL_FOG GL_FOG
#define so_called_lib_opengl_GL_FOG_COLOR GL_FOG_COLOR
#define so_called_lib_opengl_GL_FOG_END GL_FOG_END
#define so_called_lib_opengl_GL_FOG_MODE GL_FOG_MODE
#define so_called_lib_opengl_GL_FOG_START GL_FOG_START
#define so_called_lib_opengl_GL_LINEAR GL_LINEAR
#define so_called_lib_opengl_GL_MODULATE GL_MODULATE
#define so_called_lib_opengl_GL_ONE_MINUS_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
#define so_called_lib_opengl_GL_RGBA GL_RGBA
#define so_called_lib_opengl_GL_REPEAT GL_REPEAT
#define so_called_lib_opengl_GL_SRC_ALPHA GL_SRC_ALPHA
#define so_called_lib_opengl_GL_TEXTURE_2D GL_TEXTURE_2D
#define so_called_lib_opengl_GL_TEXTURE_ENV GL_TEXTURE_ENV
#define so_called_lib_opengl_GL_TEXTURE_ENV_MODE GL_TEXTURE_ENV_MODE
#define so_called_lib_opengl_GL_TEXTURE_MAG_FILTER GL_TEXTURE_MAG_FILTER
#define so_called_lib_opengl_GL_TEXTURE_MIN_FILTER GL_TEXTURE_MIN_FILTER
#define so_called_lib_opengl_GL_TEXTURE_WRAP_S GL_TEXTURE_WRAP_S
#define so_called_lib_opengl_GL_TEXTURE_WRAP_T GL_TEXTURE_WRAP_T
#define so_called_lib_opengl_GL_UNPACK_ALIGNMENT GL_UNPACK_ALIGNMENT
#define so_called_lib_opengl_GL_UNSIGNED_BYTE GL_UNSIGNED_BYTE
typedef GLfloat so_called_lib_opengl_GLfloat ;
typedef GLsizei so_called_lib_opengl_GLsizei ;
typedef GLubyte so_called_lib_opengl_GLubyte ;

#endif
