#ifndef _shy_common_logic_main_menu_letters_animation_selection_push_transform_request_message_injections_included
#define _shy_common_logic_main_menu_letters_animation_selection_push_transform_request_message_injections_included

#include "../../../../../../../injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_selection_push_transform_request.h"

typedef shy_common_logic_main_menu_letters_animation_selection_push_transform_request_message so_called_common_logic_main_menu_letters_animation_selection_push_transform_request_message ;

#endif
