#ifndef _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message_injections_included
#define _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message_injections_included

#include "src/injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message so_called_common_logic_main_menu_letters_animation_unselection_weight_select_row_message ;

#endif
