#ifndef _shy_type_macosx_platform_render_vertex_buffer_id_injections_included
#define _shy_type_macosx_platform_render_vertex_buffer_id_injections_included

#include "platform/render/opengl/type/vertex_buffer_id/shy_vertex_buffer_id_injections.h"
typedef so_called_type_platform_render_opengl_vertex_buffer_id so_called_type_platform_render_vertex_buffer_id ;

#endif
