#ifndef _shy_loadable_fsm_content_action_do_type_injections_included
#define _shy_loadable_fsm_content_action_do_type_injections_included

#include "./shy_action_do.h"

typedef shy_loadable_fsm_content_action_do_type so_called_loadable_fsm_content_action_do_type ;

#endif
