#ifndef _shy_type_loadable_consts_content_value_whole_container_injections_included
#define _shy_type_loadable_consts_content_value_whole_container_injections_included

#include "loadable/consts/content/type/value_whole/shy_value_whole_injections.h"

#include "./shy_value_whole_container.h"

typedef shy_type_loadable_consts_content_value_whole_container so_called_type_loadable_consts_content_value_whole_container ;

#endif
