#ifndef _shy_loadable_consts_content_value_whole_container_type_injections_included
#define _shy_loadable_consts_content_value_whole_container_type_injections_included

#include "loadable/consts/content/type/value_whole/shy_value_whole_injections.h"

#include "./shy_value_whole_container.h"

typedef shy_loadable_consts_content_value_whole_container_type so_called_loadable_consts_content_value_whole_container_type ;

#endif
