#ifndef _shy_common_logic_fidget_render_reply_message_injections_included
#define _shy_common_logic_fidget_render_reply_message_injections_included

#include "./shy_render_reply.h"

typedef shy_common_logic_fidget_render_reply_message so_called_common_logic_fidget_render_reply_message ;

#endif
