#ifndef _shy_platform_math_int_float_const_int_32_type_injections_included
#define _shy_platform_math_int_float_const_int_32_type_injections_included

#include "injections/lib/std/int32_t/shy_int32_t.h"

#include "./shy_const_int_32.h"

typedef shy_platform_math_int_float_const_int_32_type so_called_platform_math_int_float_const_int_32_type ;

#endif
