#ifndef _shy_type_platform_math_int_float_const_int_32_injections_included
#define _shy_type_platform_math_int_float_const_int_32_injections_included

#include "injections/lib/std/int32_t/shy_int32_t.h"

#include "./shy_const_int_32.h"

typedef shy_type_platform_math_int_float_const_int_32 so_called_type_platform_math_int_float_const_int_32 ;

#endif
