#ifndef _shy_sender_common_engine_render_mesh_set_transform_injections_included
#define _shy_sender_common_engine_render_mesh_set_transform_injections_included

#include "../../message/mesh_set_transform/shy_mesh_set_transform_injections.h"

#include "./shy_mesh_set_transform.h"

typedef shy_sender_common_engine_render_mesh_set_transform so_called_sender_common_engine_render_mesh_set_transform ;

#endif

