#ifndef _shy_common_engine_rasterizer_finalize_reply_message_injections_included
#define _shy_common_engine_rasterizer_finalize_reply_message_injections_included

#include "./shy_finalize_reply.h"

typedef shy_common_engine_rasterizer_finalize_reply_message so_called_common_engine_rasterizer_finalize_reply_message ;

#endif
