#ifndef _shy_message_common_engine_rasterizer_finalize_reply_injections_included
#define _shy_message_common_engine_rasterizer_finalize_reply_injections_included

#include "./shy_finalize_reply.h"

typedef shy_message_common_engine_rasterizer_finalize_reply so_called_message_common_engine_rasterizer_finalize_reply ;

#endif
