#ifndef _shy_common_logic_text_render_reply_message_injections_included
#define _shy_common_logic_text_render_reply_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_text_render_reply_message so_called_common_logic_text_render_reply_message ;

#endif
