#ifndef _shy_common_engine_render_matrix_identity_sender_injections_included
#define _shy_common_engine_render_matrix_identity_sender_injections_included

#include "src/common/engine/render/matrix/identity/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_render_matrix_identity_sender so_called_common_engine_render_matrix_identity_sender ;

#endif

