#ifndef _shy_sender_common_logic_main_menu_choice_row_selected_injections_included
#define _shy_sender_common_logic_main_menu_choice_row_selected_injections_included

#include "../../message/choice_row_selected/shy_choice_row_selected_injections.h"

#include "./shy_choice_row_selected.h"

typedef shy_sender_common_logic_main_menu_choice_row_selected so_called_sender_common_logic_main_menu_choice_row_selected ;

#endif
