#ifndef _shy_common_logic_text_prepare_permit_sender_injections_included
#define _shy_common_logic_text_prepare_permit_sender_injections_included

#include "common/logic/text/message/prepare_permit/shy_prepare_permit_injections.h"

#include "./shy_prepare_permit.h"

typedef shy_common_logic_text_prepare_permit_sender so_called_common_logic_text_prepare_permit_sender ;

#endif
