#ifndef _shy_message_common_logic_main_menu_render_injections_included
#define _shy_message_common_logic_main_menu_render_injections_included

#include "./shy_render.h"

typedef shy_message_common_logic_main_menu_render so_called_message_common_logic_main_menu_render ;

#endif
