#ifndef _shy_loadable_consts_reflection_logic_fader_injections_included
#define _shy_loadable_consts_reflection_logic_fader_injections_included

#include "./shy_fader.h"

typedef shy_loadable_consts_reflection_logic_fader so_called_loadable_consts_reflection_logic_fader ;

#endif
