#ifndef _shy_message_common_logic_main_menu_selection_tracking_director_update_injections_included
#define _shy_message_common_logic_main_menu_selection_tracking_director_update_injections_included

#include "./shy_tracking_director_update.h"

typedef shy_message_common_logic_main_menu_selection_tracking_director_update so_called_message_common_logic_main_menu_selection_tracking_director_update ;

#endif
