#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_id_reply_message_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_id_reply_message_injections_included

#include "common/engine/render/type/mesh_id/shy_mesh_id_injections.h"

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_mesh_id_reply.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_id_reply_message so_called_common_logic_main_menu_letters_meshes_mesh_id_reply_message ;

#endif
