#ifndef _shy_loadable_consts_content_module_container_type_injections_included
#define _shy_loadable_consts_content_module_container_type_injections_included

#include "src/loadable/consts/content/module/type/shy_type_injections.h"

#include "./shy_type.h"

typedef shy_loadable_consts_content_module_container_type so_called_loadable_consts_content_module_container_type ;

#endif
