#ifndef _shy_type_platform_sound_directx_buffer_id_injections_included
#define _shy_type_platform_sound_directx_buffer_id_injections_included

#include "./shy_buffer_id.h"

typedef shy_type_platform_sound_directx_buffer_id so_called_type_platform_sound_directx_buffer_id ;

#endif
