#ifndef _shy_sender_common_logic_main_menu_letters_letter_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_letter_request_injections_included

#include "../../message/letter_request/shy_letter_request_injections.h"

#include "./shy_letter_request.h"

typedef shy_sender_common_logic_main_menu_letters_letter_request so_called_sender_common_logic_main_menu_letters_letter_request ;

#endif
