#ifndef _shy_common_logic_main_menu_letters_boundaries_request_sender_injections_included
#define _shy_common_logic_main_menu_letters_boundaries_request_sender_injections_included

#include "common/logic/main_menu/letters/message/boundaries_request/shy_boundaries_request_injections.h"

#include "./shy_boundaries_request.h"

typedef shy_common_logic_main_menu_letters_boundaries_request_sender so_called_common_logic_main_menu_letters_boundaries_request_sender ;

#endif
