#ifndef _shy_macosx_platform_static_array_insider_included
#define _shy_macosx_platform_static_array_insider_included

#include "../platform/shy_static_array_insider.h"
typedef shy_platform_static_array_insider shy_macosx_platform_static_array_insider ;

#endif

