#ifndef _shy_loadable_consts_reflection_logic_main_menu_animation_injections_included
#define _shy_loadable_consts_reflection_logic_main_menu_animation_injections_included

#include "./shy_animation.h"

typedef shy_loadable_consts_reflection_logic_main_menu_animation so_called_loadable_consts_reflection_logic_main_menu_animation ;

#endif
