#ifndef _shy_loadable_consts_content_value_fract_binding_type_injections_included
#define _shy_loadable_consts_content_value_fract_binding_type_injections_included

#include "injections/platform/math/type/num_fract/shy_num_fract.h"

#include "./shy_value_fract_binding.h"

typedef shy_loadable_consts_content_value_fract_binding_type so_called_loadable_consts_content_value_fract_binding_type ;

#endif
