#ifndef _shy_platform_render_opengl_index_buffer_id_type_injections_included
#define _shy_platform_render_opengl_index_buffer_id_type_injections_included

#include "injections/lib/opengl/shy_opengl.h"

#include "./shy_index_buffer_id.h"

typedef shy_platform_render_opengl_index_buffer_id_type so_called_platform_render_opengl_index_buffer_id_type ;

#endif


