#ifndef _shy_type_macosx_platform_render_index_data_injections_included
#define _shy_type_macosx_platform_render_index_data_injections_included

#include "./shy_index_data.h"

typedef shy_type_macosx_platform_render_index_data so_called_type_platform_render_index_data ;

#endif
