#ifndef _shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_reply_injections_included

#include "../../message/mesh_row_col_reply/shy_mesh_row_col_reply_injections.h"

#include "./shy_mesh_row_col_reply.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_reply so_called_sender_common_logic_main_menu_letters_meshes_mesh_row_col_reply ;

#endif
