const so_called_lib_std_string shy_platform_generator_consts :: autogenerated_cpp_file_begin = "// autogenerated file begin\n" ;
const so_called_lib_std_string shy_platform_generator_consts :: autogenerated_cpp_file_end = "// autogenerated file end\n" ;
const so_called_lib_std_string shy_platform_generator_consts :: autogenerated_python_file_begin = "# autogenerated file begin\n" ;
const so_called_lib_std_string shy_platform_generator_consts :: autogenerated_python_file_end = "# autogenerated file end\n" ;
const so_called_lib_std_string shy_platform_generator_consts :: common_folder_path = "../../common/" ;
const so_called_lib_std_string shy_platform_generator_consts :: new_line = "\n" ;
const so_called_lib_std_string shy_platform_generator_consts :: whitespace = " " ;

