#ifndef _shy_type_loadable_consts_content_value_whole_container_injections_included
#define _shy_type_loadable_consts_content_value_whole_container_injections_included

#include "./shy_value_whole_container.h"

typedef shy_type_loadable_consts_content_value_whole_container so_called_type_loadable_consts_content_value_whole_container ;

#endif
