#ifndef _shy_macosx_platform_render_insider_injections_included
#define _shy_macosx_platform_render_insider_injections_included

#include "src/platform/render/opengl/insider/shy_insider_injections.h"
typedef so_called_platform_render_opengl_insider so_called_platform_render_insider ;

#endif

