#ifndef _shy_win_platform_sound_loader_stereo_resource_id_type_injections_included
#define _shy_win_platform_sound_loader_stereo_resource_id_type_injections_included

#include "src/platform/sound/loader/winapi/stereo/resource/id/type/shy_type_injections.h"
typedef so_called_platform_sound_loader_winapi_stereo_resource_id_type so_called_platform_sound_loader_stereo_resource_id_type ;

#endif

