#ifndef _shy_sender_common_logic_text_letter_small_tex_coords_reply_injections_included
#define _shy_sender_common_logic_text_letter_small_tex_coords_reply_injections_included

#include "../../message/letter_small_tex_coords_reply/shy_letter_small_tex_coords_reply_injections.h"

#include "./shy_letter_small_tex_coords_reply.h"

typedef shy_sender_common_logic_text_letter_small_tex_coords_reply so_called_sender_common_logic_text_letter_small_tex_coords_reply ;

#endif
