#ifndef _shy_common_engine_render_mesh_finalize_sender_injections_included
#define _shy_common_engine_render_mesh_finalize_sender_injections_included

#include "common/engine/render/message/mesh_finalize/shy_mesh_finalize_injections.h"

#include "./shy_mesh_finalize.h"

typedef shy_common_engine_render_mesh_finalize_sender so_called_common_engine_render_mesh_finalize_sender ;

#endif

