#ifndef _shy_type_loadable_fsm_content_state_injections_included
#define _shy_type_loadable_fsm_content_state_injections_included

#include "./shy_state.h"

typedef shy_type_loadable_fsm_content_state so_called_type_loadable_fsm_content_state ;

#endif
