#ifndef _shy_message_common_engine_render_texture_unselect_included
#define _shy_message_common_engine_render_texture_unselect_included

class shy_message_common_engine_render_texture_unselect
{
} ;

#endif

