#ifndef _shy_message_common_logic_main_menu_selection_track_reply_injections_included
#define _shy_message_common_logic_main_menu_selection_track_reply_injections_included

#include "./shy_track_reply.h"

typedef shy_message_common_logic_main_menu_selection_track_reply so_called_message_common_logic_main_menu_selection_track_reply ;

#endif
