const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: mesh_color_a ;
const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: mesh_color_b ;
const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: mesh_color_g ;
const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: mesh_color_r ;
const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: mesh_size ;
const so_called_type_platform_math_num_fract shy_common_logic_main_menu_selection_consts :: selected_rect_vertical_scale ;

