#ifndef _shy_common_logic_salutation_letters_animation_transform_reply_message_injections_included
#define _shy_common_logic_salutation_letters_animation_transform_reply_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"
#include "injections/platform/matrix/type/data/shy_data.h"

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_animation_transform_reply_message so_called_common_logic_salutation_letters_animation_transform_reply_message ;

#endif
