// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: color_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: color_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: color_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: color_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: mesh_size = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: time_between_creation = so_called_platform_math :: init_num_fract ( 50 , 1000 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_salutation_letters_meshes_consts :: time_between_destruction = so_called_platform_math :: init_num_fract ( 50 , 1000 ) ;

// autogenerated file end
