// autogenerated file begin

const so_called_type_platform_math_num_fract so_called_common_logic_salutation_letters_meshes_consts :: time_between_creation = so_called_platform_math :: init_num_fract ( 50 , 1000 ) ;

// autogenerated file end
