#ifndef _shy_type_macosx_platform_render_texture_id_injections_included
#define _shy_type_macosx_platform_render_texture_id_injections_included

#include "shy_type_render_texture_id.h"

typedef shy_type_macosx_platform_render_texture_id so_called_type_platform_render_texture_id ;

#endif

