#ifndef _shy_type_macosx_platform_sound_sample_stereo_injections_included
#define _shy_type_macosx_platform_sound_sample_stereo_injections_included

#include "shy_type_sound_sample_stereo.h"

typedef shy_type_macosx_platform_sound_sample_stereo so_called_type_platform_sound_sample_stereo ;

#endif

