#ifndef _shy_macosx_platform_vector_insider_injections_included
#define _shy_macosx_platform_vector_insider_injections_included

#include "../../platform/shy_vector_float_insider_injections.h"
typedef shy_platform_vector_float_insider so_called_platform_vector_insider ;

#endif
