#ifndef _shy_type_macosx_platform_math_const_int_32_injections_included
#define _shy_type_macosx_platform_math_const_int_32_injections_included

#include "../../platform/shy_type_math_int_float_const_int_32_injections.h"
typedef shy_type_platform_math_int_float_const_int_32 so_called_type_platform_math_const_int_32 ;

#endif
