#include "../../injections/shy_type_platform_math_num_fract.h"
#include "../../injections/shy_type_platform_math_num_whole.h"
#include "../../injections/shy_platform_math_insider.h"
#include "../../injections/shy_type_platform_matrix_data.h"
#include "../../injections/shy_platform_matrix_insider.h"
#include "../../injections/shy_platform_consts_insider.h"
#include "../../injections/shy_platform_pointer.h"
#include "../../injections/shy_platform_static_array_insider.h"
#include "../../injections/shy_type_platform_render_index_buffer_id.h"
#include "../../injections/shy_type_platform_render_index_buffer_mapped_data.h"
#include "../../injections/shy_type_platform_render_index_data.h"
#include "../../injections/shy_type_platform_render_texel_data.h"
#include "../../injections/shy_type_platform_render_texture_id.h"
#include "../../injections/shy_type_platform_render_texture_resource_id.h"
#include "../../injections/shy_type_platform_render_vertex_buffer_id.h"
#include "../../injections/shy_type_platform_render_vertex_buffer_mapped_data.h"
#include "../../injections/shy_type_platform_render_vertex_data.h"
#include "../../injections/shy_platform_render.h"

#include "shy_macosx_platform_render_insider.hpp"

