#ifndef _shy_type_macosx_platform_render_vertex_buffer_id_injections_included
#define _shy_type_macosx_platform_render_vertex_buffer_id_injections_included

#include "shy_type_render_vertex_buffer_id.h"

typedef shy_type_macosx_platform_render_vertex_buffer_id so_called_type_platform_render_vertex_buffer_id ;

#endif

