#ifndef _shy_injections_type_platform_render_vertex_buffer_mapped_data_included
#define _shy_injections_type_platform_render_vertex_buffer_mapped_data_included

#ifdef shy_build_for_macosx
    #include "../macosx/platform/shy_type_macosx_platform_render_vertex_buffer_mapped_data_injections.h"
#endif

#endif
