#ifndef _shy_message_common_logic_main_menu_selection_animation_select_start_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_select_start_injections_included

#include "./shy_select_start.h"

typedef shy_message_common_logic_main_menu_selection_animation_select_start so_called_message_common_logic_main_menu_selection_animation_select_start ;

#endif
