#ifndef _shy_sender_common_logic_salutation_letters_text_storage_size_reply_injections_included
#define _shy_sender_common_logic_salutation_letters_text_storage_size_reply_injections_included

#include "../../message/size_reply/shy_size_reply_injections.h"
#include "./shy_size_reply.h"

typedef shy_sender_common_logic_salutation_letters_text_storage_size_reply so_called_sender_common_logic_salutation_letters_text_storage_size_reply ;

#endif
