#ifndef _shy_sender_common_logic_main_menu_selection_mesh_destroy_request_injections_included
#define _shy_sender_common_logic_main_menu_selection_mesh_destroy_request_injections_included

#include "../../message/mesh_destroy_request/shy_mesh_destroy_request_injections.h"

#include "./shy_mesh_destroy_request.h"

typedef shy_sender_common_logic_main_menu_selection_mesh_destroy_request so_called_sender_common_logic_main_menu_selection_mesh_destroy_request ;

#endif
