#ifndef _shy_loadable_fsm_content_action_binding_type_injections_included
#define _shy_loadable_fsm_content_action_binding_type_injections_included

#include "./shy_type.h"

typedef shy_loadable_fsm_content_action_binding_type so_called_loadable_fsm_content_action_binding_type ;

#endif
