#ifndef _shy_common_engine_rasterizer_use_texel_message_injections_included
#define _shy_common_engine_rasterizer_use_texel_message_injections_included

#include "injections/platform/render/type/texel_data/shy_texel_data.h"

#include "./shy_use_texel.h"

typedef shy_common_engine_rasterizer_use_texel_message so_called_common_engine_rasterizer_use_texel_message ;

#endif
