#ifndef _shy_loadable_fsm_content_action_do_container_type_injections_included
#define _shy_loadable_fsm_content_action_do_container_type_injections_included

#include "loadable/fsm/content/type/action_do/shy_action_do_injections.h"

#include "./shy_action_do_container.h"

typedef shy_loadable_fsm_content_action_do_container_type so_called_loadable_fsm_content_action_do_container_type ;

#endif
