#ifndef _shy_type_macosx_platform_render_index_buffer_id_injections_included
#define _shy_type_macosx_platform_render_index_buffer_id_injections_included

#include "platform/render/opengl/type/index_buffer_id/shy_index_buffer_id_injections.h"
typedef so_called_type_platform_render_opengl_index_buffer_id so_called_type_platform_render_index_buffer_id ;

#endif

