#ifndef _shy_loadable_consts_reflection_logic_door_injections_included
#define _shy_loadable_consts_reflection_logic_door_injections_included

#include "./shy_door.h"

typedef shy_loadable_consts_reflection_logic_door so_called_loadable_consts_reflection_logic_door ;

#endif
