#ifndef _shy_loadable_consts_reflection_logic_room_injections_included
#define _shy_loadable_consts_reflection_logic_room_injections_included

#include "./shy_room.h"

typedef shy_loadable_consts_reflection_logic_room so_called_loadable_consts_reflection_logic_room ;

#endif
