#ifndef _shy_common_logic_salutation_letters_animation_layout_transform_checker_injections_included
#define _shy_common_logic_salutation_letters_animation_layout_transform_checker_injections_included

#include "../reply/message/shy_message_injections.h"
#include "../request/message/shy_message_injections.h"

#include "./shy_checker.h"

typedef shy_common_logic_salutation_letters_animation_layout_transform_checker so_called_common_logic_salutation_letters_animation_layout_transform_checker ;

#endif
