#ifndef _shy_loadable_consts_reflection_logic_blanket_animation_injections_included
#define _shy_loadable_consts_reflection_logic_blanket_animation_injections_included

#include "./shy_animation.h"

typedef shy_loadable_consts_reflection_logic_blanket_animation so_called_loadable_consts_reflection_logic_blanket_animation ;

#endif
