#ifndef _shy_message_common_logic_salutation_letters_meshes_generator_generate_finished_injections_included
#define _shy_message_common_logic_salutation_letters_meshes_generator_generate_finished_injections_included

#include "./shy_message.h"

typedef shy_message_common_logic_salutation_letters_meshes_generator_generate_finished so_called_message_common_logic_salutation_letters_meshes_generator_generate_finished ;

#endif
