#ifndef _shy_common_logic_salutation_letters_meshes_storage_mesh_reply_message_injections_included
#define _shy_common_logic_salutation_letters_meshes_storage_mesh_reply_message_injections_included

#include "src/common/engine/render/mesh/id/type/shy_type_injections.h"
#include "src/injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_meshes_storage_mesh_reply_message so_called_common_logic_salutation_letters_meshes_storage_mesh_reply_message ;

#endif
