#ifndef _shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_message_injections_included
#define _shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_message_injections_included

#include "./shy_message.h"

typedef shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_message so_called_common_engine_render_blend_src_alpha_dst_one_minus_alpha_message ;

#endif
