#ifndef _shy_message_common_logic_main_menu_row_chosen_injections_included
#define _shy_message_common_logic_main_menu_row_chosen_injections_included

#include "./shy_row_chosen.h"

typedef shy_message_common_logic_main_menu_row_chosen so_called_message_common_logic_main_menu_row_chosen ;

#endif
