#ifndef _shy_common_logic_main_menu_row_chosen_message_injections_included
#define _shy_common_logic_main_menu_row_chosen_message_injections_included

#include "./shy_row_chosen.h"

typedef shy_common_logic_main_menu_row_chosen_message so_called_common_logic_main_menu_row_chosen_message ;

#endif
