#ifndef _shy_common_engine_render_enable_face_culling_sender_injections_included
#define _shy_common_engine_render_enable_face_culling_sender_injections_included

#include "src/common/engine/render/enable/face/culling/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_render_enable_face_culling_sender so_called_common_engine_render_enable_face_culling_sender ;

#endif

