#ifndef _shy_common_engine_render_texture_mode_modulate_sender_injections_included
#define _shy_common_engine_render_texture_mode_modulate_sender_injections_included

#include "../../message/texture_mode_modulate/shy_texture_mode_modulate_injections.h"

#include "./shy_texture_mode_modulate.h"

typedef shy_common_engine_render_texture_mode_modulate_sender so_called_common_engine_render_texture_mode_modulate_sender ;

#endif

