#ifndef _shy_common_logic_perspective_planes_reply_sender_injections_included
#define _shy_common_logic_perspective_planes_reply_sender_injections_included

#include "common/logic/perspective/message/planes_reply/shy_planes_reply_injections.h"

#include "./shy_planes_reply.h"

typedef shy_common_logic_perspective_planes_reply_sender so_called_common_logic_perspective_planes_reply_sender ;

#endif
