#ifndef _shy_sender_common_logic_observer_animation_flight_transform_request_injections_included
#define _shy_sender_common_logic_observer_animation_flight_transform_request_injections_included

#include "../../message/flight_transform_request/shy_flight_transform_request_injections.h"

#include "./shy_flight_transform_request.h"

typedef shy_sender_common_logic_observer_animation_flight_transform_request so_called_sender_common_logic_observer_animation_flight_transform_request ;

#endif
