#ifndef _shy_loadable_fsm_content_condition_group_type_injections_included
#define _shy_loadable_fsm_content_condition_group_type_injections_included

#include "loadable/fsm/content/type/condition_command_container/shy_condition_command_container_injections.h"
#include "loadable/fsm/content/type/condition_input_container/shy_condition_input_container_injections.h"
#include "loadable/fsm/content/type/condition_state_container/shy_condition_state_container_injections.h"

#include "./shy_condition_group.h"

typedef shy_loadable_fsm_content_condition_group_type so_called_loadable_fsm_content_condition_group_type ;

#endif
