#ifndef _shy_macosx_platform_render_texture_loader_injections_included
#define _shy_macosx_platform_render_texture_loader_injections_included

#include "src/platform/render/texture/loader/cocoa/shy_cocoa_injections.h"
typedef so_called_platform_render_texture_loader_cocoa so_called_platform_render_texture_loader ;

#endif

