#ifndef _shy_common_logic_main_menu_selection_animation_disappear_start_sender_injections_included
#define _shy_common_logic_main_menu_selection_animation_disappear_start_sender_injections_included

#include "common/logic/main_menu/selection/animation/message/disappear_start/shy_disappear_start_injections.h"

#include "./shy_disappear_start.h"

typedef shy_common_logic_main_menu_selection_animation_disappear_start_sender so_called_common_logic_main_menu_selection_animation_disappear_start_sender ;

#endif
