#ifndef _shy_loadable_consts_content_value_whole_binding_type_injections_included
#define _shy_loadable_consts_content_value_whole_binding_type_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_value_whole_binding.h"

typedef shy_loadable_consts_content_value_whole_binding_type so_called_loadable_consts_content_value_whole_binding_type ;

#endif
