#ifndef _shy_type_loadable_consts_content_value_whole_binding_injections_included
#define _shy_type_loadable_consts_content_value_whole_binding_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_value_whole_binding.h"

typedef shy_type_loadable_consts_content_value_whole_binding so_called_type_loadable_consts_content_value_whole_binding ;

#endif
