#ifndef _shy_iphone_platform_vector_insider_injections_included
#define _shy_iphone_platform_vector_insider_injections_included

#include "src/platform/vector/float/insider/shy_insider_injections.h"
typedef so_called_platform_vector_float_insider so_called_platform_vector_insider ;

#endif
