#ifndef _shy_loadable_fsm_content_condition_state_type_injections_included
#define _shy_loadable_fsm_content_condition_state_type_injections_included

#include "./shy_type.h"

typedef shy_loadable_fsm_content_condition_state_type so_called_loadable_fsm_content_condition_state_type ;

#endif
