#include "./shy_title_injections.h"

#include "common/logic/title/consts/shy_consts_injections.h"
#include "common/logic/title/created/sender/shy_sender_injections.h"
#include "common/logic/title/finished/sender/shy_sender_injections.h"

#include "common/logic/core/use/ortho/projection/request/sender/shy_sender_injections.h"
#include "common/logic/fidget/render/request/sender/shy_sender_injections.h"
#include "common/logic/text/consts/shy_consts_injections.h"
#include "common/logic/text/letter/big/tex/coords/request/sender/shy_sender_injections.h"
#include "common/logic/text/use/text/texture/request/sender/shy_sender_injections.h"
#include "common/logic/text/stateless/shy_stateless_injections.h"

#include "common/engine/math/stateless/shy_stateless_injections.h"
#include "common/engine/render/aspect/request/sender/shy_sender_injections.h"
#include "common/engine/render/blend/disable/sender/shy_sender_injections.h"
#include "common/engine/render/blend/src/alpha/dst/one/minus/alpha/sender/shy_sender_injections.h"
#include "common/engine/render/clear/screen/sender/shy_sender_injections.h"
#include "common/engine/render/disable/depth/test/sender/shy_sender_injections.h"
#include "common/engine/render/fog/disable/sender/shy_sender_injections.h"
#include "common/engine/render/matrix/load/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/create/request/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/delete/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/finalize/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/render/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/transform/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/triangle/strip/index/value/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/color/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/position/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/set/vertex/tex/coord/sender/shy_sender_injections.h"

#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"
#include "injections/platform/matrix/shy_matrix.h"
#include "injections/platform/pointer/data/type/shy_type.h"
#include "injections/platform/static/array/shy_array.h"
#include "injections/platform/static/array/data/type/shy_type.h"
#include "injections/platform/vector/shy_vector.h"

#include "./shy_title.hpp"

