#include "./shy_title_injections.h"

#include "./consts/shy_consts_injections.h"
#include "./sender/created/shy_created_injections.h"
#include "./sender/finished/shy_finished_injections.h"

#include "../core/sender/use_ortho_projection_request/shy_use_ortho_projection_request_injections.h"
#include "../fidget/sender/render_request/shy_render_request_injections.h"
#include "../text/consts/shy_consts_injections.h"
#include "../text/sender/letter_big_tex_coords_request/shy_letter_big_tex_coords_request_injections.h"
#include "../text/sender/use_text_texture_request/shy_use_text_texture_request_injections.h"
#include "../text/stateless/shy_stateless_injections.h"

#include "../../engine/math/stateless/shy_stateless_injections.h"
#include "../../engine/render/sender/aspect_request/shy_aspect_request_injections.h"
#include "../../engine/render/sender/blend_disable/shy_blend_disable_injections.h"
#include "../../engine/render/sender/blend_src_alpha_dst_one_minus_alpha/shy_blend_src_alpha_dst_one_minus_alpha_injections.h"
#include "../../engine/render/sender/clear_screen/shy_clear_screen_injections.h"
#include "../../engine/render/sender/disable_depth_test/shy_disable_depth_test_injections.h"
#include "../../engine/render/sender/fog_disable/shy_fog_disable_injections.h"
#include "../../engine/render/sender/matrix_load/shy_matrix_load_injections.h"
#include "../../engine/render/sender/mesh_create_request/shy_mesh_create_request_injections.h"
#include "../../engine/render/sender/mesh_delete/shy_mesh_delete_injections.h"
#include "../../engine/render/sender/mesh_finalize/shy_mesh_finalize_injections.h"
#include "../../engine/render/sender/mesh_render/shy_mesh_render_injections.h"
#include "../../engine/render/sender/mesh_set_transform/shy_mesh_set_transform_injections.h"
#include "../../engine/render/sender/mesh_set_triangle_strip_index_value/shy_mesh_set_triangle_strip_index_value_injections.h"
#include "../../engine/render/sender/mesh_set_vertex_color/shy_mesh_set_vertex_color_injections.h"
#include "../../engine/render/sender/mesh_set_vertex_position/shy_mesh_set_vertex_position_injections.h"
#include "../../engine/render/sender/mesh_set_vertex_tex_coord/shy_mesh_set_vertex_tex_coord_injections.h"

#include "../../../injections/platform/conditions/shy_conditions.h"
#include "../../../injections/platform/math/consts/shy_consts.h"
#include "../../../injections/platform/math/shy_math.h"
#include "../../../injections/platform/matrix/shy_matrix.h"
#include "../../../injections/platform/pointer/type/data/shy_data.h"
#include "../../../injections/platform/static_array/shy_static_array.h"
#include "../../../injections/platform/static_array/type/data/shy_data.h"
#include "../../../injections/platform/vector/shy_vector.h"

#include "./shy_title.hpp"

