#ifndef _shy_macosx_platform_sound_insider_injections_included
#define _shy_macosx_platform_sound_insider_injections_included

#include "./shy_insider.h"

typedef shy_macosx_platform_sound_insider so_called_platform_sound_insider ;

#endif
