#ifndef _shy_common_logic_salutation_letters_animation_layout_transform_request_sender_injections_included
#define _shy_common_logic_salutation_letters_animation_layout_transform_request_sender_injections_included

#include "src/common/logic/salutation/letters/animation/layout/transform/request/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_animation_layout_transform_request_sender so_called_common_logic_salutation_letters_animation_layout_transform_request_sender ;

#endif
