#ifndef _shy_common_engine_render_mesh_set_triangle_fan_index_value_message_injections_included
#define _shy_common_engine_render_mesh_set_triangle_fan_index_value_message_injections_included

#include "src/common/engine/render/mesh/id/type/shy_type_injections.h"

#include "./shy_message.h"

typedef shy_common_engine_render_mesh_set_triangle_fan_index_value_message so_called_common_engine_render_mesh_set_triangle_fan_index_value_message ;

#endif
