#ifndef _shy_common_logic_observer_animation_flight_transform_reply_sender_injections_included
#define _shy_common_logic_observer_animation_flight_transform_reply_sender_injections_included

#include "common/logic/observer/animation/message/flight_transform_reply/shy_flight_transform_reply_injections.h"

#include "./shy_flight_transform_reply.h"

typedef shy_common_logic_observer_animation_flight_transform_reply_sender so_called_common_logic_observer_animation_flight_transform_reply_sender ;

#endif
