#ifndef _shy_macosx_platform_render_texture_id_type_injections_included
#define _shy_macosx_platform_render_texture_id_type_injections_included

#include "platform/render/opengl/type/texture_id/shy_texture_id_injections.h"
typedef so_called_platform_render_opengl_texture_id_type so_called_platform_render_texture_id_type ;

#endif
