#ifndef _shy_common_logic_main_menu_letters_rows_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_rows_reply_sender_injections_included

#include "common/logic/main_menu/letters/message/rows_reply/shy_rows_reply_injections.h"

#include "./shy_rows_reply.h"

typedef shy_common_logic_main_menu_letters_rows_reply_sender so_called_common_logic_main_menu_letters_rows_reply_sender ;

#endif
