// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: animation_origin_x = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: animation_origin_y = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: animation_origin_z = so_called_platform_math :: init_num_fract ( - 3 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: appear_scale_begin = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: appear_scale_end = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_animation_consts :: appear_time_from_begin_to_end = so_called_platform_math :: init_num_fract ( 2 , 1 ) ;

// autogenerated file end
