#ifndef _shy_platform_render_texture_loader_cocoa_resource_id_type_injections_included
#define _shy_platform_render_texture_loader_cocoa_resource_id_type_injections_included

#include "src/injections/lib/std/int32/t/shy_t.h"
#include "./shy_type.h"

typedef shy_platform_render_texture_loader_cocoa_resource_id_type so_called_platform_render_texture_loader_cocoa_resource_id_type ;

#endif
