#ifndef _shy_type_macosx_platform_sound_loader_stereo_resource_id_injections_included
#define _shy_type_macosx_platform_sound_loader_stereo_resource_id_injections_included

#include "platform/sound/loader/cocoa/type/stereo_resource_id/shy_stereo_resource_id_injections.h"
typedef so_called_type_platform_sound_loader_cocoa_stereo_resource_id so_called_type_platform_sound_loader_stereo_resource_id ;

#endif

