#ifndef _shy_loadable_consts_reflection_logic_door_animation_injections_included
#define _shy_loadable_consts_reflection_logic_door_animation_injections_included

#include "./shy_animation.h"

typedef shy_loadable_consts_reflection_logic_door_animation so_called_loadable_consts_reflection_logic_door_animation ;

#endif
