// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_color_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_color_b = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_color_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_color_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_u_bottom_left = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_u_bottom_right = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_u_top_left = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_u_top_right = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_v_bottom_left = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_v_bottom_right = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_v_top_left = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_v_top_right = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_x_left = so_called_platform_math :: init_num_fract ( - 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_x_right = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_y_bottom = so_called_platform_math :: init_num_fract ( - 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_y_top = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: mesh_z = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_paper_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_paper_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_paper_g = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_paper_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_pen_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_pen_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_pen_g = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_door_consts :: texture_pen_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_door_consts :: texture_stripes = so_called_platform_math :: init_num_whole ( 9 ) ;

// autogenerated file end
