#ifndef _shy_iphone_platform_render_index_buffer_id_type_injections_included
#define _shy_iphone_platform_render_index_buffer_id_type_injections_included

#include "platform/render/opengl/type/index_buffer_id/shy_index_buffer_id_injections.h"
typedef so_called_platform_render_opengl_index_buffer_id_type so_called_platform_render_index_buffer_id_type ;

#endif

