// autogenerated file begin

const so_called_type_platform_math_num_fract so_called_common_logic_ortho_consts :: z_far = so_called_platform_math :: init_num_fract ( 50 , 1 ) ;
const so_called_type_platform_math_num_fract so_called_common_logic_ortho_consts :: z_near = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;

// autogenerated file end
