#ifndef _shy_type_platform_render_directx_vertex_buffer_id_injections_included
#define _shy_type_platform_render_directx_vertex_buffer_id_injections_included

#include "injections/lib/directx/shy_directx.h"

#include "./shy_vertex_buffer_id.h"

typedef shy_type_platform_render_directx_vertex_buffer_id so_called_type_platform_render_directx_vertex_buffer_id ;

#endif
