#include "./shy_consts_injections.h"

#ifdef shy_build_static_way
    #include "../../../autogenerated/logic_amusement_consts/shy_logic_amusement_consts_injections.hpp"
#endif

#ifdef shy_build_loadable_way
    #include "./shy_consts.hpp"
#endif
