#ifndef _shy_type_loadable_consts_content_value_fract_injections_included
#define _shy_type_loadable_consts_content_value_fract_injections_included

#include "./shy_value_fract.h"

typedef shy_type_loadable_consts_content_value_fract so_called_type_loadable_consts_content_value_fract ;

#endif
