// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_color_a = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_color_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_color_g = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_color_r = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_vertex_x_left = so_called_platform_math :: init_num_fract ( - 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_vertex_x_right = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_vertex_y_bottom = so_called_platform_math :: init_num_fract ( - 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_vertex_y_top = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_blanket_consts :: mesh_vertex_z = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;

// autogenerated file end
