#ifndef _shy_message_common_logic_ortho_planes_request_injections_included
#define _shy_message_common_logic_ortho_planes_request_injections_included

#include "./shy_planes_request.h"

typedef shy_message_common_logic_ortho_planes_request so_called_message_common_logic_ortho_planes_request ;

#endif
