#ifndef _shy_common_engine_render_texture_load_from_resource_sender_injections_included
#define _shy_common_engine_render_texture_load_from_resource_sender_injections_included

#include "common/engine/render/message/texture_load_from_resource/shy_texture_load_from_resource_injections.h"

#include "./shy_texture_load_from_resource.h"

typedef shy_common_engine_render_texture_load_from_resource_sender so_called_common_engine_render_texture_load_from_resource_sender ;

#endif

