#ifndef _shy_type_loadable_fsm_content_condition_state_container_injections_included
#define _shy_type_loadable_fsm_content_condition_state_container_injections_included

#include "../condition_state/shy_condition_state_injections.h"

#include "./shy_condition_state_container.h"

typedef shy_type_loadable_fsm_content_condition_state_container so_called_type_loadable_fsm_content_condition_state_container ;

#endif
