#ifndef _shy_common_engine_render_texture_load_from_resource_message_injections_included
#define _shy_common_engine_render_texture_load_from_resource_message_injections_included

#include "common/engine/render/type/texture_id/shy_texture_id_injections.h"
#include "injections/platform/render/texture_loader/type/resource_id/shy_resource_id.h"

#include "./shy_texture_load_from_resource.h"

typedef shy_common_engine_render_texture_load_from_resource_message so_called_common_engine_render_texture_load_from_resource_message ;

#endif
