#ifndef _shy_macosx_platform_vector_profile_injections_included
#define _shy_macosx_platform_vector_profile_injections_included

#include "src/profile/platform/vector/shy_vector_injections.h"

#endif
