#ifndef _shy_sender_common_logic_main_menu_selection_track_reply_injections_included
#define _shy_sender_common_logic_main_menu_selection_track_reply_injections_included

#include "../../message/track_reply/shy_track_reply_injections.h"

#include "./shy_track_reply.h"

typedef shy_sender_common_logic_main_menu_selection_track_reply so_called_sender_common_logic_main_menu_selection_track_reply ;

#endif
