#ifndef _shy_common_engine_render_texture_loader_ready_reply_sender_injections_included
#define _shy_common_engine_render_texture_loader_ready_reply_sender_injections_included

#include "../../message/texture_loader_ready_reply/shy_texture_loader_ready_reply_injections.h"

#include "./shy_texture_loader_ready_reply.h"

typedef shy_common_engine_render_texture_loader_ready_reply_sender so_called_common_engine_render_texture_loader_ready_reply_sender ;

#endif

