#ifndef _shy_sender_common_engine_render_texture_loader_ready_reply_injections_included
#define _shy_sender_common_engine_render_texture_loader_ready_reply_injections_included

#include "../../message/texture_loader_ready_reply/shy_texture_loader_ready_reply_injections.h"

#include "./shy_texture_loader_ready_reply.h"

typedef shy_sender_common_engine_render_texture_loader_ready_reply so_called_sender_common_engine_render_texture_loader_ready_reply ;

#endif

