#ifndef _shy_message_common_logic_salutation_letters_animation_layout_transform_reply_injections_included
#define _shy_message_common_logic_salutation_letters_animation_layout_transform_reply_injections_included

#include "injections/platform/math/type/num_fract/shy_num_fract.h"
#include "injections/platform/math/type/num_whole/shy_num_whole.h"
#include "injections/platform/vector/type/data/shy_data.h"

#include "./shy_message.h"

typedef shy_message_common_logic_salutation_letters_animation_layout_transform_reply so_called_message_common_logic_salutation_letters_animation_layout_transform_reply ;

#endif
