#ifndef _shy_common_engine_render_enable_depth_test_message_injections_included
#define _shy_common_engine_render_enable_depth_test_message_injections_included

#include "./shy_enable_depth_test.h"

typedef shy_common_engine_render_enable_depth_test_message so_called_common_engine_render_enable_depth_test_message ;

#endif
