#ifndef _shy_type_macosx_platform_render_texture_loader_resource_id_injections_included
#define _shy_type_macosx_platform_render_texture_loader_resource_id_injections_included

#include "platform/render/texture_loader/cocoa/type/resource_id/shy_resource_id_injections.h"
typedef so_called_type_platform_render_texture_loader_cocoa_resource_id so_called_type_platform_render_texture_loader_resource_id ;

#endif
