#ifndef _shy_sender_common_logic_main_menu_letters_animation_unselection_weight_select_row_injections_included
#define _shy_sender_common_logic_main_menu_letters_animation_unselection_weight_select_row_injections_included

#include "../../message/unselection_weight_select_row/shy_unselection_weight_select_row_injections.h"

#include "./shy_unselection_weight_select_row.h"

typedef shy_sender_common_logic_main_menu_letters_animation_unselection_weight_select_row so_called_sender_common_logic_main_menu_letters_animation_unselection_weight_select_row ;

#endif
