#ifndef _shy_type_win_platform_math_num_whole_injections_included
#define _shy_type_win_platform_math_num_whole_injections_included

#include "platform/math/int_float/type/num_whole/shy_num_whole_injections.h"
typedef so_called_type_platform_math_int_float_num_whole so_called_type_platform_math_num_whole ;

#endif

