#include "./shy_renderer_injections.h"

#include "./sender/render_reply/shy_render_reply_injections.h"
#include "../animation/sender/transform_request/shy_transform_request_injections.h"
#include "../meshes/storage/mesh/checker/shy_checker_injections.h"
#include "../meshes/storage/sender/mesh_request/shy_mesh_request_injections.h"
#include "../meshes/storage/sender/size_request/shy_size_request_injections.h"
#include "../meshes/storage/size/checker/shy_checker_injections.h"
#include "../../../../engine/render/sender/mesh_render/shy_mesh_render_injections.h"
#include "../../../../engine/render/sender/mesh_set_transform/shy_mesh_set_transform_injections.h"
#include "../../../../engine/taker/helper/shy_helper_injections.h"
#include "../../../../../injections/platform/conditions/shy_conditions.h"
#include "../../../../../injections/platform/math/consts/shy_consts.h"
#include "../../../../../injections/platform/math/shy_math.h"

#include "./shy_renderer.hpp"
