#include "./shy_renderer_injections.h"

#include "src/common/engine/render/mesh/render/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/transform/sender/shy_sender_injections.h"
#include "src/common/engine/taker/helper/shy_helper_injections.h"
#include "src/common/logic/salutation/letters/animation/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/mesh/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/mesh/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/size/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/size/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/renderer/render/reply/sender/shy_sender_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"

#include "./shy_renderer.hpp"
