#include "./shy_renderer_injections.h"

#include "common/engine/render/sender/mesh_render/shy_mesh_render_injections.h"
#include "common/engine/render/sender/mesh_set_transform/shy_mesh_set_transform_injections.h"
#include "common/engine/taker/helper/shy_helper_injections.h"
#include "common/logic/salutation/letters/animation/transform/checker/shy_checker_injections.h"
#include "common/logic/salutation/letters/animation/transform/request/sender/shy_sender_injections.h"
#include "common/logic/salutation/letters/meshes/storage/mesh/checker/shy_checker_injections.h"
#include "common/logic/salutation/letters/meshes/storage/mesh/request/sender/shy_sender_injections.h"
#include "common/logic/salutation/letters/meshes/storage/size/checker/shy_checker_injections.h"
#include "common/logic/salutation/letters/meshes/storage/size/request/sender/shy_sender_injections.h"
#include "common/logic/salutation/letters/renderer/render/reply/sender/shy_sender_injections.h"
#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"

#include "./shy_renderer.hpp"
