#ifndef _shy_common_logic_main_menu_selection_animation_select_start_message_injections_included
#define _shy_common_logic_main_menu_selection_animation_select_start_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_main_menu_selection_animation_select_start_message so_called_common_logic_main_menu_selection_animation_select_start_message ;

#endif
