#ifndef _shy_common_logic_text_use_text_texture_request_sender_injections_included
#define _shy_common_logic_text_use_text_texture_request_sender_injections_included

#include "../../message/use_text_texture_request/shy_use_text_texture_request_injections.h"

#include "./shy_use_text_texture_request.h"

typedef shy_common_logic_text_use_text_texture_request_sender so_called_common_logic_text_use_text_texture_request_sender ;

#endif
