#ifndef _shy_sender_common_logic_text_use_text_texture_request_injections_included
#define _shy_sender_common_logic_text_use_text_texture_request_injections_included

#include "../../message/use_text_texture_request/shy_use_text_texture_request_injections.h"

#include "./shy_use_text_texture_request.h"

typedef shy_sender_common_logic_text_use_text_texture_request so_called_sender_common_logic_text_use_text_texture_request ;

#endif
