#include "./shy_storage_injections.h"

#include "./letter/reply/sender/shy_sender_injections.h"
#include "./size/reply/sender/shy_sender_injections.h"
#include "../../consts/shy_consts_injections.h"
#include "../../../../text/consts/shy_consts_injections.h"
#include "../../../../../../injections/lib/std/true/shy_true.h"
#include "../../../../../../injections/platform/conditions/shy_conditions.h"
#include "../../../../../../injections/platform/math/consts/shy_consts.h"
#include "../../../../../../injections/platform/math/shy_math.h"
#include "../../../../../../injections/platform/pointer/shy_pointer.h"
#include "../../../../../../injections/platform/pointer/type/data/shy_data.h"
#include "../../../../../../injections/platform/static_array/shy_static_array.h"
#include "../../../../../../injections/platform/static_array/type/data/shy_data.h"
#include "../../../../../../trace/common/logic/salutation/letters/text/storage/shy_storage_injections.h"
#include "../../../../../../trace/shy_trace_injections.h"

#include "./shy_storage.hpp"
