void shy_loadable_consts_reflection :: prepare ( )
{
    so_called_loadable_consts_reflection_logic_amusement :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_application :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_blanket :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_blanket_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_door :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_door_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_fader :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_fidget :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_font_mesh :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_font_texture :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_letters_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_letters_layout :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_letters_meshes :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_selection :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_main_menu_selection_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_observer_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_ortho :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_perspective :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_room :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_salutation_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_salutation_letters_animation :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_salutation_letters_meshes :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_salutation_renderer :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_salutation_timer :: prepare ( ) ;
    so_called_loadable_consts_reflection_logic_vacuum :: prepare ( ) ;
}
