#ifndef _shy_sender_common_logic_main_menu_selection_animation_appear_finished_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_appear_finished_injections_included

#include "../../message/appear_finished/shy_appear_finished_injections.h"

#include "./shy_appear_finished.h"

typedef shy_sender_common_logic_main_menu_selection_animation_appear_finished so_called_sender_common_logic_main_menu_selection_animation_appear_finished ;

#endif
