#ifndef _shy_loadable_consts_reflection_logic_fidget_injections_included
#define _shy_loadable_consts_reflection_logic_fidget_injections_included

#include "./shy_fidget.h"

typedef shy_loadable_consts_reflection_logic_fidget so_called_loadable_consts_reflection_logic_fidget ;

#endif
