#ifndef _shy_type_platform_math_int_float_const_int_32_included
#define _shy_type_platform_math_int_float_const_int_32_included

typedef const int shy_type_platform_math_int_float_const_int_32 ;

#endif
