#ifndef _shy_message_common_logic_salutation_animation_transform_request_injections_included
#define _shy_message_common_logic_salutation_animation_transform_request_injections_included

#include "./shy_transform_request.h"

typedef shy_message_common_logic_salutation_animation_transform_request so_called_message_common_logic_salutation_animation_transform_request ;

#endif
