#ifndef _shy_macosx_platform_static_array_profile_injections_included
#define _shy_macosx_platform_static_array_profile_injections_included

#include "src/profile/platform/static/array/shy_array_injections.h"

#endif
