#ifndef _shy_message_common_logic_main_menu_selection_animation_unselect_finished_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_unselect_finished_injections_included

#include "./shy_unselect_finished.h"

typedef shy_message_common_logic_main_menu_selection_animation_unselect_finished so_called_message_common_logic_main_menu_selection_animation_unselect_finished ;

#endif
