#ifndef _shy_message_common_logic_controls_state_request_injections_included
#define _shy_message_common_logic_controls_state_request_injections_included

#include "./shy_state_request.h"

typedef shy_message_common_logic_controls_state_request so_called_message_common_logic_controls_state_request ;

#endif
