#ifndef _shy_common_logic_salutation_timer_disappear_finished_sender_injections_included
#define _shy_common_logic_salutation_timer_disappear_finished_sender_injections_included

#include "src/common/logic/salutation/timer/disappear/finished/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_timer_disappear_finished_sender so_called_common_logic_salutation_timer_disappear_finished_sender ;

#endif
