#ifndef _shy_sender_common_logic_main_menu_letters_letter_add_injections_included
#define _shy_sender_common_logic_main_menu_letters_letter_add_injections_included

#include "../../message/letter_add/shy_letter_add_injections.h"

#include "./shy_letter_add.h"

typedef shy_sender_common_logic_main_menu_letters_letter_add so_called_sender_common_logic_main_menu_letters_letter_add ;

#endif
