#ifndef _shy_common_logic_main_menu_letters_letter_add_sender_injections_included
#define _shy_common_logic_main_menu_letters_letter_add_sender_injections_included

#include "common/logic/main_menu/letters/message/letter_add/shy_letter_add_injections.h"

#include "./shy_letter_add.h"

typedef shy_common_logic_main_menu_letters_letter_add_sender so_called_common_logic_main_menu_letters_letter_add_sender ;

#endif
