#ifndef _shy_common_engine_render_texture_set_texel_sender_injections_included
#define _shy_common_engine_render_texture_set_texel_sender_injections_included

#include "../../message/texture_set_texel/shy_texture_set_texel_injections.h"

#include "./shy_texture_set_texel.h"

typedef shy_common_engine_render_texture_set_texel_sender so_called_common_engine_render_texture_set_texel_sender ;

#endif

