#ifndef _shy_sender_common_logic_main_menu_selection_animation_push_attention_transform_request_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_push_attention_transform_request_injections_included

#include "../../message/push_attention_transform_request/shy_push_attention_transform_request_injections.h"

#include "./shy_push_attention_transform_request.h"

typedef shy_sender_common_logic_main_menu_selection_animation_push_attention_transform_request so_called_sender_common_logic_main_menu_selection_animation_push_attention_transform_request ;

#endif
