#ifndef _shy_common_logic_salutation_letters_meshes_storage_size_request_message_injections_included
#define _shy_common_logic_salutation_letters_meshes_storage_size_request_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_meshes_storage_size_request_message so_called_common_logic_salutation_letters_meshes_storage_size_request_message ;

#endif
