#ifndef _shy_win_platform_sound_buffer_id_type_injections_included
#define _shy_win_platform_sound_buffer_id_type_injections_included

#include "src/platform/sound/directx/buffer/id/type/shy_type_injections.h"
typedef so_called_platform_sound_directx_buffer_id_type so_called_platform_sound_buffer_id_type ;

#endif

