#ifndef _shy_sender_common_logic_main_menu_letters_meshes_creation_finished_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_creation_finished_injections_included

#include "../../message/creation_finished/shy_creation_finished_injections.h"

#include "./shy_creation_finished.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_creation_finished so_called_sender_common_logic_main_menu_letters_meshes_creation_finished ;

#endif
