#ifndef _shy_iphone_platform_sound_loader_insider_injections_included
#define _shy_iphone_platform_sound_loader_insider_injections_included

#include "./shy_insider.h"

typedef shy_iphone_platform_sound_loader_insider so_called_platform_sound_loader_insider ;

#endif

