#ifndef _shy_sender_common_logic_main_menu_letters_layout_row_rect_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_layout_row_rect_request_injections_included

#include "../../message/row_rect_request/shy_row_rect_request_injections.h"

#include "./shy_row_rect_request.h"

typedef shy_sender_common_logic_main_menu_letters_layout_row_rect_request so_called_sender_common_logic_main_menu_letters_layout_row_rect_request ;

#endif
