#ifndef _shy_common_logic_blanket_animation_transform_reply_sender_injections_included
#define _shy_common_logic_blanket_animation_transform_reply_sender_injections_included

#include "common/logic/blanket/animation/message/transform_reply/shy_transform_reply_injections.h"

#include "./shy_transform_reply.h"

typedef shy_common_logic_blanket_animation_transform_reply_sender so_called_common_logic_blanket_animation_transform_reply_sender ;

#endif
