#ifndef _shy_iphone_platform_math_insider_injections_included
#define _shy_iphone_platform_math_insider_injections_included

#include "src/platform/math/int/float/insider/shy_insider_injections.h"
typedef so_called_platform_math_int_float_insider so_called_platform_math_insider ;

#endif
