#include "./shy_cleaner_injections.h"

#include "./clean/finished/sender/shy_sender_injections.h"
#include "../consts/shy_consts_injections.h"
#include "../storage/clean/sender/shy_sender_injections.h"
#include "../storage/mesh/checker/shy_checker_injections.h"
#include "../storage/mesh/request/sender/shy_sender_injections.h"
#include "../storage/size/checker/shy_checker_injections.h"
#include "../storage/size/request/sender/shy_sender_injections.h"
#include "../../../../../engine/render/sender/mesh_delete/shy_mesh_delete_injections.h"
#include "../../../../../engine/render/type/mesh_id/shy_mesh_id_injections.h"
#include "../../../../../engine/taker/helper/shy_helper_injections.h"
#include "../../../../../../injections/platform/conditions/shy_conditions.h"
#include "../../../../../../injections/platform/consts/shy_consts.h"
#include "../../../../../../injections/platform/math/consts/shy_consts.h"
#include "../../../../../../injections/platform/math/shy_math.h"

#include "./shy_cleaner.hpp"
