#ifndef _shy_loadable_consts_reflection_logic_font_texture_injections_included
#define _shy_loadable_consts_reflection_logic_font_texture_injections_included

#include "./shy_texture.h"

typedef shy_loadable_consts_reflection_logic_font_texture so_called_loadable_consts_reflection_logic_font_texture ;

#endif
