#ifndef _shy_common_engine_rasterizer_draw_triangle_sender_injections_included
#define _shy_common_engine_rasterizer_draw_triangle_sender_injections_included

#include "src/common/engine/rasterizer/draw/triangle/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_rasterizer_draw_triangle_sender so_called_common_engine_rasterizer_draw_triangle_sender ;

#endif
