#ifndef _shy_loadable_consts_reflection_logic_amusement_injections_included
#define _shy_loadable_consts_reflection_logic_amusement_injections_included

#include "./shy_amusement.h"

typedef shy_loadable_consts_reflection_logic_amusement so_called_loadable_consts_reflection_logic_amusement ;

#endif
