#ifndef _shy_win_lib_directx_injections_included
#define _shy_win_lib_directx_injections_included

#include "src/main/win/DXUT/Core/DXUT.h"

#define so_called_lib_directx_D3DBLEND_INVSRCALPHA D3DBLEND_INVSRCALPHA
#define so_called_lib_directx_D3DBLEND_SRCALPHA D3DBLEND_SRCALPHA
#define so_called_lib_directx_D3DCLEAR_TARGET D3DCLEAR_TARGET
#define so_called_lib_directx_D3DCLEAR_ZBUFFER D3DCLEAR_ZBUFFER
#define so_called_lib_directx_D3DCOLOR_ARGB D3DCOLOR_ARGB
#define so_called_lib_directx_D3DCULL_NONE D3DCULL_NONE
#define so_called_lib_directx_D3DFMT_A8R8G8B8 D3DFMT_A8R8G8B8
#define so_called_lib_directx_D3DFMT_INDEX32 D3DFMT_INDEX32
#define so_called_lib_directx_D3DFOG_LINEAR D3DFOG_LINEAR
#define so_called_lib_directx_D3DFVF_DIFFUSE D3DFVF_DIFFUSE
#define so_called_lib_directx_D3DFVF_TEX1 D3DFVF_TEX1
#define so_called_lib_directx_D3DFVF_XYZ D3DFVF_XYZ
#define so_called_lib_directx_D3DPOOL_MANAGED D3DPOOL_MANAGED
#define so_called_lib_directx_D3DPT_TRIANGLEFAN D3DPT_TRIANGLEFAN
#define so_called_lib_directx_D3DPT_TRIANGLESTRIP D3DPT_TRIANGLESTRIP
#define so_called_lib_directx_D3DRS_ALPHABLENDENABLE D3DRS_ALPHABLENDENABLE
#define so_called_lib_directx_D3DRS_CULLMODE D3DRS_CULLMODE
#define so_called_lib_directx_D3DRS_DESTBLEND D3DRS_DESTBLEND 
#define so_called_lib_directx_D3DRS_FOGCOLOR D3DRS_FOGCOLOR 
#define so_called_lib_directx_D3DRS_FOGENABLE D3DRS_FOGENABLE
#define so_called_lib_directx_D3DRS_FOGEND D3DRS_FOGEND 
#define so_called_lib_directx_D3DRS_FOGSTART D3DRS_FOGSTART 
#define so_called_lib_directx_D3DRS_FOGVERTEXMODE D3DRS_FOGVERTEXMODE
#define so_called_lib_directx_D3DRS_LIGHTING D3DRS_LIGHTING 
#define so_called_lib_directx_D3DRS_SRCBLEND D3DRS_SRCBLEND 
#define so_called_lib_directx_D3DRS_ZENABLE D3DRS_ZENABLE
#define so_called_lib_directx_D3DSAMP_MAGFILTER D3DSAMP_MAGFILTER 
#define so_called_lib_directx_D3DSAMP_MINFILTER D3DSAMP_MINFILTER 
#define so_called_lib_directx_D3DSAMP_MIPFILTER D3DSAMP_MIPFILTER 
#define so_called_lib_directx_D3DTEXF_LINEAR D3DTEXF_LINEAR 
#define so_called_lib_directx_D3DTEXF_NONE D3DTEXF_NONE 
#define so_called_lib_directx_D3DTEXF_POINT D3DTEXF_POINT 
#define so_called_lib_directx_D3DTS_PROJECTION D3DTS_PROJECTION 
#define so_called_lib_directx_D3DTS_VIEW D3DTS_VIEW
#define so_called_lib_directx_D3DUSAGE_WRITEONLY D3DUSAGE_WRITEONLY
#define so_called_lib_directx_D3DXCreateMatrixStack D3DXCreateMatrixStack 
#define so_called_lib_directx_D3DXMatrixOrthoOffCenterRH D3DXMatrixOrthoOffCenterRH 
#define so_called_lib_directx_D3DXMatrixPerspectiveOffCenterRH D3DXMatrixPerspectiveOffCenterRH 
#define so_called_lib_directx_D3DZB_FALSE D3DZB_FALSE
#define so_called_lib_directx_D3DZB_TRUE D3DZB_TRUE
#define so_called_lib_directx_DXUTGetD3D9Device DXUTGetD3D9Device
#define so_called_lib_directx_FALSE FALSE
#define so_called_lib_directx_TRUE TRUE 
#define so_called_lib_directx_V V

typedef BYTE so_called_lib_directx_BYTE ;
typedef D3DCOLOR so_called_lib_directx_D3DCOLOR ;
typedef D3DLOCKED_RECT so_called_lib_directx_D3DLOCKED_RECT ;
typedef D3DVIEWPORT9 so_called_lib_directx_D3DVIEWPORT9 ;
typedef D3DXMATRIX so_called_lib_directx_D3DXMATRIX ;
typedef DWORD so_called_lib_directx_DWORD ; 
typedef FLOAT so_called_lib_directx_FLOAT ;
typedef HRESULT so_called_lib_directx_HRESULT ;
typedef IDirect3DIndexBuffer9 so_called_lib_directx_IDirect3DIndexBuffer9 ;
typedef IDirect3DTexture9 so_called_lib_directx_IDirect3DTexture9 ; 
typedef IDirect3DVertexBuffer9 so_called_lib_directx_IDirect3DVertexBuffer9 ;
typedef LPD3DXMATRIXSTACK so_called_lib_directx_LPD3DXMATRIXSTACK ;
typedef RECT so_called_lib_directx_RECT ;
typedef UINT so_called_lib_directx_UINT ;

#endif
