#ifndef _shy_common_logic_blanket_render_request_sender_injections_included
#define _shy_common_logic_blanket_render_request_sender_injections_included

#include "common/logic/blanket/message/render_request/shy_render_request_injections.h"

#include "./shy_render_request.h"

typedef shy_common_logic_blanket_render_request_sender so_called_common_logic_blanket_render_request_sender ;

#endif
