#ifndef _shy_common_engine_render_enable_face_culling_message_injections_included
#define _shy_common_engine_render_enable_face_culling_message_injections_included

#include "./shy_message.h"

typedef shy_common_engine_render_enable_face_culling_message so_called_common_engine_render_enable_face_culling_message ;

#endif
