#ifndef _shy_common_logic_main_menu_letters_animation_unselection_weight_unselect_row_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_unselection_weight_unselect_row_sender_injections_included

#include "common/logic/main_menu/letters/animation/message/unselection_weight_unselect_row/shy_unselection_weight_unselect_row_injections.h"

#include "./shy_unselection_weight_unselect_row.h"

typedef shy_common_logic_main_menu_letters_animation_unselection_weight_unselect_row_sender so_called_common_logic_main_menu_letters_animation_unselection_weight_unselect_row_sender ;

#endif
