#ifndef _shy_sender_common_logic_core_near_plane_distance_request_injections_included
#define _shy_sender_common_logic_core_near_plane_distance_request_injections_included

#include "../../message/near_plane_distance_request/shy_near_plane_distance_request_injections.h"

#include "./shy_near_plane_distance_request.h"

typedef shy_sender_common_logic_core_near_plane_distance_request so_called_sender_common_logic_core_near_plane_distance_request ;

#endif
