#ifndef _shy_sender_common_logic_main_menu_letters_layout_position_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_layout_position_reply_injections_included

#include "../../message/position_reply/shy_position_reply_injections.h"

#include "./shy_position_reply.h"

typedef shy_sender_common_logic_main_menu_letters_layout_position_reply so_called_sender_common_logic_main_menu_letters_layout_position_reply ;

#endif
