#ifndef _shy_common_logic_main_menu_letters_layout_position_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_layout_position_reply_sender_injections_included

#include "../../message/position_reply/shy_position_reply_injections.h"

#include "./shy_position_reply.h"

typedef shy_common_logic_main_menu_letters_layout_position_reply_sender so_called_common_logic_main_menu_letters_layout_position_reply_sender ;

#endif
