#ifndef _shy_common_logic_main_menu_letters_animation_disappear_finished_sender_injections_included
#define _shy_common_logic_main_menu_letters_animation_disappear_finished_sender_injections_included

#include "common/logic/main_menu/letters/animation/message/disappear_finished/shy_disappear_finished_injections.h"

#include "./shy_disappear_finished.h"

typedef shy_common_logic_main_menu_letters_animation_disappear_finished_sender so_called_common_logic_main_menu_letters_animation_disappear_finished_sender ;

#endif
