#ifndef _shy_sender_common_engine_render_matrix_identity_injections_included
#define _shy_sender_common_engine_render_matrix_identity_injections_included

#include "../message/shy_matrix_identity_injections.h"

#include "shy_matrix_identity.h"

typedef shy_sender_common_engine_render_matrix_identity so_called_sender_common_engine_render_matrix_identity ;

#endif

