#ifndef _shy_sender_common_engine_render_texture_set_texel_injections_included
#define _shy_sender_common_engine_render_texture_set_texel_injections_included

#include "../message/shy_texture_set_texel_injections.h"

#include "shy_texture_set_texel.h"

typedef shy_sender_common_engine_render_texture_set_texel so_called_sender_common_engine_render_texture_set_texel ;

#endif

