#ifndef _shy_sender_common_engine_render_enable_depth_test_injections_included
#define _shy_sender_common_engine_render_enable_depth_test_injections_included

#include "../message/shy_enable_depth_test_injections.h"

#include "shy_enable_depth_test.h"

typedef shy_sender_common_engine_render_enable_depth_test so_called_sender_common_engine_render_enable_depth_test ;

#endif

