#ifndef _shy_sender_common_engine_render_texture_finalize_injections_included
#define _shy_sender_common_engine_render_texture_finalize_injections_included

#include "../message/texture_finalize/shy_texture_finalize_injections.h"

#include "shy_texture_finalize.h"

typedef shy_sender_common_engine_render_texture_finalize so_called_sender_common_engine_render_texture_finalize ;

#endif

