#ifndef _shy_sender_common_engine_render_matrix_load_injections_included
#define _shy_sender_common_engine_render_matrix_load_injections_included

#include "../message/matrix_load/shy_matrix_load_injections.h"

#include "shy_matrix_load.h"

typedef shy_sender_common_engine_render_matrix_load so_called_sender_common_engine_render_matrix_load ;

#endif

