#ifndef _shy_sender_common_engine_render_blend_disable_injections_included
#define _shy_sender_common_engine_render_blend_disable_injections_included

#include "../message/blend_disable/shy_blend_disable_injections.h"

#include "shy_blend_disable.h"

typedef shy_sender_common_engine_render_blend_disable so_called_sender_common_engine_render_blend_disable ;

#endif

