#ifndef _shy_sender_common_engine_render_mesh_set_vertex_color_injections_included
#define _shy_sender_common_engine_render_mesh_set_vertex_color_injections_included

#include "../message/shy_mesh_set_vertex_color_injections.h"

#include "shy_mesh_set_vertex_color.h"

typedef shy_sender_common_engine_render_mesh_set_vertex_color so_called_sender_common_engine_render_mesh_set_vertex_color ;

#endif

