#ifndef _shy_sender_common_engine_render_projection_frustum_injections_included
#define _shy_sender_common_engine_render_projection_frustum_injections_included

#include "../message/shy_projection_frustum_injections.h"

#include "shy_projection_frustum.h"

typedef shy_sender_common_engine_render_projection_frustum so_called_sender_common_engine_render_projection_frustum ;

#endif

