#ifndef _shy_sender_common_engine_render_frame_loss_reply_injections_included
#define _shy_sender_common_engine_render_frame_loss_reply_injections_included

#include "../message/shy_frame_loss_reply_injections.h"

#include "shy_frame_loss_reply.h"

typedef shy_sender_common_engine_render_frame_loss_reply so_called_sender_common_engine_render_frame_loss_reply ;

#endif

