#ifndef _shy_sender_common_engine_render_texture_unselect_injections_included
#define _shy_sender_common_engine_render_texture_unselect_injections_included

#include "../message/texture_unselect/shy_texture_unselect_injections.h"

#include "shy_texture_unselect.h"

typedef shy_sender_common_engine_render_texture_unselect so_called_sender_common_engine_render_texture_unselect ;

#endif

