#ifndef _shy_sender_common_engine_render_mesh_render_injections_included
#define _shy_sender_common_engine_render_mesh_render_injections_included

#include "../message/shy_mesh_render_injections.h"

#include "shy_mesh_render.h"

typedef shy_sender_common_engine_render_mesh_render so_called_sender_mesh_common_engine_render_mesh_render ;

#endif

