#ifndef _shy_sender_common_engine_render_mesh_finalize_injections_included
#define _shy_sender_common_engine_render_mesh_finalize_injections_included

#include "../message/mesh_finalize/shy_mesh_finalize_injections.h"

#include "shy_mesh_finalize.h"

typedef shy_sender_common_engine_render_mesh_finalize so_called_sender_common_engine_render_mesh_finalize ;

#endif

