#ifndef _shy_common_logic_main_menu_render_permit_sender_injections_included
#define _shy_common_logic_main_menu_render_permit_sender_injections_included

#include "common/logic/main_menu/message/render_permit/shy_render_permit_injections.h"

#include "./shy_render_permit.h"

typedef shy_common_logic_main_menu_render_permit_sender so_called_common_logic_main_menu_render_permit_sender ;

#endif
