#ifndef _shy_common_logic_room_texture_select_reply_sender_injections_included
#define _shy_common_logic_room_texture_select_reply_sender_injections_included

#include "src/common/logic/room/texture/select/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_room_texture_select_reply_sender so_called_common_logic_room_texture_select_reply_sender ;

#endif
