#ifndef _shy_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha_injections_included
#define _shy_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha_injections_included

#include "./shy_blend_src_alpha_dst_one_minus_alpha.h"

typedef shy_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha so_called_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha ;

#endif
