#ifndef _shy_common_logic_main_menu_created_message_injections_included
#define _shy_common_logic_main_menu_created_message_injections_included

#include "./shy_created.h"

typedef shy_common_logic_main_menu_created_message so_called_common_logic_main_menu_created_message ;

#endif
