#ifndef _shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh_injections_included
#define _shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh_injections_included

#include "../../message/add_mesh/shy_add_mesh_injections.h"
#include "./shy_add_mesh.h"

typedef shy_sender_common_logic_salutation_letters_meshes_storage_add_mesh so_called_sender_common_logic_salutation_letters_meshes_storage_add_mesh ;

#endif
