#ifndef _shy_sender_common_logic_text_use_text_texture_reply_injections_included
#define _shy_sender_common_logic_text_use_text_texture_reply_injections_included

#include "../../message/use_text_texture_reply/shy_use_text_texture_reply_injections.h"

#include "./shy_use_text_texture_reply.h"

typedef shy_sender_common_logic_text_use_text_texture_reply so_called_sender_common_logic_text_use_text_texture_reply ;

#endif
