#ifndef _shy_iphone_platform_sound_loader_injections_included
#define _shy_iphone_platform_sound_loader_injections_included

#include "src/platform/sound/loader/cocoa/shy_cocoa_injections.h"
typedef so_called_platform_sound_loader_cocoa so_called_platform_sound_loader ;

#endif
