#ifndef _shy_type_loadable_fsm_content_system_container_injections_included
#define _shy_type_loadable_fsm_content_system_container_injections_included

#include "./shy_system_container.h"

typedef shy_type_loadable_fsm_content_system_container so_called_type_loadable_fsm_content_system_container ;

#endif
