#ifndef _shy_sender_common_logic_door_texture_select_request_injections_included
#define _shy_sender_common_logic_door_texture_select_request_injections_included

#include "../../message/texture_select_request/shy_texture_select_request_injections.h"

#include "./shy_texture_select_request.h"

typedef shy_sender_common_logic_door_texture_select_request so_called_sender_common_logic_door_texture_select_request ;

#endif
