#ifndef _shy_sender_common_logic_main_menu_animation_shake_transform_reply_injections_included
#define _shy_sender_common_logic_main_menu_animation_shake_transform_reply_injections_included

#include "../../message/shake_transform_reply/shy_shake_transform_reply_injections.h"

#include "./shy_shake_transform_reply.h"

typedef shy_sender_common_logic_main_menu_animation_shake_transform_reply so_called_sender_common_logic_main_menu_animation_shake_transform_reply ;

#endif
