#ifndef _shy_common_engine_render_aspect_reply_sender_injections_included
#define _shy_common_engine_render_aspect_reply_sender_injections_included

#include "common/engine/render/message/aspect_reply/shy_aspect_reply_injections.h"

#include "./shy_aspect_reply.h"

typedef shy_common_engine_render_aspect_reply_sender so_called_common_engine_render_aspect_reply_sender ;

#endif

