java org.antlr.Tool -verbose -make -fo copypaster copypaster/Frontend.g
java org.antlr.Tool -verbose -make -fo copypaster copypaster/Backend.g
java org.antlr.Tool -verbose -make -fo autogenerated grammar/ShyLexer.g
java org.antlr.Tool -verbose -make -fo autogenerated grammar/ShyRecognizerBackend.g
java org.antlr.Tool -verbose -make -fo autogenerated grammar/ShyRecognizerFrontend.g
