from antlr3 import ANTLRInputStream , CommonTokenStream , RecognitionException
from antlr3 . tree import CommonTreeNodeStream
from antlr3 . constants import EOF
from autogenerated . ShyRecognizerBackend import ShyRecognizerBackend
from autogenerated . ShyRecognizerFrontend import ShyRecognizerFrontend
from autogenerated . ShyRecognizerFrontend import ShyRecognizerFrontendException
from autogenerated . ShyLexer import ShyLexer , ShyLexerException

class exception ( Exception ) :
    def __init__ ( self , text ) :
        Exception . __init__ ( self , text )

class recognizer :
    def run ( self , input ) :
        sl = ShyLexer ( ANTLRInputStream ( input ) )
        ts = CommonTokenStream ( sl )
        srf = ShyRecognizerFrontend ( ts )
        try :
            t = srf . start ( ) . tree
        except ShyLexerException as e :
            raise exception ( str ( e ) )
        except ShyRecognizerFrontendException as e :
            raise exception ( str ( e ) )
        if ts . LA ( 1 ) != EOF :
            raise exception ( 'unparsed tokens left' )
        if t == None :
            return { }
        else :
            srb = ShyRecognizerBackend ( CommonTreeNodeStream ( t ) )
            return srb . start ( )
