from antlr3 import ANTLRInputStream , CommonTokenStream , RecognitionException
from antlr3 . tree import CommonTreeNodeStream
from antlr3 . constants import EOF
from autogenerated . RecognizerFrontendParser import RecognizerFrontendParser
from autogenerated . RecognizerFrontendParser import RecognizerFrontendParserException
from autogenerated . RecognizerFrontendLexer import RecognizerFrontendLexer
from autogenerated . RecognizerFrontendLexer import RecognizerFrontendLexerException
from autogenerated . RecognizerBackend import RecognizerBackend

class exception ( Exception ) :
    def __init__ ( self , text ) :
        Exception . __init__ ( self , text )

class recognizer :
    def run ( self , input ) :
        fel = RecognizerFrontendLexer ( ANTLRInputStream ( input ) )
        ts = CommonTokenStream ( fel )
        fep = RecognizerFrontendParser ( ts )
        try :
            t = fep . start ( ) . tree
        except RecognizerFrontendLexerException as e :
            raise exception ( str ( e ) )
        except RecognizerFrontendParserException as e :
            raise exception ( str ( e ) )
        if ts . LA ( 1 ) != EOF :
            raise exception ( 'unparsed tokens left' )
        if t == None :
            return { }
        else :
            be = RecognizerBackend ( CommonTreeNodeStream ( t ) )
            return be . start ( )
