#include "./shy_render_injections.h"

#include "common/engine/render/consts/shy_consts_injections.h"
#include "common/engine/render/aspect/reply/sender/shy_sender_injections.h"
#include "common/engine/render/frame/loss/reply/sender/shy_sender_injections.h"
#include "common/engine/render/mesh/create/reply/sender/shy_sender_injections.h"
#include "common/engine/render/texture/create/reply/sender/shy_sender_injections.h"
#include "common/engine/render/texture/loader/ready/reply/sender/shy_sender_injections.h"
#include "injections/lib/std/true/shy_true.h"
#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"
#include "injections/platform/math/const/int/32/type/shy_type.h"
#include "injections/platform/matrix/shy_matrix.h"
#include "injections/platform/render/shy_render.h"
#include "injections/platform/render/texture/loader/shy_loader.h"
#include "injections/platform/render/texture/id/type/shy_type.h"
#include "injections/platform/render/index/buffer/id/type/shy_type.h"
#include "injections/platform/render/index/buffer/mapped/data/type/shy_type.h"
#include "injections/platform/render/vertex/buffer/id/type/shy_type.h"
#include "injections/platform/render/vertex/buffer/mapped/data/type/shy_type.h"
#include "injections/platform/static/array/shy_array.h"
#include "injections/platform/static/array/data/type/shy_type.h"
#include "trace/common/engine/render/shy_render_injections.h"
#include "trace/shy_trace_injections.h"

#include "./shy_render.hpp"
