#ifndef _shy_common_logic_salutation_letters_meshes_generator_generate_message_injections_included
#define _shy_common_logic_salutation_letters_meshes_generator_generate_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_meshes_generator_generate_message so_called_common_logic_salutation_letters_meshes_generator_generate_message ;

#endif
