#ifndef _shy_common_logic_room_texture_select_reply_sender_injections_included
#define _shy_common_logic_room_texture_select_reply_sender_injections_included

#include "common/logic/room/message/texture_select_reply/shy_texture_select_reply_injections.h"

#include "./shy_texture_select_reply.h"

typedef shy_common_logic_room_texture_select_reply_sender so_called_common_logic_room_texture_select_reply_sender ;

#endif
