#ifndef _shy_sender_common_logic_room_texture_select_reply_injections_included
#define _shy_sender_common_logic_room_texture_select_reply_injections_included

#include "../../message/texture_select_reply/shy_texture_select_reply_injections.h"

#include "./shy_texture_select_reply.h"

typedef shy_sender_common_logic_room_texture_select_reply so_called_sender_common_logic_room_texture_select_reply ;

#endif
