#ifndef _shy_win_platform_render_index_buffer_id_type_injections_included
#define _shy_win_platform_render_index_buffer_id_type_injections_included

#include "platform/render/directx/type/index_buffer_id/shy_index_buffer_id_injections.h"
typedef so_called_platform_render_directx_index_buffer_id_type so_called_platform_render_index_buffer_id_type ;

#endif

