#ifndef _shy_type_iphone_platform_render_index_data_injections_included
#define _shy_type_iphone_platform_render_index_data_injections_included

#include "platform/render/opengl/type/index_data/shy_index_data_injections.h"
typedef so_called_type_platform_render_opengl_index_data so_called_type_platform_render_index_data ;

#endif
