#ifndef _shy_common_logic_application_fsm_binding_injections_included
#define _shy_common_logic_application_fsm_binding_injections_included

#include "./shy_binding.h"

#define so_called_common_logic_application_fsm_binding shy_common_logic_application_fsm_binding

#endif
