#ifndef _shy_message_common_logic_salutation_timer_appear_run_finished_injections_included
#define _shy_message_common_logic_salutation_timer_appear_run_finished_injections_included

#include "./shy_run_finished.h"

typedef shy_message_common_logic_salutation_timer_appear_run_finished so_called_message_common_logic_salutation_timer_appear_run_finished ;

#endif
