#ifndef _shy_common_logic_salutation_letters_text_storage_letter_reply_message_injections_included
#define _shy_common_logic_salutation_letters_text_storage_letter_reply_message_injections_included

#include "common/logic/text/letter/id/type/shy_type_injections.h"
#include "injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_text_storage_letter_reply_message so_called_common_logic_salutation_letters_text_storage_letter_reply_message ;

#endif
