#ifndef _shy_common_logic_salutation_letters_text_storage_letter_reply_message_injections_included
#define _shy_common_logic_salutation_letters_text_storage_letter_reply_message_injections_included

#include "common/logic/text/type/letter_id/shy_letter_id_injections.h"
#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_message.h"

typedef shy_common_logic_salutation_letters_text_storage_letter_reply_message so_called_common_logic_salutation_letters_text_storage_letter_reply_message ;

#endif
