#ifndef _shy_common_logic_main_menu_selection_animation_idle_transform_reply_message_injections_included
#define _shy_common_logic_main_menu_selection_animation_idle_transform_reply_message_injections_included

#include "src/injections/platform/math/num/fract/type/shy_type.h"
#include "src/injections/platform/vector/data/type/shy_type.h"

#include "./shy_message.h"

typedef shy_common_logic_main_menu_selection_animation_idle_transform_reply_message so_called_common_logic_main_menu_selection_animation_idle_transform_reply_message ;

#endif
