#ifndef _shy_common_engine_render_texture_set_texels_rect_sender_injections_included
#define _shy_common_engine_render_texture_set_texels_rect_sender_injections_included

#include "../../message/texture_set_texels_rect/shy_texture_set_texels_rect_injections.h"

#include "./shy_texture_set_texels_rect.h"

typedef shy_common_engine_render_texture_set_texels_rect_sender so_called_common_engine_render_texture_set_texels_rect_sender ;

#endif

