#ifndef _shy_sender_common_engine_rasterizer_finalize_request_injections_included
#define _shy_sender_common_engine_rasterizer_finalize_request_injections_included

#include "../../message/finalize_request/shy_finalize_request_injections.h"

#include "./shy_finalize_request.h"

typedef shy_sender_common_engine_rasterizer_finalize_request so_called_sender_common_engine_rasterizer_finalize_request ;

#endif
