#ifndef _shy_message_common_logic_entities_mesh_grid_request_injections_included
#define _shy_message_common_logic_entities_mesh_grid_request_injections_included

#include "./shy_mesh_grid_request.h"

typedef shy_message_common_logic_entities_mesh_grid_request so_called_message_common_logic_entities_mesh_grid_request ;

#endif
