#ifndef _shy_message_common_logic_main_menu_selection_animation_disappear_transform_request_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_disappear_transform_request_injections_included

#include "./shy_disappear_transform_request.h"

typedef shy_message_common_logic_main_menu_selection_animation_disappear_transform_request so_called_message_common_logic_main_menu_selection_animation_disappear_transform_request ;

#endif
