#ifndef _shy_sender_common_logic_main_menu_animation_shake_transform_request_injections_included
#define _shy_sender_common_logic_main_menu_animation_shake_transform_request_injections_included

#include "../../message/shake_transform_request/shy_shake_transform_request_injections.h"

#include "./shy_shake_transform_request.h"

typedef shy_sender_common_logic_main_menu_animation_shake_transform_request so_called_sender_common_logic_main_menu_animation_shake_transform_request ;

#endif
