#ifndef _shy_type_loadable_consts_content_module_binding_injections_included
#define _shy_type_loadable_consts_content_module_binding_injections_included

#include "./shy_module_binding.h"

typedef shy_type_loadable_consts_content_module_binding so_called_type_loadable_consts_content_module_binding ;

#endif
