#ifndef _shy_iphone_platform_matrix_profile_injections_included
#define _shy_iphone_platform_matrix_profile_injections_included

#include "src/profile/platform/matrix/shy_matrix_injections.h"

#endif
