#ifndef _shy_message_common_logic_blanket_animation_disappear_start_injections_included
#define _shy_message_common_logic_blanket_animation_disappear_start_injections_included

#include "./shy_disappear_start.h"

typedef shy_message_common_logic_blanket_animation_disappear_start so_called_message_common_logic_blanket_animation_disappear_start ;

#endif
