#ifndef _shy_sender_common_logic_main_menu_selection_tracking_director_update_injections_included
#define _shy_sender_common_logic_main_menu_selection_tracking_director_update_injections_included

#include "../../message/tracking_director_update/shy_tracking_director_update_injections.h"

#include "./shy_tracking_director_update.h"

typedef shy_sender_common_logic_main_menu_selection_tracking_director_update so_called_sender_common_logic_main_menu_selection_tracking_director_update ;

#endif
