#ifndef _shy_win_platform_sound_loader_injections_included
#define _shy_win_platform_sound_loader_injections_included

#include "src/platform/sound/loader/winapi/shy_winapi_injections.h"
typedef so_called_platform_sound_loader_winapi so_called_platform_sound_loader ;

#endif
