#ifndef _shy_message_common_logic_text_update_injections_included
#define _shy_message_common_logic_text_update_injections_included

#include "./shy_update.h"

typedef shy_message_common_logic_text_update so_called_message_common_logic_text_update ;

#endif
