#ifndef _shy_sender_common_logic_salutation_letters_text_generator_generate_finished_injections_included
#define _shy_sender_common_logic_salutation_letters_text_generator_generate_finished_injections_included

#include "../message/shy_message_injections.h"
#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_text_generator_generate_finished so_called_sender_common_logic_salutation_letters_text_generator_generate_finished ;

#endif
