#ifndef _shy_macosx_platform_sound_sample_mono_type_injections_included
#define _shy_macosx_platform_sound_sample_mono_type_injections_included

#include "platform/sound/openal/type/sample_mono/shy_sample_mono_injections.h"
typedef so_called_platform_sound_openal_sample_mono_type so_called_platform_sound_sample_mono_type ;

#endif

