#ifndef _shy_loadable_consts_reflection_logic_observer_animation_injections_included
#define _shy_loadable_consts_reflection_logic_observer_animation_injections_included

#include "./shy_logic_observer_animation.h"

typedef shy_loadable_consts_reflection_logic_observer_animation so_called_loadable_consts_reflection_logic_observer_animation ;

#endif
