#ifndef _shy_win_platform_render_vertex_buffer_id_type_injections_included
#define _shy_win_platform_render_vertex_buffer_id_type_injections_included

#include "src/platform/render/directx/vertex/buffer/id/type/shy_type_injections.h"
typedef so_called_platform_render_directx_vertex_buffer_id_type so_called_platform_render_vertex_buffer_id_type ;

#endif
