#ifndef _shy_common_engine_fsm_state_type_injections_included
#define _shy_common_engine_fsm_state_type_injections_included

#include "./shy_type.h"

typedef shy_common_engine_fsm_state_type so_called_common_engine_fsm_state_type ;

#endif
