#include "./shy_creator_injections.h"

#include "common/logic/main/menu/letters/meshes/consts/shy_consts_injections.h"
#include "common/logic/main/menu/letters/meshes/creation/finished/sender/shy_sender_injections.h"
#include "common/logic/main/menu/letters/meshes/mesh/has/been/created/sender/shy_sender_injections.h"
#include "common/logic/main/menu/letters/cols/request/sender/shy_sender_injections.h"
#include "common/logic/main/menu/letters/letter/request/sender/shy_sender_injections.h"
#include "common/logic/main/menu/letters/rows/request/sender/shy_sender_injections.h"
#include "common/logic/text/consts/shy_consts_injections.h"
#include "common/logic/text/letter/mesh/create/request/sender/shy_sender_injections.h"
#include "common/logic/text/stateless/shy_stateless_injections.h"
#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"

#include "./shy_creator.hpp"
