#ifndef _shy_message_common_logic_main_menu_selection_mesh_create_finished_injections_included
#define _shy_message_common_logic_main_menu_selection_mesh_create_finished_injections_included

#include "./shy_mesh_create_finished.h"

typedef shy_message_common_logic_main_menu_selection_mesh_create_finished so_called_message_common_logic_main_menu_selection_mesh_create_finished ;

#endif
