#ifndef _shy_macosx_platform_scheduler_profile_injections_included
#define _shy_macosx_platform_scheduler_profile_injections_included

#include "src/profile/platform/scheduler/shy_scheduler_injections.h"

#endif
