#ifndef _shy_message_common_logic_main_menu_letters_meshes_mesh_create_next_injections_included
#define _shy_message_common_logic_main_menu_letters_meshes_mesh_create_next_injections_included

#include "./shy_mesh_create_next.h"

typedef shy_message_common_logic_main_menu_letters_meshes_mesh_create_next so_called_message_common_logic_main_menu_letters_meshes_mesh_create_next ;

#endif
