#ifndef _shy_common_logic_perspective_planes_request_sender_injections_included
#define _shy_common_logic_perspective_planes_request_sender_injections_included

#include "../../message/planes_request/shy_planes_request_injections.h"

#include "./shy_planes_request.h"

typedef shy_common_logic_perspective_planes_request_sender so_called_common_logic_perspective_planes_request_sender ;

#endif
