#ifndef _shy_type_win_platform_render_index_buffer_mapped_data_injections_included
#define _shy_type_win_platform_render_index_buffer_mapped_data_injections_included

#include "platform/render/directx/type/index_buffer_mapped_data/shy_index_buffer_mapped_data_injections.h"
typedef so_called_type_platform_render_directx_index_buffer_mapped_data so_called_type_platform_render_index_buffer_mapped_data ;

#endif

