// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_perspective_consts :: z_far_unscaled = so_called_platform_math :: init_num_fract ( 50 , 1 ) ;

// autogenerated file end
