#ifndef _shy_message_common_engine_render_init_injections_included
#define _shy_message_common_engine_render_init_injections_included

#include "./shy_init.h"

typedef shy_message_common_engine_render_init so_called_message_common_engine_render_init ;

#endif
