#ifndef _shy_sender_common_logic_main_menu_selection_animation_unselect_finished_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_unselect_finished_injections_included

#include "../../message/unselect_finished/shy_unselect_finished_injections.h"

#include "./shy_unselect_finished.h"

typedef shy_sender_common_logic_main_menu_selection_animation_unselect_finished so_called_sender_common_logic_main_menu_selection_animation_unselect_finished ;

#endif
