#ifndef _shy_type_iphone_platform_sound_sample_mono_injections_included
#define _shy_type_iphone_platform_sound_sample_mono_injections_included

#include "platform/sound/openal/type/sample_mono/shy_sample_mono_injections.h"
typedef so_called_type_platform_sound_openal_sample_mono so_called_type_platform_sound_sample_mono ;

#endif

