#ifndef _shy_common_logic_core_use_perspective_projection_reply_message_injections_included
#define _shy_common_logic_core_use_perspective_projection_reply_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_core_use_perspective_projection_reply_message so_called_common_logic_core_use_perspective_projection_reply_message ;

#endif
