class shy_loadable_generator_consts
{
public :
    static const so_called_lib_std_string autogenerated_folder_path ;
    static const so_called_lib_std_string common_folder_path ;
    static const so_called_lib_std_string new_line ;
    static const so_called_lib_std_string whitespace ;
} ;
