#include "./shy_storage_injections.h"

#include "src/common/engine/render/consts/shy_consts_injections.h"
#include "src/common/logic/salutation/letters/consts/shy_consts_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/mesh/reply/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/size/reply/sender/shy_sender_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"
#include "src/injections/platform/pointer/shy_pointer.h"
#include "src/injections/platform/pointer/data/type/shy_type.h"
#include "src/injections/platform/static/array/shy_array.h"
#include "src/injections/platform/static/array/data/type/shy_type.h"
#include "src/trace/common/logic/salutation/letters/meshes/storage/shy_storage_injections.h"
#include "src/trace/shy_trace_injections.h"

#include "./shy_storage.hpp"
