#ifndef _shy_common_engine_rasterizer_finalize_request_sender_injections_included
#define _shy_common_engine_rasterizer_finalize_request_sender_injections_included

#include "../../message/finalize_request/shy_finalize_request_injections.h"

#include "./shy_finalize_request.h"

typedef shy_common_engine_rasterizer_finalize_request_sender so_called_common_engine_rasterizer_finalize_request_sender ;

#endif
