// autogenerated file begin

#ifndef _shy_common_logic_application_fsm_behaviour_static_autogenerated_injections_included
#define _shy_common_logic_application_fsm_behaviour_static_autogenerated_injections_included

#include "src/injections/platform/pointer/data/type/shy_type.h"

#include "./shy_autogenerated.h"

typedef shy_common_logic_application_fsm_behaviour_static so_called_common_logic_application_fsm_behaviour_static ;

#endif

// autogenerated file end
