// autogenerated file begin

#include "common/engine/fsm/stateless/shy_stateless_injections.h"

#include "injections/platform/math/consts/shy_consts.h"

#include "./shy_autogenerated.hpp"

// autogenerated file end
