#ifndef _shy_win_platform_render_index_data_type_injections_included
#define _shy_win_platform_render_index_data_type_injections_included

#include "platform/render/directx/type/index_data/shy_index_data_injections.h"
typedef so_called_platform_render_directx_index_data_type so_called_platform_render_index_data_type ;

#endif
