#ifndef _shy_common_logic_main_menu_letters_meshes_place_message_injections_included
#define _shy_common_logic_main_menu_letters_meshes_place_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_main_menu_letters_meshes_place_message so_called_common_logic_main_menu_letters_meshes_place_message ;

#endif
