#include "../logic/ortho/consts/shy_consts_injections.h"
#include "../logic/title/consts/shy_consts_injections.h"

#include "../../injections/platform/math/shy_math.h"

#include "./shy_autogenerated.hpp"
