#include "../engine/fsm/stateless/shy_stateless_injections.h"
#include "../logic/application/fsm/actions/shy_actions_injections.h"
#include "../logic/application/fsm/behaviour/shy_behaviour_injections.h"
#include "../logic/ortho/consts/shy_consts_injections.h"
#include "../logic/perspective/consts/shy_consts_injections.h"
#include "../logic/room/consts/shy_consts_injections.h"
#include "../logic/title/consts/shy_consts_injections.h"

#include "../../injections/platform/math/shy_math.h"

#include "./shy_autogenerated.hpp"
