#ifndef _shy_loadable_fsm_content_action_command_type_injections_included
#define _shy_loadable_fsm_content_action_command_type_injections_included

#include "./shy_action_command.h"

typedef shy_loadable_fsm_content_action_command_type so_called_loadable_fsm_content_action_command_type ;

#endif
