#ifndef _shy_common_logic_entities_prepare_permit_sender_injections_included
#define _shy_common_logic_entities_prepare_permit_sender_injections_included

#include "src/common/logic/entities/prepare/permit/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_entities_prepare_permit_sender so_called_common_logic_entities_prepare_permit_sender ;

#endif
