#ifndef _shy_common_logic_door_animation_appear_start_sender_injections_included
#define _shy_common_logic_door_animation_appear_start_sender_injections_included

#include "src/common/logic/door/animation/appear/start/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_door_animation_appear_start_sender so_called_common_logic_door_animation_appear_start_sender ;

#endif
