#include "./shy_menu_injections.h"

#include "src/common/logic/main/menu/letters/animation/disappear/start/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/letters/meshes/create/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/letters/meshes/destroy/request/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/letters/meshes/place/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/letters/create/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/selection/animation/disappear/start/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/selection/mesh/create/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/selection/mesh/destroy/request/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/selection/mesh/place/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/selection/tracking/director/update/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/created/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/finished/sender/shy_sender_injections.h"
#include "src/common/logic/main/menu/render/permit/sender/shy_sender_injections.h"

#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"

#include "./shy_menu.hpp"
