#ifndef _shy_common_logic_blanket_mesh_set_transform_sender_injections_included
#define _shy_common_logic_blanket_mesh_set_transform_sender_injections_included

#include "common/logic/blanket/message/mesh_set_transform/shy_mesh_set_transform_injections.h"

#include "./shy_mesh_set_transform.h"

typedef shy_common_logic_blanket_mesh_set_transform_sender so_called_common_logic_blanket_mesh_set_transform_sender ;

#endif
