#ifndef _shy_message_common_logic_blanket_animation_fit_transform_request_injections_included
#define _shy_message_common_logic_blanket_animation_fit_transform_request_injections_included

#include "./shy_fit_transform_request.h"

typedef shy_message_common_logic_blanket_animation_fit_transform_request so_called_message_common_logic_blanket_animation_fit_transform_request ;

#endif
