#ifndef _shy_common_engine_render_matrix_identity_sender_injections_included
#define _shy_common_engine_render_matrix_identity_sender_injections_included

#include "common/engine/render/message/matrix_identity/shy_matrix_identity_injections.h"

#include "./shy_matrix_identity.h"

typedef shy_common_engine_render_matrix_identity_sender so_called_common_engine_render_matrix_identity_sender ;

#endif

