#ifndef _shy_sender_common_logic_salutation_letters_text_storage_size_request_injections_included
#define _shy_sender_common_logic_salutation_letters_text_storage_size_request_injections_included

#include "../../message/size_request/shy_size_request_injections.h"
#include "./shy_size_request.h"

typedef shy_sender_common_logic_salutation_letters_text_storage_size_request so_called_sender_common_logic_salutation_letters_text_storage_size_request ;

#endif
