#ifndef _shy_common_logic_door_place_message_injections_included
#define _shy_common_logic_door_place_message_injections_included

#include "./shy_message.h"

typedef shy_common_logic_door_place_message so_called_common_logic_door_place_message ;

#endif
