#ifndef _shy_common_engine_render_frame_loss_reply_sender_injections_included
#define _shy_common_engine_render_frame_loss_reply_sender_injections_included

#include "common/engine/render/message/frame_loss_reply/shy_frame_loss_reply_injections.h"

#include "./shy_frame_loss_reply.h"

typedef shy_common_engine_render_frame_loss_reply_sender so_called_common_engine_render_frame_loss_reply_sender ;

#endif

