#ifndef _shy_common_logic_blanket_animation_appear_finished_sender_injections_included
#define _shy_common_logic_blanket_animation_appear_finished_sender_injections_included

#include "../../message/appear_finished/shy_appear_finished_injections.h"

#include "./shy_appear_finished.h"

typedef shy_common_logic_blanket_animation_appear_finished_sender so_called_common_logic_blanket_animation_appear_finished_sender ;

#endif
