#ifndef _shy_common_logic_main_menu_selection_track_void_selected_sender_injections_included
#define _shy_common_logic_main_menu_selection_track_void_selected_sender_injections_included

#include "src/common/logic/main/menu/selection/track/void/selected/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_main_menu_selection_track_void_selected_sender so_called_common_logic_main_menu_selection_track_void_selected_sender ;

#endif
