#ifndef _shy_common_logic_entities_height_reply_sender_injections_included
#define _shy_common_logic_entities_height_reply_sender_injections_included

#include "common/logic/entities/message/height_reply/shy_height_reply_injections.h"

#include "./shy_height_reply.h"

typedef shy_common_logic_entities_height_reply_sender so_called_common_logic_entities_height_reply_sender ;

#endif
