#ifndef _shy_sender_common_logic_main_menu_letters_meshes_mesh_has_been_created_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_mesh_has_been_created_injections_included

#include "../../message/mesh_has_been_created/shy_mesh_has_been_created_injections.h"

#include "./shy_mesh_has_been_created.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_mesh_has_been_created so_called_sender_common_logic_main_menu_letters_meshes_mesh_has_been_created ;

#endif
