#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_has_been_created_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_has_been_created_sender_injections_included

#include "common/logic/main_menu/letters/meshes/message/mesh_has_been_created/shy_mesh_has_been_created_injections.h"

#include "./shy_mesh_has_been_created.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_has_been_created_sender so_called_common_logic_main_menu_letters_meshes_mesh_has_been_created_sender ;

#endif
