#ifndef _shy_common_logic_blanket_animation_fit_transform_reply_sender_injections_included
#define _shy_common_logic_blanket_animation_fit_transform_reply_sender_injections_included

#include "common/logic/blanket/animation/message/fit_transform_reply/shy_fit_transform_reply_injections.h"

#include "./shy_fit_transform_reply.h"

typedef shy_common_logic_blanket_animation_fit_transform_reply_sender so_called_common_logic_blanket_animation_fit_transform_reply_sender ;

#endif
