#ifndef _shy_type_win_platform_sound_buffer_id_injections_included
#define _shy_type_win_platform_sound_buffer_id_injections_included

#include "platform/sound/directx/type/buffer_id/shy_buffer_id_injections.h"
typedef so_called_type_platform_sound_directx_buffer_id so_called_type_platform_sound_buffer_id ;

#endif

