#ifndef _shy_loadable_consts_content_module_container_type_injections_included
#define _shy_loadable_consts_content_module_container_type_injections_included

#include "loadable/consts/content/type/module/shy_module_injections.h"

#include "./shy_module_container.h"

typedef shy_loadable_consts_content_module_container_type so_called_loadable_consts_content_module_container_type ;

#endif
