#ifndef _shy_type_loadable_consts_content_module_container_injections_included
#define _shy_type_loadable_consts_content_module_container_injections_included

#include "loadable/consts/content/type/module/shy_module_injections.h"

#include "./shy_module_container.h"

typedef shy_type_loadable_consts_content_module_container so_called_type_loadable_consts_content_module_container ;

#endif
