#ifndef _shy_message_common_logic_blanket_place_injections_included
#define _shy_message_common_logic_blanket_place_injections_included

#include "./shy_place.h"

typedef shy_message_common_logic_blanket_place so_called_message_common_logic_blanket_place ;

#endif
