#ifndef _shy_common_logic_text_letter_small_tex_coords_request_sender_injections_included
#define _shy_common_logic_text_letter_small_tex_coords_request_sender_injections_included

#include "common/logic/text/message/letter_small_tex_coords_request/shy_letter_small_tex_coords_request_injections.h"

#include "./shy_letter_small_tex_coords_request.h"

typedef shy_common_logic_text_letter_small_tex_coords_request_sender so_called_common_logic_text_letter_small_tex_coords_request_sender ;

#endif
