#ifndef _shy_message_common_logic_main_menu_selection_animation_idle_void_selected_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_idle_void_selected_injections_included

#include "./shy_idle_void_selected.h"

typedef shy_message_common_logic_main_menu_selection_animation_idle_void_selected so_called_message_common_logic_main_menu_selection_animation_idle_void_selected ;

#endif
