#ifndef _shy_macosx_platform_render_index_buffer_id_type_injections_included
#define _shy_macosx_platform_render_index_buffer_id_type_injections_included

#include "src/platform/render/opengl/index/buffer/id/type/shy_type_injections.h"
typedef so_called_platform_render_opengl_index_buffer_id_type so_called_platform_render_index_buffer_id_type ;

#endif

