#ifndef _shy_common_logic_salutation_timer_disappear_tick_sender_injections_included
#define _shy_common_logic_salutation_timer_disappear_tick_sender_injections_included

#include "src/common/logic/salutation/timer/disappear/tick/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_timer_disappear_tick_sender so_called_common_logic_salutation_timer_disappear_tick_sender ;

#endif
