#include "./shy_layout_injections.h"

#include "src/common/engine/render/aspect/checker/shy_checker_injections.h"
#include "src/common/engine/render/aspect/request/sender/shy_sender_injections.h"
#include "src/common/engine/taker/helper/shy_helper_injections.h"
#include "src/common/logic/salutation/letters/animation/consts/shy_consts_injections.h"
#include "src/common/logic/salutation/letters/animation/layout/transform/reply/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/meshes/consts/shy_consts_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/size/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/meshes/storage/size/request/sender/shy_sender_injections.h"
#include "src/common/logic/text/stateless/shy_stateless_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"
#include "src/injections/platform/vector/shy_vector.h"

#include "./shy_layout.hpp"
