#ifndef _shy_message_common_logic_fidget_prepared_injections_included
#define _shy_message_common_logic_fidget_prepared_injections_included

#include "./shy_prepared.h"

typedef shy_message_common_logic_fidget_prepared so_called_message_common_logic_fidget_prepared ;

#endif
