#include "../engine/rasterizer/shy_rasterizer_injections.h"
#include "../engine/render/shy_render_injections.h"
#include "../logic/amusement/renderer/shy_renderer_injections.h"
#include "../logic/amusement/shy_amusement_injections.h"
#include "../logic/application/fsm/shy_fsm_injections.h"
#include "../logic/blanket/animation/appear/shy_appear_injections.h"
#include "../logic/blanket/animation/disappear/shy_disappear_injections.h"
#include "../logic/blanket/animation/fit/shy_fit_injections.h"
#include "../logic/blanket/animation/shy_animation_injections.h"
#include "../logic/blanket/mesh/shy_mesh_injections.h"
#include "../logic/blanket/placement/shy_placement_injections.h"
#include "../logic/blanket/renderer/shy_renderer_injections.h"
#include "../logic/blanket/shy_blanket_injections.h"
#include "../logic/camera/shy_camera_injections.h"
#include "../logic/controls/shy_controls_injections.h"
#include "../logic/core/shy_core_injections.h"
#include "../logic/door/animation/appear/shy_appear_injections.h"
#include "../logic/door/animation/shy_animation_injections.h"
#include "../logic/door/mesh/shy_mesh_injections.h"
#include "../logic/door/placement/shy_placement_injections.h"
#include "../logic/door/renderer/shy_renderer_injections.h"
#include "../logic/door/shy_door_injections.h"
#include "../logic/door/texture/shy_texture_injections.h"

#include "./shy_init_injections.h"
#include "./shy_init.hpp"

