#ifndef _shy_type_platform_render_directx_texel_data_injections_included
#define _shy_type_platform_render_directx_texel_data_injections_included

#include "injections/lib/directx/shy_directx.h"

#include "./shy_texel_data.h"

typedef shy_type_platform_render_directx_texel_data so_called_type_platform_render_directx_texel_data ;

#endif
