#ifndef _shy_message_common_logic_title_created_injections_included
#define _shy_message_common_logic_title_created_injections_included

#include "./shy_created.h"

typedef shy_message_common_logic_title_created so_called_message_common_logic_title_created ;

#endif
