#ifndef _shy_sender_common_logic_amusement_creation_permit_injections_included
#define _shy_sender_common_logic_amusement_creation_permit_injections_included

#include "../../message/creation_permit/shy_creation_permit_injections.h"

#include "./shy_creation_permit.h"

typedef shy_sender_common_logic_amusement_creation_permit so_called_sender_common_logic_amusement_creation_permit ;

#endif
