#ifndef _shy_common_logic_amusement_creation_permit_sender_injections_included
#define _shy_common_logic_amusement_creation_permit_sender_injections_included

#include "../../message/creation_permit/shy_creation_permit_injections.h"

#include "./shy_creation_permit.h"

typedef shy_common_logic_amusement_creation_permit_sender so_called_common_logic_amusement_creation_permit_sender ;

#endif
