const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: color_a ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: color_b ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: color_g ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: color_r ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: mesh_size ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: time_between_creation ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_meshes_consts :: time_between_destruction ;

void shy_common_logic_salutation_letters_meshes_consts :: binding ( )
{
}
