#include "./shy_consts_injections.h"

#ifdef shy_build_static_way
    #include "common/autogenerated/logic_salutation_letters_meshes_consts/shy_logic_salutation_letters_meshes_consts_injections.hpp"
#endif

#ifdef shy_build_loadable_way
    #include "./shy_consts.hpp"
#endif
