#ifndef _shy_common_engine_render_mesh_set_vertex_color_message_injections_included
#define _shy_common_engine_render_mesh_set_vertex_color_message_injections_included

#include "common/engine/render/type/mesh_id/shy_mesh_id_injections.h"
#include "injections/platform/math/type/num_fract/shy_num_fract.h"

#include "./shy_mesh_set_vertex_color.h"

typedef shy_common_engine_render_mesh_set_vertex_color_message so_called_common_engine_render_mesh_set_vertex_color_message ;

#endif
