#ifndef _shy_message_common_engine_render_mesh_set_triangle_strip_index_value_injections_included
#define _shy_message_common_engine_render_mesh_set_triangle_strip_index_value_injections_included

#include "../../shy_type_mesh_id_injections.h"

#include "./shy_mesh_set_triangle_strip_index_value.h"

typedef shy_message_common_engine_render_mesh_set_triangle_strip_index_value so_called_message_common_engine_render_mesh_set_triangle_strip_index_value ;

#endif
