#ifndef _shy_loadable_fsm_content_machine_container_type_injections_included
#define _shy_loadable_fsm_content_machine_container_type_injections_included

#include "src/loadable/fsm/content/machine/type/shy_type_injections.h"

#include "./shy_type.h"

typedef shy_loadable_fsm_content_machine_container_type so_called_loadable_fsm_content_machine_container_type ;

#endif
