#ifndef _shy_common_logic_entities_injections_included
#define _shy_common_logic_entities_injections_included

#include "shy_entities.h"

typedef shy_common_logic_entities_scheduled so_called_common_logic_entities ;

#endif
