#ifndef _shy_message_common_logic_salutation_letters_animation_disappear_play_injections_included
#define _shy_message_common_logic_salutation_letters_animation_disappear_play_injections_included

#include "./shy_play.h"

typedef shy_message_common_logic_salutation_letters_animation_disappear_play so_called_message_common_logic_salutation_letters_animation_disappear_play ;

#endif
