#ifndef _shy_common_logic_title_update_message_injections_included
#define _shy_common_logic_title_update_message_injections_included

#include "./shy_update.h"

typedef shy_common_logic_title_update_message so_called_common_logic_title_update_message ;

#endif
