#ifndef _shy_common_logic_room_texture_injections_included
#define _shy_common_logic_room_texture_injections_included

#include "shy_texture.h"

typedef shy_common_logic_room_texture_scheduled so_called_common_logic_room_texture ;

#endif
