#ifndef _shy_common_engine_rasterizer_use_texel_sender_injections_included
#define _shy_common_engine_rasterizer_use_texel_sender_injections_included

#include "common/engine/rasterizer/message/use_texel/shy_use_texel_injections.h"

#include "./shy_use_texel.h"

typedef shy_common_engine_rasterizer_use_texel_sender so_called_common_engine_rasterizer_use_texel_sender ;

#endif
