#ifndef _shy_iphone_platform_sound_loader_insider_injections_included
#define _shy_iphone_platform_sound_loader_insider_injections_included

#include "src/platform/sound/loader/cocoa/insider/shy_insider_injections.h"
typedef so_called_platform_sound_loader_cocoa_insider so_called_platform_sound_loader_insider ;

#endif
