#ifndef _shy_sender_common_logic_main_menu_letters_cols_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_cols_reply_injections_included

#include "../../message/cols_reply/shy_cols_reply_injections.h"

#include "./shy_cols_reply.h"

typedef shy_sender_common_logic_main_menu_letters_cols_reply so_called_sender_common_logic_main_menu_letters_cols_reply ;

#endif
