#ifndef _shy_common_logic_main_menu_letters_cols_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_cols_reply_sender_injections_included

#include "common/logic/main_menu/letters/message/cols_reply/shy_cols_reply_injections.h"

#include "./shy_cols_reply.h"

typedef shy_common_logic_main_menu_letters_cols_reply_sender so_called_common_logic_main_menu_letters_cols_reply_sender ;

#endif
