#ifndef _shy_common_logic_main_menu_letters_meshes_place_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_place_sender_injections_included

#include "common/logic/main_menu/letters/meshes/message/place/shy_place_injections.h"

#include "./shy_place.h"

typedef shy_common_logic_main_menu_letters_meshes_place_sender so_called_common_logic_main_menu_letters_meshes_place_sender ;

#endif
