#ifndef _shy_platform_sound_loader_cocoa_stereo_resource_id_type_injections_included
#define _shy_platform_sound_loader_cocoa_stereo_resource_id_type_injections_included

#include "injections/lib/std/int32_t/shy_int32_t.h"

#include "./shy_stereo_resource_id.h"

typedef shy_platform_sound_loader_cocoa_stereo_resource_id_type so_called_platform_sound_loader_cocoa_stereo_resource_id_type ;

#endif
