void shy_sender_common_init :: send ( so_called_message_common_init msg )
{
    so_called_common_engine_rasterizer :: receive ( msg ) ;
    so_called_common_engine_render :: receive ( msg ) ;
    so_called_common_logic_amusement :: receive ( msg ) ;
    so_called_common_logic_amusement_renderer :: receive ( msg ) ;
    so_called_common_logic_application_fsm :: receive ( msg ) ;
    so_called_common_logic_blanket :: receive ( msg ) ;
    so_called_common_logic_blanket_animation :: receive ( msg ) ;
    so_called_common_logic_blanket_animation_appear :: receive ( msg ) ;
    so_called_common_logic_blanket_animation_disappear :: receive ( msg ) ;
    so_called_common_logic_blanket_animation_fit :: receive ( msg ) ;
    so_called_common_logic_blanket_mesh :: receive ( msg ) ;
    so_called_common_logic_blanket_placement :: receive ( msg ) ;
    so_called_common_logic_blanket_renderer :: receive ( msg ) ;
    so_called_common_logic_camera :: receive ( msg ) ;
    so_called_common_logic_controls :: receive ( msg ) ;
    so_called_common_logic_core :: receive ( msg ) ;
    so_called_common_logic_door :: receive ( msg ) ;
    so_called_common_logic_door_animation :: receive ( msg ) ;
    so_called_common_logic_door_animation_appear :: receive ( msg ) ;
/*
    _receivers . get ( ) . logic_door_mesh . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_door_placement . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_door_renderer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_door_texture . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_entities . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_fidget . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_game . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_image . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_land . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_animation . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_animation_shake . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_choice . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_appear . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_disappear . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_idle . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_selection . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_selection_push . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_selection_weight . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_animation_unselection_weight . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_layout_position . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_layout_row_rect . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_storage . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_creation_director . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_creator . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_destroyer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_placement . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_renderer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_letters_meshes_storage . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_renderer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_appear . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_disappear . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_idle . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_idle_attention . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_push . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_push_attention . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_push_weight . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_select . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_animation_unselect . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_mesh . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_tracker . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_main_menu_selection_tracking_director . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_observer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_observer_animation . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_observer_animation_flight . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_ortho . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_perspective . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_room . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_room_mesh . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_room_renderer . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_room_texture . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_sound . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_text . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_title . get ( ) . receive ( msg ) ;
    _receivers . get ( ) . logic_touch . get ( ) . receive ( msg ) ;
*/
}
