#include "./shy_init_injections.h"

#include "../../engine/rasterizer/shy_rasterizer_injections.h"
#include "../../engine/render/shy_render_injections.h"
#include "../../logic/amusement/renderer/shy_renderer_injections.h"
#include "../../logic/amusement/shy_amusement_injections.h"
#include "../../logic/application/fsm/shy_fsm_injections.h"
#include "../../logic/blanket/animation/appear/shy_appear_injections.h"
#include "../../logic/blanket/animation/disappear/shy_disappear_injections.h"
#include "../../logic/blanket/animation/fit/shy_fit_injections.h"
#include "../../logic/blanket/animation/shy_animation_injections.h"
#include "../../logic/blanket/mesh/shy_mesh_injections.h"
#include "../../logic/blanket/placement/shy_placement_injections.h"
#include "../../logic/blanket/shy_blanket_injections.h"
#include "../../logic/core/shy_core_injections.h"

#include "./shy_init.hpp"
