// autogenerated file begin

const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: angle_delta = so_called_platform_math :: init_num_fract ( 125 , 1000 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: fidget_b = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: fidget_g = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: fidget_r = so_called_platform_math :: init_num_fract ( 1 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: fidget_size = so_called_platform_math :: init_num_fract ( 3 , 10 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: mesh_x = so_called_platform_math :: init_num_fract ( 0 , 1 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: mesh_y_from_top = so_called_platform_math :: init_num_fract ( 1 , 2 ) ;
const so_called_platform_math_num_fract_type so_called_common_logic_fidget_consts :: mesh_z = so_called_platform_math :: init_num_fract ( - 3 , 1 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_fidget_consts :: fidget_edges = so_called_platform_math :: init_num_whole ( 3 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_fidget_consts :: scale_in_frames = so_called_platform_math :: init_num_whole ( 60 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_fidget_consts :: should_render_fidget = so_called_platform_math :: init_num_whole ( 0 ) ;

// autogenerated file end
