#ifndef _shy_common_engine_rasterizer_draw_triangle_sender_injections_included
#define _shy_common_engine_rasterizer_draw_triangle_sender_injections_included

#include "common/engine/rasterizer/message/draw_triangle/shy_draw_triangle_injections.h"

#include "./shy_draw_triangle.h"

typedef shy_common_engine_rasterizer_draw_triangle_sender so_called_common_engine_rasterizer_draw_triangle_sender ;

#endif
