#ifndef _shy_sender_common_logic_salutation_animation_transform_request_injections_included
#define _shy_sender_common_logic_salutation_animation_transform_request_injections_included

#include "../message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_animation_transform_request so_called_sender_common_logic_salutation_animation_transform_request ;

#endif
