#ifndef _shy_common_logic_entities_mesh_grid_request_sender_injections_included
#define _shy_common_logic_entities_mesh_grid_request_sender_injections_included

#include "../../message/mesh_grid_request/shy_mesh_grid_request_injections.h"

#include "./shy_mesh_grid_request.h"

typedef shy_common_logic_entities_mesh_grid_request_sender so_called_common_logic_entities_mesh_grid_request_sender ;

#endif
