#ifndef _shy_sender_common_logic_entities_mesh_grid_request_injections_included
#define _shy_sender_common_logic_entities_mesh_grid_request_injections_included

#include "../../message/mesh_grid_request/shy_mesh_grid_request_injections.h"

#include "./shy_mesh_grid_request.h"

typedef shy_sender_common_logic_entities_mesh_grid_request so_called_sender_common_logic_entities_mesh_grid_request ;

#endif
