#include "./shy_main_menu_injections.h"

#include "common/logic/main_menu/letters/animation/sender/disappear_start/shy_disappear_start_injections.h"
#include "common/logic/main_menu/letters/meshes/sender/create/shy_create_injections.h"
#include "common/logic/main_menu/letters/meshes/sender/destroy_request/shy_destroy_request_injections.h"
#include "common/logic/main_menu/letters/meshes/sender/place/shy_place_injections.h"
#include "common/logic/main_menu/letters/sender/create/shy_create_injections.h"
#include "common/logic/main_menu/selection/animation/sender/disappear_start/shy_disappear_start_injections.h"
#include "common/logic/main_menu/selection/sender/mesh_create/shy_mesh_create_injections.h"
#include "common/logic/main_menu/selection/sender/mesh_destroy_request/shy_mesh_destroy_request_injections.h"
#include "common/logic/main_menu/selection/sender/mesh_place/shy_mesh_place_injections.h"
#include "common/logic/main_menu/selection/sender/tracking_director_update/shy_tracking_director_update_injections.h"
#include "common/logic/main_menu/sender/created/shy_created_injections.h"
#include "common/logic/main_menu/sender/finished/shy_finished_injections.h"
#include "common/logic/main_menu/sender/render_permit/shy_render_permit_injections.h"

#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/math/consts/shy_consts.h"

#include "./shy_main_menu.hpp"
