#ifndef _shy_message_common_logic_salutation_letters_text_storage_clean_injections_included
#define _shy_message_common_logic_salutation_letters_text_storage_clean_injections_included

#include "./shy_clean.h"

typedef shy_message_common_logic_salutation_letters_text_storage_clean so_called_message_common_logic_salutation_letters_text_storage_clean ;

#endif
