#include "./shy_facade_injections.h"

#include "src/common/init/sender/shy_sender_injections.h"
#include "src/common/init/shy_init_injections.h"
#include "src/common/done/sender/shy_sender_injections.h"
#include "src/common/done/shy_done_injections.h"
#include "src/common/next/frame/sender/shy_sender_injections.h"
#include "src/generator/shy_generator_injections.h"
#include "src/injections/platform/generator/shy_generator.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/profile/insider/shy_insider.h"
#include "src/injections/platform/profile/shy_profile.h"
#include "src/injections/platform/render/shy_render.h"
#include "src/injections/platform/render/texture/loader/shy_loader.h"
#include "src/injections/platform/scheduler/shy_scheduler.h"
#include "src/injections/platform/sound/loader/shy_loader.h"
#include "src/injections/platform/trace/insider/shy_insider.h"
#include "src/loadable/loader/shy_loader_injections.h"
#include "src/loadable/shy_loadable_injections.h"
#include "src/profile/init/shy_init_injections.h"
#include "src/profile/shy_profile_injections.h"
#include "src/trace/shy_trace_injections.h"

#include "./shy_facade.hpp"
