class shy_fsm_collection_autogenerated
{
public :
    template < typename logic_application_fsm >
    class logic_application_fsm_autogenerated
    {
    public :
        typedef shy_logic_application_fsm_autogenerated < logic_application_fsm > type ;
    } ;
} ;

template < typename platform >
class shy_facade_static
: public shy_facade_interface
{
    typedef typename platform :: platform_pointer platform_pointer ;
public :
    shy_facade_static ( typename platform_pointer :: template pointer < const platform > ) ;
    virtual ~ shy_facade_static ( ) ;
    virtual void init ( ) ;
    virtual void done ( ) ;
    virtual void render ( ) ;
    virtual void update ( ) ;
    virtual void video_mode_changed ( ) ;
private :
    shy_composer < platform , shy_fsm_collection_autogenerated > _composer ;
    shy_fsm_collection_autogenerated _fsm_collection ;
} ;

template < typename platform >
shy_facade_static < platform > :: shy_facade_static ( typename platform_pointer :: template pointer < const platform > platform_ptr )
{
    typename platform_pointer :: template pointer < shy_fsm_collection_autogenerated > fsm_collection_ptr ;
    platform_pointer :: bind ( fsm_collection_ptr , _fsm_collection ) ;
    _composer . register_components ( platform_ptr , fsm_collection_ptr ) ;
}

template < typename platform >
shy_facade_static < platform > :: ~ shy_facade_static ( )
{
}

template < typename platform >
void shy_facade_static < platform > :: init ( )
{
    _composer . init ( ) ;
}

template < typename platform >
void shy_facade_static < platform > :: done ( )
{
    _composer . done ( ) ;
}

template < typename platform >
void shy_facade_static < platform > :: update ( )
{
    _composer . update ( ) ;
}

template < typename platform >
void shy_facade_static < platform > :: render ( )
{
    _composer . render ( ) ;
}

template < typename platform >
void shy_facade_static < platform > :: video_mode_changed ( )
{
    _composer . video_mode_changed ( ) ;
}

