#ifndef _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message_injections_included
#define _shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_unselection_weight_select_row.h"

typedef shy_common_logic_main_menu_letters_animation_unselection_weight_select_row_message so_called_common_logic_main_menu_letters_animation_unselection_weight_select_row_message ;

#endif
