#ifndef _shy_iphone_platform_render_texture_id_type_injections_included
#define _shy_iphone_platform_render_texture_id_type_injections_included

#include "src/platform/render/opengl/texture/id/type/shy_type_injections.h"
typedef so_called_platform_render_opengl_texture_id_type so_called_platform_render_texture_id_type ;

#endif
