#ifndef _shy_sender_common_engine_rasterizer_finalize_reply_injections_included
#define _shy_sender_common_engine_rasterizer_finalize_reply_injections_included

#include "../../message/finalize_reply/shy_finalize_reply_injections.h"

#include "./shy_finalize_reply.h"

typedef shy_sender_common_engine_rasterizer_finalize_reply so_called_sender_common_engine_rasterizer_finalize_reply ;

#endif
