#ifndef _shy_common_logic_salutation_letters_text_storage_letter_checker_injections_included
#define _shy_common_logic_salutation_letters_text_storage_letter_checker_injections_included

#include "src/common/logic/salutation/letters/text/storage/letter/reply/message/shy_message_injections.h"
#include "src/common/logic/salutation/letters/text/storage/letter/request/message/shy_message_injections.h"

#include "./shy_checker.h"

typedef shy_common_logic_salutation_letters_text_storage_letter_checker so_called_common_logic_salutation_letters_text_storage_letter_checker ;

#endif
