#ifndef _shy_common_logic_main_menu_letters_cols_request_sender_injections_included
#define _shy_common_logic_main_menu_letters_cols_request_sender_injections_included

#include "../../message/cols_request/shy_cols_request_injections.h"

#include "./shy_cols_request.h"

typedef shy_common_logic_main_menu_letters_cols_request_sender so_called_common_logic_main_menu_letters_cols_request_sender ;

#endif
