#ifndef _shy_sender_common_logic_main_menu_letters_cols_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_cols_request_injections_included

#include "../../message/cols_request/shy_cols_request_injections.h"

#include "./shy_cols_request.h"

typedef shy_sender_common_logic_main_menu_letters_cols_request so_called_sender_common_logic_main_menu_letters_cols_request ;

#endif
