#ifndef _shy_sender_common_logic_main_menu_selection_animation_unselect_start_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_unselect_start_injections_included

#include "../../message/unselect_start/shy_unselect_start_injections.h"

#include "./shy_unselect_start.h"

typedef shy_sender_common_logic_main_menu_selection_animation_unselect_start so_called_sender_common_logic_main_menu_selection_animation_unselect_start ;

#endif
