#ifndef _shy_common_logic_main_menu_selection_animation_unselect_start_sender_injections_included
#define _shy_common_logic_main_menu_selection_animation_unselect_start_sender_injections_included

#include "../../message/unselect_start/shy_unselect_start_injections.h"

#include "./shy_unselect_start.h"

typedef shy_common_logic_main_menu_selection_animation_unselect_start_sender so_called_common_logic_main_menu_selection_animation_unselect_start_sender ;

#endif
