#ifndef _shy_common_logic_main_menu_letters_meshes_creator_injections_included
#define _shy_common_logic_main_menu_letters_meshes_creator_injections_included

#include "shy_meshes_creator.h"

typedef shy_common_logic_main_menu_letters_meshes_creator_scheduled so_called_common_logic_main_menu_letters_meshes_creator ;

#endif
