#ifndef _shy_common_logic_main_menu_selection_animation_select_finished_sender_injections_included
#define _shy_common_logic_main_menu_selection_animation_select_finished_sender_injections_included

#include "common/logic/main_menu/selection/animation/message/select_finished/shy_select_finished_injections.h"

#include "./shy_select_finished.h"

typedef shy_common_logic_main_menu_selection_animation_select_finished_sender so_called_common_logic_main_menu_selection_animation_select_finished_sender ;

#endif
