#ifndef _shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_request_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_request_injections_included

#include "../../message/mesh_row_col_request/shy_mesh_row_col_request_injections.h"

#include "./shy_mesh_row_col_request.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_mesh_row_col_request so_called_sender_common_logic_main_menu_letters_meshes_mesh_row_col_request ;

#endif
