#ifndef _shy_sender_common_logic_observer_animation_flight_transform_reply_injections_included
#define _shy_sender_common_logic_observer_animation_flight_transform_reply_injections_included

#include "../../message/flight_transform_reply/shy_flight_transform_reply_injections.h"

#include "./shy_flight_transform_reply.h"

typedef shy_sender_common_logic_observer_animation_flight_transform_reply so_called_sender_common_logic_observer_animation_flight_transform_reply ;

#endif
