#ifndef _shy_win_platform_math_num_fract_type_injections_included
#define _shy_win_platform_math_num_fract_type_injections_included

#include "src/platform/math/int/float/num/fract/type/shy_type_injections.h"
typedef so_called_platform_math_int_float_num_fract_type so_called_platform_math_num_fract_type ;

#endif
