#ifndef _shy_iphone_platform_sound_source_id_type_injections_included
#define _shy_iphone_platform_sound_source_id_type_injections_included

#include "src/platform/sound/openal/source/id/type/shy_type_injections.h"
typedef so_called_platform_sound_openal_source_id_type so_called_platform_sound_source_id_type ;

#endif

