#ifndef _shy_type_loadable_fsm_content_transition_injections_included
#define _shy_type_loadable_fsm_content_transition_injections_included

#include "../condition_group_container/shy_condition_group_container_injections.h"

#include "./shy_transition.h"

typedef shy_type_loadable_fsm_content_transition so_called_type_loadable_fsm_content_transition ;

#endif
