#ifndef _shy_message_common_engine_render_projection_ortho_injections_included
#define _shy_message_common_engine_render_projection_ortho_injections_included

#include "shy_message_projection_ortho.h"

typedef shy_message_common_engine_render_projection_ortho so_called_message_common_engine_render_projection_ortho ;

#endif
