#ifndef _shy_message_common_engine_render_mesh_set_vertex_tex_coord_injections_included
#define _shy_message_common_engine_render_mesh_set_vertex_tex_coord_injections_included

#include "shy_message_mesh_set_vertex_tex_coord.h"

typedef shy_message_common_engine_render_mesh_set_vertex_tex_coord so_called_message_common_engine_render_mesh_set_vertex_tex_coord ;

#endif
