#ifndef _shy_message_common_engine_render_disable_depth_test_included
#define _shy_message_common_engine_render_disable_depth_test_included

class shy_message_common_engine_render_disable_depth_test
{
} ;

#endif
