#ifndef _shy_message_common_engine_render_texture_load_from_resource_injections_included
#define _shy_message_common_engine_render_texture_load_from_resource_injections_included

#include "../../../injections/shy_type_platform_render_texture_resource_id.h"

#include "shy_message_texture_load_from_resource.h"

typedef shy_message_common_engine_render_texture_load_from_resource so_called_message_common_engine_render_texture_load_from_resource ;

#endif
