#ifndef _shy_message_common_engine_render_texture_set_texels_rect_injections_included
#define _shy_message_common_engine_render_texture_set_texels_rect_injections_included

#include "shy_message_texture_set_texels_rect.h"

typedef shy_message_common_engine_render_texture_set_texels_rect so_called_message_common_engine_render_texture_set_texels_rect ;

#endif
