#ifndef _shy_message_common_engine_render_projection_frustum_injections_included
#define _shy_message_common_engine_render_projection_frustum_injections_included

#include "shy_message_projection_frustum.h"

typedef shy_message_common_engine_render_projection_frustum so_called_message_common_engine_render_projection_frustum ;

#endif
