#ifndef _shy_message_common_engine_render_texture_set_texel_rgba_injections_included
#define _shy_message_common_engine_render_texture_set_texel_rgba_injections_included

#include "shy_message_texture_set_texel_rgba.h"

typedef shy_message_common_engine_render_texture_set_texel_rgba so_called_message_common_engine_render_texture_set_texel_rgba ;

#endif
