#ifndef _shy_sender_common_engine_render_aspect_request_injections_included
#define _shy_sender_common_engine_render_aspect_request_injections_included

#include "shy_message_aspect_request_injections.h"

#include "shy_sender_aspect_request.h"

typedef shy_sender_common_engine_render_aspect_request so_called_sender_common_engine_render_aspect_request ;

#endif

