#ifndef _shy_sender_common_engine_render_texture_select_injections_included
#define _shy_sender_common_engine_render_texture_select_injections_included

#include "shy_message_texture_select_injections.h"

#include "shy_sender_texture_select.h"

typedef shy_sender_common_engine_render_texture_select so_called_sender_common_engine_render_texture_select ;

#endif

