#include "../../../injections/shy_type_platform_math_num_fract.h"
#include "../../../injections/shy_type_platform_math_num_whole.h"
#include "../../../injections/shy_type_platform_matrix_data.h"
#include "../../../injections/shy_type_platform_render_texel_data.h"
#include "../../../injections/shy_type_platform_render_texture_resource_id.h"

#include "shy_type_mesh_id.h"
#include "shy_type_texture_id.h"

typedef shy_type_common_engine_render_mesh_id so_called_type_common_engine_render_mesh_id ;
typedef shy_type_common_engine_render_texture_id so_called_type_common_engine_render_texture_id ;

#include "shy_message_aspect_reply.h"
#include "shy_message_aspect_request.h"
#include "shy_message_blend_disable.h"
#include "shy_message_blend_src_alpha_dst_one_minus_alpha.h"
#include "shy_message_clear_screen.h"
#include "shy_message_disable_depth_test.h"
#include "shy_message_enable_depth_test.h"
#include "shy_message_enable_face_culling.h"
#include "shy_message_fog_disable.h"
#include "shy_message_fog_linear.h"
#include "shy_message_frame_loss_reply.h"
#include "shy_message_frame_loss_request.h"
#include "shy_message_matrix_identity.h"
#include "shy_message_matrix_load.h"
#include "shy_message_matrix_mult.h"
#include "shy_message_mesh_create_reply.h"
#include "shy_message_mesh_create_request.h"
#include "shy_message_mesh_delete.h"
#include "shy_message_mesh_finalize.h"
#include "shy_message_mesh_render.h"
#include "shy_message_mesh_set_transform.h"
#include "shy_message_mesh_set_triangle_fan_index_value.h"
#include "shy_message_mesh_set_triangle_strip_index_value.h"
#include "shy_message_mesh_set_vertex_color.h"
#include "shy_message_mesh_set_vertex_position.h"
#include "shy_message_mesh_set_vertex_tex_coord.h"
#include "shy_message_projection_frustum.h"
#include "shy_message_projection_ortho.h"
#include "shy_message_texture_create_reply.h"
#include "shy_message_texture_create_request.h"
#include "shy_message_texture_finalize.h"
#include "shy_message_texture_load_from_resource.h"
#include "shy_message_texture_loader_ready_reply.h"
#include "shy_message_texture_loader_ready_request.h"
#include "shy_message_texture_mode_modulate.h"
#include "shy_message_texture_select.h"
#include "shy_message_texture_set_texel.h"
#include "shy_message_texture_set_texel_rgba.h"
#include "shy_message_texture_set_texels_rect.h"
#include "shy_message_texture_unselect.h"

typedef shy_message_common_engine_render_aspect_reply so_called_message_common_engine_render_aspect_reply ;
typedef shy_message_common_engine_render_aspect_request so_called_message_common_engine_render_aspect_request ;
typedef shy_message_common_engine_render_blend_disable so_called_message_common_engine_render_blend_disable ;
typedef shy_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha so_called_message_common_engine_render_blend_src_alpha_dst_one_minus_alpha ;
typedef shy_message_common_engine_render_clear_screen so_called_message_common_engine_render_clear_screen ;
typedef shy_message_common_engine_render_disable_depth_test so_called_message_common_engine_render_disable_depth_test ;
typedef shy_message_common_engine_render_enable_depth_test so_called_message_common_engine_render_enable_depth_test ;
typedef shy_message_common_engine_render_enable_face_culling so_called_message_common_engine_render_enable_face_culling ;
typedef shy_message_common_engine_render_fog_disable so_called_message_common_engine_render_fog_disable ;
typedef shy_message_common_engine_render_fog_linear so_called_message_common_engine_render_fog_linear ;
typedef shy_message_common_engine_render_frame_loss_reply so_called_message_common_engine_render_frame_loss_reply ;
typedef shy_message_common_engine_render_frame_loss_request so_called_message_common_engine_render_frame_loss_request ;
typedef shy_message_common_engine_render_matrix_identity so_called_message_common_engine_render_matrix_identity ;
typedef shy_message_common_engine_render_matrix_load so_called_message_common_engine_render_matrix_load ;
typedef shy_message_common_engine_render_matrix_mult so_called_message_common_engine_render_matrix_mult ;
typedef shy_message_common_engine_render_mesh_create_reply so_called_message_common_engine_render_mesh_create_reply ;
typedef shy_message_common_engine_render_mesh_create_request so_called_message_common_engine_render_mesh_create_request ;
typedef shy_message_common_engine_render_mesh_delete so_called_message_common_engine_render_mesh_delete ;
typedef shy_message_common_engine_render_mesh_finalize so_called_message_common_engine_render_mesh_finalize ;
typedef shy_message_common_engine_render_mesh_render so_called_message_common_engine_render_mesh_render ;
typedef shy_message_common_engine_render_mesh_set_transform so_called_message_common_engine_render_mesh_set_transform ;
typedef shy_message_common_engine_render_mesh_set_triangle_fan_index_value so_called_message_common_engine_render_mesh_set_triangle_fan_index_value ;
typedef shy_message_common_engine_render_mesh_set_triangle_strip_index_value so_called_message_common_engine_render_mesh_set_triangle_strip_index_value ;
typedef shy_message_common_engine_render_mesh_set_vertex_color so_called_message_common_engine_render_mesh_set_vertex_color ;
typedef shy_message_common_engine_render_mesh_set_vertex_position so_called_message_common_engine_render_mesh_set_vertex_position ;
typedef shy_message_common_engine_render_mesh_set_vertex_tex_coord so_called_message_common_engine_render_mesh_set_vertex_tex_coord ;
typedef shy_message_common_engine_render_projection_frustum so_called_message_common_engine_render_projection_frustum ;
typedef shy_message_common_engine_render_projection_ortho so_called_message_common_engine_render_projection_ortho ;
typedef shy_message_common_engine_render_texture_create_reply so_called_message_common_engine_render_texture_create_reply ;
typedef shy_message_common_engine_render_texture_create_request so_called_message_common_engine_render_texture_create_request ;
typedef shy_message_common_engine_render_texture_finalize so_called_message_common_engine_render_texture_finalize ;
typedef shy_message_common_engine_render_texture_load_from_resource so_called_message_common_engine_render_texture_load_from_resource ;
typedef shy_message_common_engine_render_texture_loader_ready_reply so_called_message_common_engine_render_texture_loader_ready_reply ;
typedef shy_message_common_engine_render_texture_loader_ready_request so_called_message_common_engine_render_texture_loader_ready_request ;
typedef shy_message_common_engine_render_texture_mode_modulate so_called_message_common_engine_render_texture_mode_modulate ;
typedef shy_message_common_engine_render_texture_select so_called_message_common_engine_render_texture_select ;
typedef shy_message_common_engine_render_texture_set_texel so_called_message_common_engine_render_texture_set_texel ;
typedef shy_message_common_engine_render_texture_set_texel_rgba so_called_message_common_engine_render_texture_set_texel_rgba ;
typedef shy_message_common_engine_render_texture_set_texels_rect so_called_message_common_engine_render_texture_set_texels_rect ;
typedef shy_message_common_engine_render_texture_unselect so_called_message_common_engine_render_texture_unselect ;

#include "../../../injections/shy_platform_static_assert.h"
#include "../../../injections/shy_platform_scheduler.h"
#include "shy_render.h"
typedef shy_common_engine_render so_called_common_engine_render ;

#include "shy_sender.hpp"

