#ifndef _shy_sender_common_engine_render_aspect_reply_injections_included
#define _shy_sender_common_engine_render_aspect_reply_injections_included

#include "shy_message_aspect_reply_injections.h"

#include "shy_sender_aspect_reply.h"

typedef shy_sender_common_engine_render_aspect_reply so_called_sender_common_engine_render_aspect_reply ;

#endif

