#ifndef _shy_sender_common_engine_render_fog_disable_injections_included
#define _shy_sender_common_engine_render_fog_disable_injections_included

#include "shy_message_fog_disable_injections.h"

#include "shy_sender_fog_disable.h"

typedef shy_sender_common_engine_render_fog_disable so_called_sender_common_engine_render_fog_disable ;

#endif

