#ifndef _shy_message_common_engine_render_fog_linear_injections_included
#define _shy_message_common_engine_render_fog_linear_injections_included

#include "shy_message_fog_linear.h"

typedef shy_message_common_engine_render_fog_linear so_called_message_common_engine_render_fog_linear ;

#endif
