#ifndef _shy_sender_common_engine_render_clear_screen_injections_included
#define _shy_sender_common_engine_render_clear_screen_injections_included

#include "shy_message_clear_screen_injections.h"

#include "shy_sender_clear_screen.h"

typedef shy_sender_common_engine_render_clear_screen so_called_sender_common_engine_render_clear_screen ;

#endif

