#ifndef _shy_sender_common_engine_render_matrix_identity_injections_included
#define _shy_sender_common_engine_render_matrix_identity_injections_included

#include "shy_message_matrix_identity_injections.h"

#include "shy_sender_matrix_identity.h"

typedef shy_sender_common_engine_render_matrix_identity so_called_sender_common_engine_render_matrix_identity ;

#endif

