#ifndef _shy_message_common_engine_render_texture_select_injections_included
#define _shy_message_common_engine_render_texture_select_injections_included

#include "shy_message_texture_select.h"

typedef shy_message_common_engine_render_texture_select so_called_message_common_engine_render_texture_select ;

#endif
