#ifndef _shy_message_common_engine_render_mesh_set_vertex_color_injections_included
#define _shy_message_common_engine_render_mesh_set_vertex_color_injections_included

#include "shy_type_mesh_id_injections.h"
#include "../../../injections/shy_type_platform_math_num_fract.h"

#include "shy_message_mesh_set_vertex_color.h"

typedef shy_message_common_engine_render_mesh_set_vertex_color so_called_message_common_engine_render_mesh_set_vertex_color ;

#endif
