#ifndef _shy_type_common_engine_render_texture_id_injections_included
#define _shy_type_common_engine_render_texture_id_injections_included

#include "shy_type_texture_id.h"

typedef shy_type_common_engine_render_texture_id so_called_type_common_engine_render_texture_id ;

#endif
