#ifndef _shy_message_common_engine_render_aspect_request_injections_included
#define _shy_message_common_engine_render_aspect_request_injections_included

#include "shy_message_aspect_request.h"

typedef shy_message_common_engine_render_aspect_request so_called_message_common_engine_render_aspect_request ;

#endif
