#ifndef _shy_sender_common_engine_render_texture_load_from_resource_injections_included
#define _shy_sender_common_engine_render_texture_load_from_resource_injections_included

#include "shy_message_texture_load_from_resource_injections.h"

#include "shy_sender_texture_load_from_resource.h"

typedef shy_sender_common_engine_render_texture_load_from_resource so_called_sender_common_engine_render_texture_load_from_resource ;

#endif

