#ifndef _shy_sender_common_engine_render_mesh_set_vertex_position_injections_included
#define _shy_sender_common_engine_render_mesh_set_vertex_position_injections_included

#include "shy_message_mesh_set_vertex_position_injections.h"

#include "shy_sender_mesh_set_vertex_position.h"

typedef shy_sender_common_engine_render_mesh_set_vertex_position so_called_sender_common_engine_render_mesh_set_vertex_position ;

#endif

