#ifndef _shy_sender_common_engine_render_mesh_finalize_injections_included
#define _shy_sender_common_engine_render_mesh_finalize_injections_included

#include "shy_message_mesh_finalize_injections.h"

#include "shy_sender_mesh_finalize.h"

typedef shy_sender_common_engine_render_mesh_finalize so_called_sender_common_engine_render_mesh_finalize ;

#endif

