#ifndef _shy_sender_common_engine_render_fog_linear_injections_included
#define _shy_sender_common_engine_render_fog_linear_injections_included

#include "shy_message_fog_linear_injections.h"

#include "shy_sender_fog_linear.h"

typedef shy_sender_common_engine_render_fog_linear so_called_sender_common_engine_render_fog_linear ;

#endif

