#ifndef _shy_message_common_engine_render_mesh_finalize_injections_included
#define _shy_message_common_engine_render_mesh_finalize_injections_included

#include "shy_message_mesh_finalize.h"

typedef shy_message_common_engine_render_mesh_finalize so_called_message_common_engine_render_mesh_finalize ;

#endif
