#ifndef _shy_sender_common_engine_render_matrix_mult_injections_included
#define _shy_sender_common_engine_render_matrix_mult_injections_included

#include "shy_message_matrix_mult_injections.h"

#include "shy_sender_matrix_mult.h"

typedef shy_sender_common_engine_render_matrix_mult so_called_common_engine_render_matrix_mult ;

#endif

