#ifndef _shy_sender_common_engine_render_mesh_set_transform_injections_included
#define _shy_sender_common_engine_render_mesh_set_transform_injections_included

#include "shy_message_mesh_set_transform_injections.h"

#include "shy_sender_mesh_set_transform.h"

typedef shy_sender_common_engine_render_mesh_set_transform so_called_sender_common_engine_render_mesh_set_transform ;

#endif

