#ifndef _shy_message_common_engine_render_texture_set_texel_injections_included
#define _shy_message_common_engine_render_texture_set_texel_injections_included

#include "../../../injections/shy_type_platform_render_texel_data.h"

#include "shy_message_texture_set_texel.h"

typedef shy_message_common_engine_render_texture_set_texel so_called_message_common_engine_render_texture_set_texel ;

#endif
