#ifndef _shy_message_common_engine_render_texture_create_request_injections_included
#define _shy_message_common_engine_render_texture_create_request_injections_included

#include "shy_message_texture_create_request.h"

typedef shy_message_common_engine_render_texture_create_request so_called_message_common_engine_render_texture_create_request ;

#endif
