#ifndef _shy_message_common_engine_render_mesh_set_transform_injections_included
#define _shy_message_common_engine_render_mesh_set_transform_injections_included

#include "shy_message_mesh_set_transform.h"

typedef shy_message_common_engine_render_mesh_set_transform so_called_message_common_engine_render_mesh_set_transform ;

#endif
