#ifndef _shy_sender_common_engine_render_texture_mode_modulate_injections_included
#define _shy_sender_common_engine_render_texture_mode_modulate_injections_included

#include "shy_message_texture_mode_modulate_injections.h"

#include "shy_sender_texture_mode_modulate.h"

typedef shy_sender_common_engine_render_texture_mode_modulate so_called_sender_common_engine_render_texture_mode_modulate ;

#endif

