#ifndef _shy_message_common_engine_render_texture_loader_ready_request_injections_included
#define _shy_message_common_engine_render_texture_loader_ready_request_injections_included

#include "shy_message_texture_loader_ready_request.h"

typedef shy_message_common_engine_render_texture_loader_ready_request so_called_message_common_engine_render_texture_loader_ready_request ;

#endif
