#ifndef _shy_message_common_engine_render_mesh_set_vertex_position_injections_included
#define _shy_message_common_engine_render_mesh_set_vertex_position_injections_included

#include "shy_message_mesh_set_vertex_position.h"

typedef shy_message_common_engine_render_mesh_set_vertex_position so_called_message_common_engine_render_mesh_set_vertex_position ;

#endif
