#ifndef _shy_iphone_platform_math_num_whole_type_injections_included
#define _shy_iphone_platform_math_num_whole_type_injections_included

#include "platform/math/int_float/type/num_whole/shy_num_whole_injections.h"
typedef so_called_platform_math_int_float_num_whole_type so_called_platform_math_num_whole_type ;

#endif

