#ifndef _shy_type_loadable_fsm_content_action_discard_injections_included
#define _shy_type_loadable_fsm_content_action_discard_injections_included

#include "./shy_action_discard.h"

typedef shy_type_loadable_fsm_content_action_discard so_called_type_loadable_fsm_content_action_discard ;

#endif
