#ifndef _shy_loadable_fsm_content_action_discard_type_injections_included
#define _shy_loadable_fsm_content_action_discard_type_injections_included

#include "./shy_action_discard.h"

typedef shy_loadable_fsm_content_action_discard_type so_called_loadable_fsm_content_action_discard_type ;

#endif
