#ifndef _shy_common_logic_salutation_animation_zoom_transform_reply_message_injections_included
#define _shy_common_logic_salutation_animation_zoom_transform_reply_message_injections_included

#include "injections/platform/math/type/num_fract/shy_num_fract.h"
#include "./shy_message.h"

typedef shy_common_logic_salutation_animation_zoom_transform_reply_message so_called_common_logic_salutation_animation_zoom_transform_reply_message ;

#endif
