#ifndef _shy_common_logic_font_mesh_generator_generate_finished_sender_injections_included
#define _shy_common_logic_font_mesh_generator_generate_finished_sender_injections_included

#include "src/common/logic/font/mesh/generator/generate/finished/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_font_mesh_generator_generate_finished_sender so_called_common_logic_font_mesh_generator_generate_finished_sender ;

#endif
