#ifndef _shy_common_logic_main_menu_selection_mesh_place_sender_injections_included
#define _shy_common_logic_main_menu_selection_mesh_place_sender_injections_included

#include "common/logic/main_menu/selection/message/mesh_place/shy_mesh_place_injections.h"

#include "./shy_mesh_place.h"

typedef shy_common_logic_main_menu_selection_mesh_place_sender so_called_common_logic_main_menu_selection_mesh_place_sender ;

#endif
