#ifndef _shy_type_win_platform_render_texel_data_injections_included
#define _shy_type_win_platform_render_texel_data_injections_included

#include "platform/render/directx/type/texel_data/shy_texel_data_injections.h"
typedef so_called_type_platform_render_directx_texel_data so_called_type_platform_render_texel_data ;

#endif

