#ifndef _shy_win_platform_render_injections_included
#define _shy_win_platform_render_injections_included

#include "src/platform/render/directx/shy_directx_injections.h"
typedef so_called_platform_render_directx so_called_platform_render ;

#endif
