#ifndef _shy_sender_common_logic_main_menu_selection_animation_idle_row_selected_injections_included
#define _shy_sender_common_logic_main_menu_selection_animation_idle_row_selected_injections_included

#include "../../message/idle_row_selected/shy_idle_row_selected_injections.h"

#include "./shy_idle_row_selected.h"

typedef shy_sender_common_logic_main_menu_selection_animation_idle_row_selected so_called_sender_common_logic_main_menu_selection_animation_idle_row_selected ;

#endif
