#ifndef _shy_message_common_logic_main_menu_letters_meshes_place_injections_included
#define _shy_message_common_logic_main_menu_letters_meshes_place_injections_included

#include "./shy_place.h"

typedef shy_message_common_logic_main_menu_letters_meshes_place so_called_message_common_logic_main_menu_letters_meshes_place ;

#endif
