#ifndef _shy_message_common_logic_blanket_animation_disappear_finished_injections_included
#define _shy_message_common_logic_blanket_animation_disappear_finished_injections_included

#include "./shy_disappear_finished.h"

typedef shy_message_common_logic_blanket_animation_disappear_finished so_called_message_common_logic_blanket_animation_disappear_finished ;

#endif
