const so_called_platform_math_num_fract_type shy_common_logic_main_menu_animation_consts :: shake_shift_x_amplitude_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_animation_consts :: shake_shift_x_amplitude_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_animation_consts :: shake_shift_x_period_in_seconds ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_animation_consts :: shake_time_from_begin_to_end ;
const so_called_platform_math_num_fract_type shy_common_logic_main_menu_animation_consts :: shake_time_to_begin ;

void shy_common_logic_main_menu_animation_consts :: binding ( )
{
}
