#ifndef _shy_loadable_fsm_content_action_discard_container_type_injections_included
#define _shy_loadable_fsm_content_action_discard_container_type_injections_included

#include "loadable/fsm/content/type/action_discard/shy_action_discard_injections.h"

#include "./shy_action_discard_container.h"

typedef shy_loadable_fsm_content_action_discard_container_type so_called_loadable_fsm_content_action_discard_container_type ;

#endif
