#ifndef _shy_common_logic_blanket_animation_disappear_transform_request_sender_injections_included
#define _shy_common_logic_blanket_animation_disappear_transform_request_sender_injections_included

#include "../../message/disappear_transform_request/shy_disappear_transform_request_injections.h"

#include "./shy_disappear_transform_request.h"

typedef shy_common_logic_blanket_animation_disappear_transform_request_sender so_called_common_logic_blanket_animation_disappear_transform_request_sender ;

#endif
