#include "./shy_generator_injections.h"

#include "src/common/engine/math/stateless/shy_stateless_injections.h"
#include "src/common/engine/taker/helper/shy_helper_injections.h"
#include "src/common/logic/salutation/letters/meshes/consts/shy_consts_injections.h"
#include "src/common/logic/salutation/letters/meshes/creator/create/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/meshes/creator/create/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/meshes/generator/generate/finished/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/text/storage/size/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/text/storage/size/request/sender/shy_sender_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"

#include "./shy_generator.hpp"
