#include "./shy_generator_injections.h"

#include "common/engine/taker/helper/shy_helper_injections.h"
#include "common/logic/salutation/letters/meshes/consts/shy_consts_injections.h"
#include "common/logic/salutation/letters/meshes/creator/create/checker/shy_checker_injections.h"
#include "common/logic/salutation/letters/meshes/creator/create/request/sender/shy_sender_injections.h"
#include "common/logic/salutation/letters/meshes/generator/generate/finished/sender/shy_sender_injections.h"
#include "common/logic/salutation/letters/text/storage/size/checker/shy_checker_injections.h"
#include "common/logic/salutation/letters/text/storage/size/request/sender/shy_sender_injections.h"
#include "injections/platform/conditions/shy_conditions.h"
#include "injections/platform/consts/shy_consts.h"
#include "injections/platform/math/consts/shy_consts.h"
#include "injections/platform/math/shy_math.h"

#include "./shy_generator.hpp"
