#ifndef _shy_common_engine_render_mesh_set_vertex_position_sender_injections_included
#define _shy_common_engine_render_mesh_set_vertex_position_sender_injections_included

#include "src/common/engine/render/mesh/set/vertex/position/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_render_mesh_set_vertex_position_sender so_called_common_engine_render_mesh_set_vertex_position_sender ;

#endif

