#ifndef _shy_message_common_logic_door_creation_finished_injections_included
#define _shy_message_common_logic_door_creation_finished_injections_included

#include "./shy_creation_finished.h"

typedef shy_message_common_logic_door_creation_finished so_called_message_common_logic_door_creation_finished ;

#endif
