#ifndef _shy_common_logic_door_creation_finished_message_injections_included
#define _shy_common_logic_door_creation_finished_message_injections_included

#include "./shy_creation_finished.h"

typedef shy_common_logic_door_creation_finished_message so_called_common_logic_door_creation_finished_message ;

#endif
