#ifndef _shy_message_common_logic_main_menu_selection_animation_unselect_start_injections_included
#define _shy_message_common_logic_main_menu_selection_animation_unselect_start_injections_included

#include "./shy_unselect_start.h"

typedef shy_message_common_logic_main_menu_selection_animation_unselect_start so_called_message_common_logic_main_menu_selection_animation_unselect_start ;

#endif
