#ifndef _shy_message_common_logic_main_menu_letters_meshes_count_request_injections_included
#define _shy_message_common_logic_main_menu_letters_meshes_count_request_injections_included

#include "./shy_count_request.h"

typedef shy_message_common_logic_main_menu_letters_meshes_count_request so_called_message_common_logic_main_menu_letters_meshes_count_request ;

#endif
