const so_called_std_string shy_loadable_generator_consts :: autogenerated_folder_path = "../common/autogenerated_test/" ;
const so_called_std_string shy_loadable_generator_consts :: whitespace = " " ;

