const so_called_lib_std_string shy_loadable_generator_consts :: autogenerated_folder_path = "../../common/autogenerated/" ;
const so_called_lib_std_string shy_loadable_generator_consts :: new_line = "\n" ;
const so_called_lib_std_string shy_loadable_generator_consts :: whitespace = " " ;

