#ifndef _shy_common_logic_main_menu_selection_animation_consts_injections_included
#define _shy_common_logic_main_menu_selection_animation_consts_injections_included

#include "src/injections/platform/math/num/fract/type/shy_type.h"

#include "./shy_consts.h"

typedef shy_common_logic_main_menu_selection_animation_consts so_called_common_logic_main_menu_selection_animation_consts ;

#endif
