#ifndef _shy_type_loadable_consts_content_module_injections_included
#define _shy_type_loadable_consts_content_module_injections_included

#include "./shy_module.h"

typedef shy_type_loadable_consts_content_module so_called_type_loadable_consts_content_module ;

#endif
