// autogenerated file begin

template < typename mediator >
shy_logic_amusement_stateless < mediator >
:: logic_amusement_stateless_consts_type 
:: logic_amusement_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( renderer_clear_color_b , 1 , 3 ) ;
    platform_math :: make_num_fract ( renderer_clear_color_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( renderer_clear_color_r , 0 , 1 ) ;
}

template < typename mediator >
shy_logic_blanket_animation_stateless < mediator >
:: logic_blanket_animation_stateless_consts_type 
:: logic_blanket_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( animation_origin_x , 0 , 1 ) ;
    platform_math :: make_num_fract ( animation_origin_y , 0 , 1 ) ;
    platform_math :: make_num_fract ( animation_origin_z , - 3 , 1 ) ;
    platform_math :: make_num_fract ( appear_rotation_begin , 0 , 1 ) ;
    platform_math :: make_num_fract ( appear_rotation_end , 10 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_begin , 0 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( appear_time_from_begin_to_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( disappear_rotation_begin , 0 , 1 ) ;
    platform_math :: make_num_fract ( disappear_rotation_end , 10 , 1 ) ;
    platform_math :: make_num_fract ( disappear_scale_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( disappear_scale_end , 0 , 1 ) ;
    platform_math :: make_num_fract ( disappear_time_from_begin_to_end , 1 , 1 ) ;
}

template < typename mediator >
shy_logic_blanket_stateless < mediator >
:: logic_blanket_stateless_consts_type 
:: logic_blanket_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( mesh_color_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_vertex_x_left , - 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_vertex_x_right , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_vertex_y_bottom , - 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_vertex_y_top , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_vertex_z , 0 , 1 ) ;
}

template < typename mediator >
shy_logic_door_animation_stateless < mediator >
:: logic_door_animation_stateless_consts_type 
:: logic_door_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( animation_origin_x , 0 , 1 ) ;
    platform_math :: make_num_fract ( animation_origin_y , 0 , 1 ) ;
    platform_math :: make_num_fract ( animation_origin_z , - 3 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_begin , 0 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( appear_time_from_begin_to_end , 2 , 1 ) ;
}

template < typename mediator >
shy_logic_door_stateless < mediator >
:: logic_door_stateless_consts_type 
:: logic_door_stateless_consts_type ( )
{
    platform_math :: make_num_whole ( texture_stripes , 9 ) ;
    platform_math :: make_num_fract ( mesh_color_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_b , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_r , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_u_bottom_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_u_bottom_right , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_u_top_left , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_u_top_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_v_bottom_left , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_v_bottom_right , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_v_top_left , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_v_top_right , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_x_left , - 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_x_right , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_y_bottom , - 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_y_top , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_z , 0 , 1 ) ;
    platform_math :: make_num_fract ( texture_paper_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( texture_paper_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( texture_paper_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( texture_paper_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( texture_pen_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( texture_pen_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( texture_pen_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( texture_pen_r , 1 , 1 ) ;
}

template < typename mediator >
shy_logic_fidget_stateless < mediator >
:: logic_fidget_stateless_consts_type 
:: logic_fidget_stateless_consts_type ( )
{
    platform_math :: make_num_whole ( fidget_edges , 3 ) ;
    platform_math :: make_num_whole ( scale_in_frames , 60 ) ;
    platform_math :: make_num_whole ( should_render_fidget , 0 ) ;
    platform_math :: make_num_fract ( angle_delta , 125 , 1000 ) ;
    platform_math :: make_num_fract ( fidget_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( fidget_g , 1 , 2 ) ;
    platform_math :: make_num_fract ( fidget_r , 1 , 1 ) ;
    platform_math :: make_num_fract ( fidget_size , 3 , 10 ) ;
    platform_math :: make_num_fract ( mesh_x , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_y_from_top , 1 , 2 ) ;
    platform_math :: make_num_fract ( mesh_z , - 3 , 1 ) ;
}

template < typename mediator >
shy_logic_main_menu_animation_stateless < mediator >
:: logic_main_menu_animation_stateless_consts_type 
:: logic_main_menu_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( shake_shift_x_amplitude_begin , 20 , 1000 ) ;
    platform_math :: make_num_fract ( shake_shift_x_amplitude_end , 5 , 1000 ) ;
    platform_math :: make_num_fract ( shake_shift_x_period_in_seconds , 2 , 10 ) ;
    platform_math :: make_num_fract ( shake_time_from_begin_to_end , 6 , 10 ) ;
    platform_math :: make_num_fract ( shake_time_to_begin , 0 , 10 ) ;
}

template < typename mediator >
shy_logic_main_menu_letters_animation_stateless < mediator >
:: logic_main_menu_letters_animation_stateless_consts_type 
:: logic_main_menu_letters_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( appear_delay_per_col_in_seconds , 2 , 100 ) ;
    platform_math :: make_num_fract ( appear_delay_per_row_in_seconds , 5 , 100 ) ;
    platform_math :: make_num_fract ( appear_scale_begin , 0 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( appear_scale_middle , 3 , 2 ) ;
    platform_math :: make_num_fract ( appear_time_from_begin_to_middle_in_seconds , 1 , 10 ) ;
    platform_math :: make_num_fract ( appear_time_from_middle_to_end_in_seconds , 7 , 10 ) ;
    platform_math :: make_num_fract ( disappear_animation_time_in_seconds , 8 , 10 ) ;
    platform_math :: make_num_fract ( disappear_delay_per_col_in_seconds , 2 , 100 ) ;
    platform_math :: make_num_fract ( disappear_delay_per_row_in_seconds , 5 , 100 ) ;
    platform_math :: make_num_fract ( disappear_scale_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( disappear_scale_end , 1 , 10 ) ;
    platform_math :: make_num_fract ( disappear_time_from_begin_to_end_in_seconds , 3 , 10 ) ;
    platform_math :: make_num_fract ( idle_horizontal_shift_amplitude , 1 , 20 ) ;
    platform_math :: make_num_fract ( idle_horizontal_shift_period_in_seconds , 2 , 1 ) ;
    platform_math :: make_num_fract ( idle_horizontal_shift_phase_per_row , 1 , 2 ) ;
    platform_math :: make_num_fract ( idle_vertical_shift_amplitude , 1 , 30 ) ;
    platform_math :: make_num_fract ( idle_vertical_shift_period_in_seconds , 1 , 1 ) ;
    platform_math :: make_num_fract ( idle_vertical_shift_phase_per_col , 1 , 3 ) ;
    platform_math :: make_num_fract ( idle_vertical_shift_phase_per_row , 1 , 5 ) ;
    platform_math :: make_num_fract ( selection_push_scale_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( selection_push_scale_end , 8 , 10 ) ;
    platform_math :: make_num_fract ( selection_push_scale_middle , 6 , 10 ) ;
    platform_math :: make_num_fract ( selection_push_time_from_begin_to_middle , 10 , 100 ) ;
    platform_math :: make_num_fract ( selection_push_time_from_middle_to_end , 20 , 100 ) ;
    platform_math :: make_num_fract ( selection_scale_max , 11 , 10 ) ;
    platform_math :: make_num_fract ( selection_scale_min , 9 , 10 ) ;
    platform_math :: make_num_fract ( selection_time_stable , 0 , 100 ) ;
    platform_math :: make_num_fract ( selection_time_transition , 30 , 100 ) ;
    platform_math :: make_num_fract ( selection_weight_time_from_begin_to_end , 30 , 100 ) ;
    platform_math :: make_num_fract ( selection_weight_time_to_begin , 10 , 100 ) ;
    platform_math :: make_num_fract ( unselection_weight_time_from_begin_to_end , 7 , 100 ) ;
    platform_math :: make_num_fract ( unselection_weight_time_to_begin , 0 , 100 ) ;
}

template < typename mediator >
shy_logic_main_menu_letters_layout_stateless < mediator >
:: logic_main_menu_letters_layout_stateless_consts_type 
:: logic_main_menu_letters_layout_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( letter_size_fract_horizontal_border , 1 , 1 ) ;
    platform_math :: make_num_fract ( letter_size_fract_horizontal_spacing , 0 , 1 ) ;
    platform_math :: make_num_fract ( letter_size_fract_vertical_border , 1 , 1 ) ;
    platform_math :: make_num_fract ( letter_size_fract_vertical_spacing , 1 , 1 ) ;
    platform_math :: make_num_fract ( menu_position_z , - 3 , 1 ) ;
}

template < typename mediator >
shy_logic_main_menu_letters_meshes_stateless < mediator >
:: logic_main_menu_letters_meshes_stateless_consts_type 
:: logic_main_menu_letters_meshes_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( letter_mesh_color_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( letter_mesh_color_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( letter_mesh_color_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( letter_mesh_color_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( letter_mesh_size , 1 , 1 ) ;
    platform_math :: make_num_fract ( time_between_creation , 50 , 1000 ) ;
}

template < typename mediator >
shy_logic_main_menu_selection_animation_stateless < mediator >
:: logic_main_menu_selection_animation_stateless_consts_type 
:: logic_main_menu_selection_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( appear_horizontal_scale_time_from_begin_to_end , 1 , 10 ) ;
    platform_math :: make_num_fract ( appear_horizontal_scale_time_to_begin , 0 , 10 ) ;
    platform_math :: make_num_fract ( appear_horizontal_scale_value_begin , 8 , 10 ) ;
    platform_math :: make_num_fract ( appear_horizontal_scale_value_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( appear_total_animation_time , 5 , 10 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_time_from_begin_to_middle , 1 , 10 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_time_from_middle_to_end , 2 , 10 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_time_to_begin , 2 , 10 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_value_begin , 10 , 100 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_value_end , 1 , 1 ) ;
    platform_math :: make_num_fract ( appear_vertical_scale_value_middle , 2 , 1 ) ;
    platform_math :: make_num_fract ( disappear_horizontal_scale_time_from_begin_to_end , 1 , 10 ) ;
    platform_math :: make_num_fract ( disappear_horizontal_scale_time_to_begin , 4 , 10 ) ;
    platform_math :: make_num_fract ( disappear_horizontal_scale_value_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( disappear_horizontal_scale_value_end , 0 , 1 ) ;
    platform_math :: make_num_fract ( disappear_vertical_scale_time_from_begin_to_end , 1 , 10 ) ;
    platform_math :: make_num_fract ( disappear_vertical_scale_time_to_begin , 0 , 10 ) ;
    platform_math :: make_num_fract ( disappear_vertical_scale_value_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( disappear_vertical_scale_value_end , 10 , 100 ) ;
    platform_math :: make_num_fract ( idle_attention_horizontal_scale_max , 20 , 20 ) ;
    platform_math :: make_num_fract ( idle_attention_horizontal_scale_min , 19 , 20 ) ;
    platform_math :: make_num_fract ( idle_attention_horizontal_scale_period_in_seconds , 2 , 1 ) ;
    platform_math :: make_num_fract ( idle_attention_vertical_scale_max , 23 , 10 ) ;
    platform_math :: make_num_fract ( idle_attention_vertical_scale_min , 20 , 10 ) ;
    platform_math :: make_num_fract ( idle_attention_vertical_scale_period_in_seconds , 1 , 1 ) ;
    platform_math :: make_num_fract ( idle_position_z , - 3 , 1 ) ;
    platform_math :: make_num_fract ( push_attention_horizontal_scale_max , 200 , 200 ) ;
    platform_math :: make_num_fract ( push_attention_horizontal_scale_min , 185 , 200 ) ;
    platform_math :: make_num_fract ( push_attention_period_in_seconds , 4 , 10 ) ;
    platform_math :: make_num_fract ( push_attention_vertical_scale_max , 250 , 100 ) ;
    platform_math :: make_num_fract ( push_attention_vertical_scale_min , 200 , 100 ) ;
    platform_math :: make_num_fract ( push_horizontal_scale_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( push_horizontal_scale_end , 95 , 100 ) ;
    platform_math :: make_num_fract ( push_horizontal_scale_middle , 90 , 100 ) ;
    platform_math :: make_num_fract ( push_time_from_begin_to_middle , 10 , 100 ) ;
    platform_math :: make_num_fract ( push_time_from_middle_to_end , 20 , 100 ) ;
    platform_math :: make_num_fract ( push_vertical_scale_begin , 1 , 1 ) ;
    platform_math :: make_num_fract ( push_vertical_scale_end , 95 , 100 ) ;
    platform_math :: make_num_fract ( push_vertical_scale_middle , 70 , 100 ) ;
    platform_math :: make_num_fract ( push_weight_max , 1 , 1 ) ;
    platform_math :: make_num_fract ( push_weight_min , 0 , 1 ) ;
    platform_math :: make_num_fract ( push_weight_time_from_begin_to_end , 20 , 100 ) ;
    platform_math :: make_num_fract ( push_weight_time_to_begin , 10 , 100 ) ;
    platform_math :: make_num_fract ( select_horizontal_scale_time_from_begin_to_end , 7 , 100 ) ;
    platform_math :: make_num_fract ( select_horizontal_scale_time_to_begin , 0 , 100 ) ;
    platform_math :: make_num_fract ( select_horizontal_scale_value_begin , 8 , 10 ) ;
    platform_math :: make_num_fract ( select_horizontal_scale_value_end , 10 , 10 ) ;
    platform_math :: make_num_fract ( select_total_animation_time , 7 , 100 ) ;
    platform_math :: make_num_fract ( select_vertical_scale_time_from_begin_to_end , 7 , 100 ) ;
    platform_math :: make_num_fract ( select_vertical_scale_time_to_begin , 0 , 100 ) ;
    platform_math :: make_num_fract ( select_vertical_scale_value_begin , 5 , 10 ) ;
    platform_math :: make_num_fract ( select_vertical_scale_value_end , 10 , 10 ) ;
    platform_math :: make_num_fract ( unselect_horizontal_scale_time_from_begin_to_end , 7 , 100 ) ;
    platform_math :: make_num_fract ( unselect_horizontal_scale_time_to_begin , 0 , 100 ) ;
    platform_math :: make_num_fract ( unselect_horizontal_scale_value_begin , 10 , 10 ) ;
    platform_math :: make_num_fract ( unselect_horizontal_scale_value_end , 8 , 10 ) ;
    platform_math :: make_num_fract ( unselect_total_animation_time , 7 , 100 ) ;
    platform_math :: make_num_fract ( unselect_vertical_scale_time_from_begin_to_end , 7 , 100 ) ;
    platform_math :: make_num_fract ( unselect_vertical_scale_time_to_begin , 0 , 100 ) ;
    platform_math :: make_num_fract ( unselect_vertical_scale_value_begin , 10 , 10 ) ;
    platform_math :: make_num_fract ( unselect_vertical_scale_value_end , 5 , 10 ) ;
}

template < typename mediator >
shy_logic_main_menu_selection_stateless < mediator >
:: logic_main_menu_selection_stateless_consts_type 
:: logic_main_menu_selection_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( mesh_color_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_g , 1 , 4 ) ;
    platform_math :: make_num_fract ( mesh_color_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_size , 1 , 1 ) ;
    platform_math :: make_num_fract ( selected_rect_vertical_scale , 20 , 10 ) ;
}

template < typename mediator >
shy_logic_observer_animation_stateless < mediator >
:: logic_observer_animation_stateless_consts_type 
:: logic_observer_animation_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( flight_horizontal_offset_amplitude , 1 , 3 ) ;
    platform_math :: make_num_fract ( flight_horizontal_offset_period , 11 , 10 ) ;
    platform_math :: make_num_fract ( flight_target_z , - 1 , 1 ) ;
    platform_math :: make_num_fract ( flight_vertical_offset_amplitude , 1 , 3 ) ;
    platform_math :: make_num_fract ( flight_vertical_offset_period , 17 , 10 ) ;
}

template < typename mediator >
shy_logic_ortho_stateless < mediator >
:: logic_ortho_stateless_consts_type 
:: logic_ortho_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( z_far , 50 , 1 ) ;
    platform_math :: make_num_fract ( z_near , 1 , 1 ) ;
}

template < typename mediator >
shy_logic_perspective_stateless < mediator >
:: logic_perspective_stateless_consts_type 
:: logic_perspective_stateless_consts_type ( )
{
    platform_math :: make_num_fract ( z_far_unscaled , 50 , 1 ) ;
}

template < typename mediator >
shy_logic_room_stateless < mediator >
:: logic_room_stateless_consts_type 
:: logic_room_stateless_consts_type ( )
{
    platform_math :: make_num_whole ( texture_grid_size , 10 ) ;
    platform_math :: make_num_fract ( mesh_bottom_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_bottom_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_bottom_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_bottom_side_v_top , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_bottom_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_bottom_b , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_bottom_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_bottom_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_far_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_far_b , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_far_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_far_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_left_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_left_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_left_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_left_r , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_near_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_near_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_near_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_near_r , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_right_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_right_b , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_right_g , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_right_r , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_top_a , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_top_b , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_top_g , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_color_top_r , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_far_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_far_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_far_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_far_side_v_top , 1 , 3 ) ;
    platform_math :: make_num_fract ( mesh_left_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_left_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_left_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_left_side_v_top , 1 , 3 ) ;
    platform_math :: make_num_fract ( mesh_near_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_near_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_near_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_near_side_v_top , 1 , 3 ) ;
    platform_math :: make_num_fract ( mesh_position_x , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_position_y , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_position_z , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_right_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_right_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_right_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_right_side_v_top , 1 , 3 ) ;
    platform_math :: make_num_fract ( mesh_top_side_u_left , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_top_side_u_right , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_top_side_v_bottom , 0 , 1 ) ;
    platform_math :: make_num_fract ( mesh_top_side_v_top , 1 , 1 ) ;
    platform_math :: make_num_fract ( mesh_x_left , - 10 , 1 ) ;
    platform_math :: make_num_fract ( mesh_x_right , 10 , 1 ) ;
    platform_math :: make_num_fract ( mesh_y_bottom , - 3 , 1 ) ;
    platform_math :: make_num_fract ( mesh_y_top , 3 , 1 ) ;
    platform_math :: make_num_fract ( mesh_z_far , - 10 , 1 ) ;
    platform_math :: make_num_fract ( mesh_z_near , 10 , 1 ) ;
    platform_math :: make_num_fract ( room_show_time , 10 , 1 ) ;
    platform_math :: make_num_fract ( texture_alpha , 1 , 1 ) ;
    platform_math :: make_num_fract ( texture_paper_intensity , 3 , 4 ) ;
    platform_math :: make_num_fract ( texture_pen_intensity , 1 , 1 ) ;
}

template < typename mediator >
shy_logic_title_stateless < mediator >
:: logic_title_stateless_consts_type 
:: logic_title_stateless_consts_type ( )
{
    platform_math :: make_num_whole ( appear_duration_in_frames , 250 ) ;
    platform_math :: make_num_whole ( disappear_duration_in_frames , 150 ) ;
    platform_math :: make_num_whole ( frames_between_letters , 5 ) ;
    platform_math :: make_num_fract ( appear_pos_angle_periods , 11 , 2 ) ;
    platform_math :: make_num_fract ( appear_rubber_first , 19 , 20 ) ;
    platform_math :: make_num_fract ( appear_rubber_last , 19 , 20 ) ;
    platform_math :: make_num_fract ( disappear_pos_angle_periods , 22 , 2 ) ;
    platform_math :: make_num_fract ( disappear_rubber_first , 59 , 60 ) ;
    platform_math :: make_num_fract ( disappear_rubber_last , 29 , 30 ) ;
    platform_math :: make_num_fract ( scene_scale_max , 9 , 10 ) ;
    platform_math :: make_num_fract ( scene_scale_min , 7 , 10 ) ;
    platform_math :: make_num_fract ( spin_radius_in_letters , 2 , 1 ) ;
}

// autogenerated file end

