#include "./shy_animation_injections.h"

#include "src/common/engine/math/stateless/shy_stateless_injections.h"
#include "src/common/engine/taker/helper/shy_helper_injections.h"
#include "src/common/logic/salutation/letters/animation/appear/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/appear/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/animation/disappear/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/disappear/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/animation/layout/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/layout/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/animation/roll/in/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/roll/in/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/animation/roll/out/transform/checker/shy_checker_injections.h"
#include "src/common/logic/salutation/letters/animation/roll/out/transform/request/sender/shy_sender_injections.h"
#include "src/common/logic/salutation/letters/animation/transform/reply/sender/shy_sender_injections.h"
#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"
#include "src/injections/platform/matrix/shy_matrix.h"
#include "src/injections/platform/vector/shy_vector.h"

#include "./shy_animation.hpp"
