const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: appear_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: appear_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: appear_time ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: appear_time_shift_per_letter ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: disappear_scale_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: disappear_scale_cut_off ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: disappear_scale_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: disappear_time ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: disappear_time_shift_per_letter ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: layout_border_height ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: layout_border_width ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: layout_step ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_position_radius_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_position_radius_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_position_spin_periods_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_position_spin_periods_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_rotation_periods_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_rotation_periods_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_time ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_in_time_shift_per_letter ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_position_radius_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_position_radius_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_position_spin_periods_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_position_spin_periods_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_rotation_periods_begin ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_rotation_periods_end ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_time ;
const so_called_platform_math_num_fract_type shy_common_logic_salutation_letters_animation_consts :: roll_out_time_shift_per_letter ;

void shy_common_logic_salutation_letters_animation_consts :: binding ( )
{
}
