#ifndef _shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_sender_injections_included
#define _shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_sender_injections_included

#include "common/engine/render/message/blend_src_alpha_dst_one_minus_alpha/shy_blend_src_alpha_dst_one_minus_alpha_injections.h"

#include "./shy_blend_src_alpha_dst_one_minus_alpha.h"

typedef shy_common_engine_render_blend_src_alpha_dst_one_minus_alpha_sender so_called_common_engine_render_blend_src_alpha_dst_one_minus_alpha_sender ;

#endif

