#ifndef _shy_sender_common_engine_render_blend_src_alpha_dst_one_minus_alpha_injections_included
#define _shy_sender_common_engine_render_blend_src_alpha_dst_one_minus_alpha_injections_included

#include "../../message/blend_src_alpha_dst_one_minus_alpha/shy_blend_src_alpha_dst_one_minus_alpha_injections.h"

#include "./shy_blend_src_alpha_dst_one_minus_alpha.h"

typedef shy_sender_common_engine_render_blend_src_alpha_dst_one_minus_alpha so_called_sender_common_engine_render_blend_src_alpha_dst_one_minus_alpha ;

#endif

