#ifndef _shy_loadable_consts_reflection_logic_ortho_injections_included
#define _shy_loadable_consts_reflection_logic_ortho_injections_included

#include "./shy_ortho.h"

typedef shy_loadable_consts_reflection_logic_ortho so_called_loadable_consts_reflection_logic_ortho ;

#endif
