#ifndef _shy_platform_sound_loader_winapi_stereo_resource_id_type_injections_included
#define _shy_platform_sound_loader_winapi_stereo_resource_id_type_injections_included

#include "src/injections/lib/std/int32/t/shy_t.h"

#include "./shy_type.h"

typedef shy_platform_sound_loader_winapi_stereo_resource_id_type so_called_platform_sound_loader_winapi_stereo_resource_id_type ;

#endif
