#ifndef _shy_loadable_content_condition_group_container_type_injections_included
#define _shy_loadable_content_condition_group_container_type_injections_included

#include "loadable/fsm/content/type/condition_group/shy_condition_group_injections.h"

#include "./shy_condition_group_container.h"

typedef shy_loadable_fsm_content_condition_group_container_type so_called_loadable_fsm_content_condition_group_container_type ;

#endif
