// autogenerated file begin

const so_called_platform_math_num_whole_type so_called_common_logic_application_consts :: skip_amusement = so_called_platform_math :: init_num_whole ( 0 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_application_consts :: skip_fader = so_called_platform_math :: init_num_whole ( 0 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_application_consts :: skip_main_menu = so_called_platform_math :: init_num_whole ( 0 ) ;
const so_called_platform_math_num_whole_type so_called_common_logic_application_consts :: skip_salutation = so_called_platform_math :: init_num_whole ( 0 ) ;

// autogenerated file end
