#ifndef _shy_message_common_logic_vacuum_update_injections_included
#define _shy_message_common_logic_vacuum_update_injections_included

#include "./shy_update.h"

typedef shy_message_common_logic_vacuum_update so_called_message_common_logic_vacuum_update ;

#endif
