#ifndef _shy_loadable_consts_reflection_logic_salutation_animation_injections_included
#define _shy_loadable_consts_reflection_logic_salutation_animation_injections_included

#include "./shy_animation.h"

typedef shy_loadable_consts_reflection_logic_salutation_animation so_called_loadable_consts_reflection_logic_salutation_animation ;

#endif
