#include "./shy_image_injections.h"

#include "src/common/logic/image/prepared/sender/shy_sender_injections.h"
#include "src/common/logic/image/render/reply/sender/shy_sender_injections.h"

#include "src/common/engine/math/stateless/shy_stateless_injections.h"
#include "src/common/engine/render/blend/disable/sender/shy_sender_injections.h"
#include "src/common/engine/render/blend/src/alpha/dst/one/minus/alpha/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/create/request/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/finalize/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/render/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/transform/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/triangle/strip/index/value/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/vertex/color/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/vertex/position/sender/shy_sender_injections.h"
#include "src/common/engine/render/mesh/set/vertex/tex/coord/sender/shy_sender_injections.h"
#include "src/common/engine/render/texture/create/request/sender/shy_sender_injections.h"
#include "src/common/engine/render/texture/finalize/sender/shy_sender_injections.h"
#include "src/common/engine/render/texture/load/from/resource/sender/shy_sender_injections.h"
#include "src/common/engine/render/texture/loader/ready/request/sender/shy_sender_injections.h"
#include "src/common/engine/render/texture/select/sender/shy_sender_injections.h"
#include "src/common/engine/render/stateless/shy_stateless_injections.h"

#include "src/injections/platform/conditions/shy_conditions.h"
#include "src/injections/platform/math/consts/shy_consts.h"
#include "src/injections/platform/math/shy_math.h"
#include "src/injections/platform/matrix/shy_matrix.h"

#include "./shy_image.hpp"

