#ifndef _shy_common_logic_door_animation_appear_transform_request_sender_injections_included
#define _shy_common_logic_door_animation_appear_transform_request_sender_injections_included

#include "../../message/appear_transform_request/shy_appear_transform_request_injections.h"

#include "./shy_appear_transform_request.h"

typedef shy_common_logic_door_animation_appear_transform_request_sender so_called_common_logic_door_animation_appear_transform_request_sender ;

#endif
