#ifndef _shy_common_logic_entities_origin_reply_sender_injections_included
#define _shy_common_logic_entities_origin_reply_sender_injections_included

#include "common/logic/entities/message/origin_reply/shy_origin_reply_injections.h"

#include "./shy_origin_reply.h"

typedef shy_common_logic_entities_origin_reply_sender so_called_common_logic_entities_origin_reply_sender ;

#endif
