#ifndef _shy_message_common_logic_salutation_letters_meshes_generate_injections_included
#define _shy_message_common_logic_salutation_letters_meshes_generate_injections_included

#include "./shy_generate.h"

typedef shy_message_common_logic_salutation_letters_meshes_generate so_called_message_common_logic_salutation_letters_meshes_generate ;

#endif
