#ifndef _shy_common_engine_render_texture_create_request_sender_injections_included
#define _shy_common_engine_render_texture_create_request_sender_injections_included

#include "common/engine/render/message/texture_create_request/shy_texture_create_request_injections.h"

#include "./shy_texture_create_request.h"

typedef shy_common_engine_render_texture_create_request_sender so_called_common_engine_render_texture_create_request_sender ;

#endif

