#ifndef _shy_common_logic_salutation_letters_animation_disappear_step_sender_injections_included
#define _shy_common_logic_salutation_letters_animation_disappear_step_sender_injections_included

#include "src/common/logic/salutation/letters/animation/disappear/step/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_letters_animation_disappear_step_sender so_called_common_logic_salutation_letters_animation_disappear_step_sender ;

#endif
