#ifndef _shy_sender_common_logic_salutation_renderer_render_injections_included
#define _shy_sender_common_logic_salutation_renderer_render_injections_included

#include "../message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_renderer_render so_called_sender_common_logic_salutation_renderer_render ;

#endif
