#ifndef _shy_common_logic_salutation_renderer_render_sender_injections_included
#define _shy_common_logic_salutation_renderer_render_sender_injections_included

#include "src/common/logic/salutation/renderer/render/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_salutation_renderer_render_sender so_called_common_logic_salutation_renderer_render_sender ;

#endif
