#ifndef _shy_common_logic_perspective_injections_included
#define _shy_common_logic_perspective_injections_included

#include "shy_perspective.h"

typedef shy_common_logic_perspective_scheduled so_called_common_logic_perspective ;

#endif
