#ifndef _shy_common_engine_render_texture_set_texel_rgba_message_injections_included
#define _shy_common_engine_render_texture_set_texel_rgba_message_injections_included

#include "common/engine/render/type/texture_id/shy_texture_id_injections.h"
#include "injections/platform/math/type/num_fract/shy_num_fract.h"

#include "./shy_texture_set_texel_rgba.h"

typedef shy_common_engine_render_texture_set_texel_rgba_message so_called_common_engine_render_texture_set_texel_rgba_message ;

#endif
