#ifndef _shy_common_logic_blanket_mesh_set_transform_message_injections_included
#define _shy_common_logic_blanket_mesh_set_transform_message_injections_included

#include "injections/platform/matrix/type/data/shy_data.h"

#include "./shy_mesh_set_transform.h"

typedef shy_common_logic_blanket_mesh_set_transform_message so_called_common_logic_blanket_mesh_set_transform_message ;

#endif
