#ifndef _shy_win_platform_render_texture_loader_resource_id_type_injections_included
#define _shy_win_platform_render_texture_loader_resource_id_type_injections_included

#include "src/platform/render/texture/loader/winapi/resource/id/type/shy_type_injections.h"
typedef so_called_platform_render_texture_loader_winapi_resource_id_type so_called_platform_render_texture_loader_resource_id_type ;

#endif
