#ifndef _shy_sender_common_logic_salutation_letters_text_storage_add_letter_injections_included
#define _shy_sender_common_logic_salutation_letters_text_storage_add_letter_injections_included

#include "../message/shy_message_injections.h"
#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_text_storage_add_letter so_called_sender_common_logic_salutation_letters_text_storage_add_letter ;

#endif
