#ifndef _shy_iphone_platform_math_num_whole_type_injections_included
#define _shy_iphone_platform_math_num_whole_type_injections_included

#include "src/platform/math/int/float/num/whole/type/shy_type_injections.h"
typedef so_called_platform_math_int_float_num_whole_type so_called_platform_math_num_whole_type ;

#endif

