#ifndef _shy_type_macosx_platform_render_vertex_data_injections_included
#define _shy_type_macosx_platform_render_vertex_data_injections_included

#include "platform/render/opengl/type/vertex_data/shy_vertex_data_injections.h"
typedef so_called_type_platform_render_opengl_vertex_data so_called_type_platform_render_vertex_data ;

#endif
