#include "./shy_update_injections.h"

#include "../../animation/shake/shy_shake_injections.h"
#include "../../choice/shy_choice_injections.h"
#include "../../letters/animation/appear/shy_appear_injections.h"
#include "../../letters/animation/disappear/shy_disappear_injections.h"
#include "../../letters/animation/idle/shy_idle_injections.h"
#include "../../letters/animation/selection/shy_selection_injections.h"
#include "../../letters/animation/selection_push/shy_selection_push_injections.h"
#include "../../letters/animation/selection_weight/shy_selection_weight_injections.h"
#include "../../letters/animation/unselection_weight/shy_unselection_weight_injections.h"
#include "../../letters/meshes/creation_director/shy_creation_director_injections.h"
#include "../../selection/animation/appear/shy_appear_injections.h"
#include "../../selection/animation/disappear/shy_disappear_injections.h"
#include "../../selection/animation/idle_attention/shy_idle_attention_injections.h"
#include "../../selection/animation/push/shy_push_injections.h"
#include "../../selection/animation/push_attention/shy_push_attention_injections.h"
#include "../../selection/animation/push_weight/shy_push_weight_injections.h"
#include "../../selection/animation/select/shy_select_injections.h"
#include "../../selection/animation/unselect/shy_unselect_injections.h"
#include "../../shy_main_menu_injections.h"

#include "./shy_update.hpp"
