#ifndef _shy_sender_common_logic_salutation_letters_meshes_generator_update_injections_included
#define _shy_sender_common_logic_salutation_letters_meshes_generator_update_injections_included

#include "common/logic/salutation/letters/meshes/generator/update/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_sender_common_logic_salutation_letters_meshes_generator_update so_called_sender_common_logic_salutation_letters_meshes_generator_update ;

#endif
