#ifndef _shy_common_engine_render_matrix_load_sender_injections_included
#define _shy_common_engine_render_matrix_load_sender_injections_included

#include "common/engine/render/message/matrix_load/shy_matrix_load_injections.h"

#include "./shy_matrix_load.h"

typedef shy_common_engine_render_matrix_load_sender so_called_common_engine_render_matrix_load_sender ;

#endif

