#ifndef _shy_sender_common_logic_blanket_mesh_render_request_injections_included
#define _shy_sender_common_logic_blanket_mesh_render_request_injections_included

#include "../../message/mesh_render_request/shy_mesh_render_request_injections.h"

#include "./shy_mesh_render_request.h"

typedef shy_sender_common_logic_blanket_mesh_render_request so_called_sender_common_logic_blanket_mesh_render_request ;

#endif
