#ifndef _shy_common_logic_main_menu_letters_meshes_mesh_id_reply_sender_injections_included
#define _shy_common_logic_main_menu_letters_meshes_mesh_id_reply_sender_injections_included

#include "src/common/logic/main/menu/letters/meshes/mesh/id/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_main_menu_letters_meshes_mesh_id_reply_sender so_called_common_logic_main_menu_letters_meshes_mesh_id_reply_sender ;

#endif
