#ifndef _shy_common_engine_render_texture_unselect_message_injections_included
#define _shy_common_engine_render_texture_unselect_message_injections_included

#include "./shy_message.h"

typedef shy_common_engine_render_texture_unselect_message so_called_common_engine_render_texture_unselect_message ;

#endif
