#ifndef _shy_loadable_consts_content_value_whole_binding_type_injections_included
#define _shy_loadable_consts_content_value_whole_binding_type_injections_included

#include "src/injections/platform/math/num/whole/type/shy_type.h"

#include "./shy_type.h"

typedef shy_loadable_consts_content_value_whole_binding_type so_called_loadable_consts_content_value_whole_binding_type ;

#endif
