#ifndef _shy_common_logic_main_menu_letters_layout_row_rect_request_message_injections_included
#define _shy_common_logic_main_menu_letters_layout_row_rect_request_message_injections_included

#include "injections/platform/math/type/num_whole/shy_num_whole.h"

#include "./shy_row_rect_request.h"

typedef shy_common_logic_main_menu_letters_layout_row_rect_request_message so_called_common_logic_main_menu_letters_layout_row_rect_request_message ;

#endif
