#ifndef _shy_common_engine_render_mesh_set_triangle_fan_index_value_message_injections_included
#define _shy_common_engine_render_mesh_set_triangle_fan_index_value_message_injections_included

#include "common/engine/render/type/mesh_id/shy_mesh_id_injections.h"

#include "./shy_mesh_set_triangle_fan_index_value.h"

typedef shy_common_engine_render_mesh_set_triangle_fan_index_value_message so_called_common_engine_render_mesh_set_triangle_fan_index_value_message ;

#endif
