#ifndef _shy_type_loadable_fsm_content_system_container_injections_included
#define _shy_type_loadable_fsm_content_system_container_injections_included

#include "loadable/fsm/content/type/system/shy_system_injections.h"

#include "./shy_system_container.h"

typedef shy_type_loadable_fsm_content_system_container so_called_type_loadable_fsm_content_system_container ;

#endif
