#ifndef _shy_loadable_fsm_content_system_container_type_injections_included
#define _shy_loadable_fsm_content_system_container_type_injections_included

#include "loadable/fsm/content/type/system/shy_system_injections.h"

#include "./shy_system_container.h"

typedef shy_loadable_fsm_content_system_container_type so_called_loadable_fsm_content_system_container_type ;

#endif
