#ifndef _shy_loadable_fsm_content_condition_input_container_type_injections_included
#define _shy_loadable_fsm_content_condition_input_container_type_injections_included

#include "loadable/fsm/content/type/condition_input/shy_condition_input_injections.h"

#include "./shy_condition_input_container.h"

typedef shy_loadable_fsm_content_condition_input_container_type so_called_loadable_fsm_content_condition_input_container_type ;

#endif
