#ifndef _shy_type_loadable_fsm_content_condition_input_container_injections_included
#define _shy_type_loadable_fsm_content_condition_input_container_injections_included

#include "loadable/fsm/content/type/condition_input/shy_condition_input_injections.h"

#include "./shy_condition_input_container.h"

typedef shy_type_loadable_fsm_content_condition_input_container so_called_type_loadable_fsm_content_condition_input_container ;

#endif
