#ifndef _shy_common_engine_render_disable_depth_test_sender_injections_included
#define _shy_common_engine_render_disable_depth_test_sender_injections_included

#include "src/common/engine/render/disable/depth/test/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_engine_render_disable_depth_test_sender so_called_common_engine_render_disable_depth_test_sender ;

#endif

