#include "../../common/init/shy_init_injections.h"
#include "../../common/sender/done/shy_done_injections.h"
#include "../../common/sender/init/shy_init_injections.h"
#include "../../common/sender/render/shy_render_injections.h"
#include "../../common/sender/update/shy_update_injections.h"
#include "../../common/sender/video_mode_changed/shy_video_mode_changed_injections.h"
#include "../../injections/platform/math/consts/shy_consts.h"
#include "../../injections/platform/render/shy_render.h"
#include "../../injections/platform/render/texture_loader/shy_texture_loader.h"
#include "../../injections/platform/scheduler/shy_scheduler.h"
#include "../../loadable/loader/shy_loader_injections.h"

#include "./shy_loadable_injections.h"
#include "./shy_loadable.hpp"
