#ifndef _shy_common_logic_observer_animation_flight_transform_reply_sender_injections_included
#define _shy_common_logic_observer_animation_flight_transform_reply_sender_injections_included

#include "src/common/logic/observer/animation/flight/transform/reply/message/shy_message_injections.h"

#include "./shy_sender.h"

typedef shy_common_logic_observer_animation_flight_transform_reply_sender so_called_common_logic_observer_animation_flight_transform_reply_sender ;

#endif
