#ifndef _shy_common_logic_main_menu_letters_layout_position_injections_included
#define _shy_common_logic_main_menu_letters_layout_position_injections_included

#include "shy_position.h"

typedef shy_common_logic_main_menu_letters_layout_position_scheduled so_called_common_logic_main_menu_letters_layout_position ;

#endif
