#ifndef _shy_common_logic_main_menu_letters_layout_row_rect_injections_included
#define _shy_common_logic_main_menu_letters_layout_row_rect_injections_included

#include "shy_row_rect.h"

typedef shy_common_logic_main_menu_letters_layout_row_rect_scheduled so_called_common_logic_main_menu_letters_layout_row_rect ;

#endif
