#ifndef _shy_sender_common_logic_main_menu_letters_meshes_count_reply_injections_included
#define _shy_sender_common_logic_main_menu_letters_meshes_count_reply_injections_included

#include "../../message/count_reply/shy_count_reply_injections.h"

#include "./shy_count_reply.h"

typedef shy_sender_common_logic_main_menu_letters_meshes_count_reply so_called_sender_common_logic_main_menu_letters_meshes_count_reply ;

#endif
