#ifndef _shy_macosx_platform_consts_insider_injections_included
#define _shy_macosx_platform_consts_insider_injections_included

#include "src/platform/consts/insider/shy_insider_injections.h"

#endif
