#ifndef _shy_loadable_consts_reflection_logic_vacuum_injections_included
#define _shy_loadable_consts_reflection_logic_vacuum_injections_included

#include "./shy_vacuum.h"

typedef shy_loadable_consts_reflection_logic_vacuum so_called_loadable_consts_reflection_logic_vacuum ;

#endif
